import { describe, it, expect } from "vitest";
import {
    paramMappings,
    paramTransforms,
    canonicalNewParamOrder,
    transformKinds,
    PARAM_COUNT,
    NEW_PARAM_BASE,
    NEW_PARAM_COUNT,
    BENDRANGE_LEGACY_INDEX,
} from "../src/obxf-param-mappings";
import sidecar from "../src/generated/param-table.json";

// The generated file is AUTO-GENERATED by tools/gen-param-table.mjs from
// tools/param-spec.mjs. These tests validate the GENERATED reality:
//   - 80 rows (BENDRANGE is ONE row; the split half lives in
//     secondaryNewId/secondaryMethod — the old hand file had 81 rows)
//   - constants, canonical NEW-param order, and drum classification
//   - the PURE transform functions (paramTransforms) round-trip / hit
//     golden values for the exact-inverse and representative-inverse kinds
//   - consistency with the machine-readable sidecar (param-table.json)

const EXACT_ROUNDTRIP_KINDS = new Set(["IDENTITY", "MUL", "LOGSC_INVLOGSC", "PAN"]);
const kindByNewId = new Map<string, string>();
for (const m of paramMappings) {
    if (m.newId) kindByNewId.set(m.newId, m.transformKind ?? "");
    if (m.secondaryNewId) kindByNewId.set(m.secondaryNewId, m.transformKind ?? "");
}

describe("obxf-param-mappings (generated)", () => {
    describe("structure", () => {
        it("has exactly 80 rows (BENDRANGE is ONE row)", () => {
            expect(paramMappings.length).toBe(80);
            expect(paramMappings.length).toBe(PARAM_COUNT);
        });

        it("every row has all required fields", () => {
            for (const m of paramMappings) {
                expect(typeof m.legacyIndex).toBe("number");
                expect(typeof m.legacyName).toBe("string");
                expect(typeof m.legacyMethod).toBe("string");
                expect(typeof m.newId).toBe("string");
                // newMethod is string | null
                expect(m.newMethod === null || typeof m.newMethod === "string").toBe(true);
                // generated extras
                expect(m.specialInline).toBe(typeof m.specialInline === "boolean" ? m.specialInline : undefined);
                expect(["none", "global", "smoother", "voice"]).toContain(m.drumClass);
                expect(typeof m.drumRestoreSkip).toBe("boolean");
                if (m.newId === "") {
                    expect(m.newMethod).toBeNull();
                    expect(m.transformKind).toBeNull();
                } else {
                    expect(typeof m.transformKind).toBe("string");
                    expect(Object.keys(transformKinds)).toContain(m.transformKind as string);
                }
            }
        });

        it("exports the spec constants", () => {
            expect(PARAM_COUNT).toBe(80);
            expect(NEW_PARAM_BASE).toBe(200);
            expect(NEW_PARAM_COUNT).toBe(28);
            expect(BENDRANGE_LEGACY_INDEX).toBe(6);
        });
    });

    describe("legacy index coverage", () => {
        it("covers indices 0..79 exactly once each", () => {
            const counts = new Map<number, number>();
            for (const m of paramMappings) {
                counts.set(m.legacyIndex, (counts.get(m.legacyIndex) ?? 0) + 1);
            }
            for (let i = 0; i <= 79; i++) {
                expect(counts.get(i) ?? 0, `legacy index ${i}`).toBe(1);
            }
        });

        it("no legacy index outside 0..79", () => {
            for (const m of paramMappings) {
                expect(m.legacyIndex).toBeGreaterThanOrEqual(0);
                expect(m.legacyIndex).toBeLessThanOrEqual(79);
            }
        });
    });

    describe("BENDRANGE split encoding", () => {
        it("row 6 carries the split half via secondaryNewId/secondaryMethod", () => {
            const bend = paramMappings.find(m => m.legacyIndex === BENDRANGE_LEGACY_INDEX);
            expect(bend).toBeDefined();
            expect(bend!.legacyName).toBe("BENDRANGE");
            expect(bend!.newId).toBe("PitchBendUp");
            expect(bend!.newMethod).toBe("processBendUpRange");
            expect(bend!.secondaryNewId).toBe("PitchBendDown");
            expect(bend!.secondaryMethod).toBe("processBendDownRange");
            expect(bend!.transformKind).toBe("SPLIT_BENDRANGE");
        });

        it("only BENDRANGE carries secondary fields", () => {
            for (const m of paramMappings) {
                if (m.legacyIndex === BENDRANGE_LEGACY_INDEX) continue;
                expect(m.secondaryNewId, `${m.legacyName}`).toBeUndefined();
                expect(m.secondaryMethod, `${m.legacyName}`).toBeUndefined();
            }
        });

        it("the split half name collides with nothing", () => {
            const ids = new Set(paramMappings.filter(m => m.newId).map(m => m.newId));
            expect(ids.has("PitchBendDown")).toBe(false);
            expect(canonicalNewParamOrder).not.toContain("PitchBendDown");
        });
    });

    describe("specialInline rows", () => {
        it("exactly LFOFREQ(17) and LFO_SYNC(72) are specialInline", () => {
            const inline = paramMappings.filter(m => m.specialInline).map(m => m.legacyIndex);
            expect(inline).toEqual([17, 72]);
            expect(paramMappings.find(m => m.legacyIndex === 17)!.transformKind).toBe("LFO1_RATE");
            expect(paramMappings.find(m => m.legacyIndex === 72)!.transformKind).toBe("LFO1_SYNC");
        });

        it("their name-keyed transforms carry invert null", () => {
            expect(paramTransforms["LFO1Rate"].invert).toBeNull();
            expect(paramTransforms["LFO1TempoSync"].invert).toBeNull();
        });
    });

    describe("uniqueness", () => {
        it("no duplicate newId strings (among non-empty)", () => {
            const ids = paramMappings
                .filter(m => m.newId && m.newId.length > 0)
                .map(m => m.newId);
            const unique = new Set(ids);
            expect(unique.size).toBe(ids.length);
        });

        it("canonicalNewParamOrder has 28 unique names, none legacy-mapped", () => {
            expect(canonicalNewParamOrder.length).toBe(NEW_PARAM_COUNT);
            expect(new Set(canonicalNewParamOrder).size).toBe(NEW_PARAM_COUNT);
            const legacyIds = new Set(paramMappings.filter(m => m.newId).map(m => m.newId));
            for (const name of canonicalNewParamOrder) {
                expect(legacyIds.has(name), `${name} must not be legacy-mapped`).toBe(false);
            }
        });
    });

    describe("consistency checks", () => {
        it("UNDEFINED (index 0) has empty newId and null newMethod", () => {
            const undef = paramMappings.find(m => m.legacyIndex === 0);
            expect(undef).toBeDefined();
            expect(undef!.newId).toBe("");
            expect(undef!.newMethod).toBeNull();
        });

        it("MIDILEARN (index 1) is marked REMOVED", () => {
            const ml = paramMappings.find(m => m.legacyIndex === 1);
            expect(ml).toBeDefined();
            expect(ml!.newMethod).toBeNull();
            expect(ml!.newNotes).toContain("REMOVED");
        });

        it("drum classification matches the spec sets (LATK exercises both axes)", () => {
            const global = paramMappings.filter(m => m.drumClass === "global").map(m => m.legacyIndex);
            expect(global).toEqual([2, 3, 4, 5, 6, 7, 8, 9, 12, 13, 14, 15, 17, 18, 19, 20, 47,
                62, 63, 64, 65, 66, 67, 68, 69, 72]);
            expect(paramMappings.filter(m => m.drumClass === "smoother").map(m => m.legacyIndex))
                .toEqual([44, 45, 46, 51, 52, 53, 54]);
            expect(paramMappings.filter(m => m.drumClass === "none").map(m => m.legacyIndex))
                .toEqual([0, 1, 32, 70, 71]);
            expect(paramMappings.filter(m => m.drumRestoreSkip).map(m => m.legacyIndex))
                .toEqual([3, 40, 41, 42, 51, 54]);
            // 51 (LATK) is BOTH smoother AND restore-skip — independent axes.
            const latk = paramMappings.find(m => m.legacyIndex === 51)!;
            expect(latk.drumClass).toBe("smoother");
            expect(latk.drumRestoreSkip).toBe(true);
        });
    });

    describe("sidecar consistency (src/generated/param-table.json)", () => {
        it("counts match the generated TS reality", () => {
            expect(sidecar.legacyRows.length).toBe(80);
            expect(sidecar.newParams.length).toBe(28);
            expect(sidecar.canonicalNewParamOrder.length).toBe(28);
            // 75 legacy names + 1 BENDRANGE split half + 28 NEW = 104
            expect(sidecar.nameIndex.length).toBe(104);
            expect(sidecar.constants.nameIndexCount).toBe(104);
        });

        it("name index is sorted, unique, and cross-references resolve", () => {
            const names = sidecar.nameIndex.map(e => e.name);
            for (let i = 1; i < names.length; i++) {
                expect(names[i - 1] < names[i], `nameIndex sorted at ${i}: ${names[i - 1]} < ${names[i]}`).toBe(true);
            }
            expect(new Set(names).size).toBe(names.length);
            const legacyIds = new Set(paramMappings.filter(m => m.newId).map(m => m.newId));
            const newIds = new Set(canonicalNewParamOrder);
            for (const e of sidecar.nameIndex) {
                if (e.legacyIndex >= 0) {
                    expect(e.newOrdinal).toBe(-1);
                    const row = sidecar.legacyRows[e.legacyIndex];
                    expect([row.newId, row.secondaryNewId]).toContain(e.name);
                } else {
                    expect(e.newOrdinal).toBeGreaterThanOrEqual(0);
                    expect(newIds.has(e.name)).toBe(true);
                    expect(legacyIds.has(e.name)).toBe(false);
                }
            }
        });

        it("legacy rows in the sidecar mirror paramMappings", () => {
            expect(sidecar.legacyRows.length).toBe(paramMappings.length);
            for (let i = 0; i < paramMappings.length; i++) {
                expect(sidecar.legacyRows[i].legacyIndex).toBe(i);
                expect(sidecar.legacyRows[i].newId).toBe(paramMappings[i].newId);
                expect(sidecar.legacyRows[i].method || null).toBe(paramMappings[i].newMethod);
            }
        });
    });

    describe("paramTransforms (pure golden tests)", () => {
        it("covers every legacy-mapped streaming name (76 = 75 rows + PitchBendDown)", () => {
            expect(Object.keys(paramTransforms).length).toBe(76);
            for (const m of paramMappings) {
                if (m.newId) expect(paramTransforms[m.newId], m.newId).toBeDefined();
            }
            expect(paramTransforms["PitchBendDown"]).toBeDefined();
            // NEW params have no legacy space — intentionally absent.
            expect(paramTransforms["UnisonVoices"]).toBeUndefined();
            expect(paramTransforms["LFO2Rate"]).toBeUndefined();
        });

        it("golden values: representative inverses", () => {
            // BENDRANGE split (both halves share the math).
            expect(paramTransforms["PitchBendUp"].forward(0.6)).toBeCloseTo(12 / 48, 12);
            expect(paramTransforms["PitchBendUp"].forward(0.4)).toBeCloseTo(2 / 48, 12);
            expect(paramTransforms["PitchBendUp"].invert!(12 / 48)).toBe(1);
            expect(paramTransforms["PitchBendDown"].forward!(0.6)).toBeCloseTo(12 / 48, 12);
            expect(paramTransforms["PitchBendDown"].invert!(2 / 48)).toBe(0);
            // Polyphony.
            expect(paramTransforms["Polyphony"].forward(1)).toBeCloseTo(7.5 / 32, 12);
            expect(paramTransforms["Polyphony"].invert!(7.5 / 32)).toBeCloseTo(1, 12);
            // Transpose round-trips at the centered position.
            expect(paramTransforms["Transpose"].forward(0.5)).toBeCloseTo(0.75, 12);
            expect(paramTransforms["Transpose"].invert!(0.75)).toBeCloseTo(0.5, 12);
            // BOOL kinds.
            expect(paramTransforms["LFO1Wave1"].forward(1)).toBe(0);
            expect(paramTransforms["LFO1Wave1"].invert!(0)).toBe(1);
            expect(paramTransforms["LFO1ToOsc1Pitch"].forward(1)).toBe(0.5);
            expect(paramTransforms["LFO1ToOsc1Pitch"].invert!(0.5)).toBe(1);
            // NOTEPRIORITY uses STRICT >.
            expect(paramTransforms["NotePriority"].forward(0.5)).toBe(0.5);
            expect(paramTransforms["NotePriority"].forward(0.51)).toBe(0);
            expect(paramTransforms["NotePriority"].invert!(0)).toBe(1);
            // MUL.
            expect(paramTransforms["OscCrossmod"].forward(1)).toBeCloseTo(0.5, 12);
            expect(paramTransforms["OscCrossmod"].invert!(0.5)).toBeCloseTo(1, 12);
            // NOISEMIX bakes logsc(1,0,1,35) = 1.
            expect(paramTransforms["NoiseMix"].forward(1)).toBeCloseTo(1, 9);
            expect(paramTransforms["NoiseMix"].invert!(1)).toBeCloseTo(1, 9);
        });

        it("exact-inverse kinds round-trip across [0,1]", () => {
            const samples = [0.05, 0.2, 0.35, 0.5, 0.65, 0.8, 0.95];
            let checked = 0;
            for (const [name, t] of Object.entries(paramTransforms)) {
                const kind = kindByNewId.get(name);
                expect(kind, `${name} must map to a transform kind`).toBeDefined();
                if (!kind || !EXACT_ROUNDTRIP_KINDS.has(kind) || !t.invert) continue;
                for (const v of samples) {
                    const n = t.forward(v);
                    expect(n, `${name}.forward(${v}) stays in [0,1]`).toBeGreaterThanOrEqual(0);
                    expect(n, `${name}.forward(${v}) stays in [0,1]`).toBeLessThanOrEqual(1);
                    expect(t.invert(n), `${name} invert(forward(${v}))`).toBeCloseTo(v, 6);
                }
                checked++;
            }
            // IDENTITY(41) + MUL(4) + LOGSC_INVLOGSC(6) + PAN(8) rows... exact rows:
            // IDENTITY 39 with invert + MUL 4 + LOGSC 6 + PAN 8 = 57 primary names.
            expect(checked).toBeGreaterThanOrEqual(50);
        });

        it("LFO1Rate forward models the free-running path", () => {
            const t = paramTransforms["LFO1Rate"];
            // logsc(1,0,50,120) = 50 Hz; invLogsc(50,0,250,3775)
            //   = ln(3775*50/250 + 1) / ln(3776) ≈ 0.8047
            const expected = Math.log(3775 * 50 / 250 + 1) / Math.log(3776);
            expect(t.forward(1)).toBeCloseTo(expected, 12);
            expect(t.invert).toBeNull();
        });
    });
});
