/*
 * wasm/obxd/gxfx_defaults.h — GENERATED guitarix FX default tables.
 *
 * AUTO-GENERATED by tools/gen-gxfx-params.mjs from tools/gxfx-param-spec.json
 * — DO NOT EDIT BY HAND; regenerate with:
 *     node tools/gen-gxfx-params.mjs          (write)
 *     node tools/gen-gxfx-params.mjs --check  (freshness gate)
 *
 * FX_DEFAULTS[effect][p] — per-effect param defaults in ENGINE units
 * (ttl ranges, NOT 0..1). Rows in effect-id order 0..10 (wah..reverb),
 * param order = port order, padded to 48 entries per row with 0.0f.
 * FX_PARAM_COUNTS[effect] — live params per effect; the rest of each row
 * is padding.
 *
 * Consumed by wasm/obxd/gxfx_host.cpp: fx_set_slot copies a row into the
 * slot's param array on every slot assign, fx_default() reads single
 * entries for the bulk state surface.
 */
#ifndef GXFX_DEFAULTS_H
#define GXFX_DEFAULTS_H

static const float FX_DEFAULTS[11][48] = {
    /*  0: wah — 2 params + 46 pad */
    {
            0.0f,    0.5f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
    /*  1: overdrive — 1 params + 47 pad */
    {
            0.5f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
    /*  2: distortion — 3 params + 45 pad */
    {
           -2.0f,    0.5f,    0.5f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
    /*  3: compressor — 5 params + 43 pad */
    {
            2.0f,    3.0f,  -20.0f,    0.5f,  0.002f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
    /*  4: chorus — 4 params + 44 pad */
    {
            0.5f,   0.02f,   0.02f,    3.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
    /*  5: flanger — 6 params + 42 pad */
    {
            0.5f,    5.0f,    0.2f, -0.707f,  100.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
    /*  6: phaser — 3 params + 45 pad */
    {
           50.0f,    0.0f,    0.5f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
    /*  7: tremolo — 4 params + 44 pad */
    {
           50.0f,    0.0f,    0.5f,    5.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
    /*  8: delay — 7 params + 41 pad */
    {
            0.0f,  -10.0f, 1000.0f,  -10.0f, 1000.0f,    0.2f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
    /*  9: echo — 7 params + 41 pad */
    {
            0.0f,   30.0f,  100.0f,   30.0f,  100.0f,    0.2f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
    /* 10: reverb — 5 params + 43 pad */
    {
           50.0f,    0.2f,    0.5f,    0.2f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
            0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,    0.0f,
    },
};

static const int FX_PARAM_COUNTS[11] = { 2, 1, 3, 5, 4, 6, 3, 4, 7, 7, 5 };

#endif /* GXFX_DEFAULTS_H */
