/*
 * wasm/obxd/param_table.h — GENERATED parameter dispatch tables for the
 * OB-Xd (legacy) → OB-Xf parameter migration.
 *
 * AUTO-GENERATED by tools/gen-param-table.mjs from tools/param-spec.mjs
 * (the single source of truth — see tools/PARAM_SPEC.md). DO NOT EDIT
 * BY HAND; regenerate with:
 *     node tools/gen-param-table.mjs          (write)
 *     node tools/gen-param-table.mjs --check  (freshness gate)
 *
 * =========================================================================
 * INCLUDE CONTRACT
 * =========================================================================
 * This header includes NOTHING itself. It MUST be #include'd AFTER the
 * OB-Xf engine headers (engine/SynthEngine.h) — it references:
 *   - SynthEngine as a COMPLETE type (function pointers take SynthEngine&),
 *   - the constants MAX_VOICES and MAX_BEND_RANGE (32 / 48, already in
 *     scope from obxf_imported/configuration.h via the engine headers),
 *   - <cmath> for std::round / std::exp / std::log (already in scope in
 *     main_obxd.cpp; JUCE headers pull it in transitively).
 *
 * =========================================================================
 * TWO DISPATCH SPACES — one table pair per space
 * =========================================================================
 * (a) LEGACY path (knob UI, integer .fxp schema): legacy-space 0..1 values
 *     that MUST be transformed before the engine call. Use
 *     obxf_legacy_params[idx].apply_legacy (NULL for removed rows and the
 *     two special_inline rows — see below).
 * (b) NATIVE path (OB-Xf named-attribute .fxp schema, `Volume="0.5"`):
 *     native engine-space 0..1 values applied 1:1 with NO transform. Use
 *     obxf_param_name_find(name, nlen)->native_apply, or
 *     obxf_new_params[ordinal].apply_native for the 28 OB-Xf-only params.
 *
 * INVERT: obxf_legacy_params[idx].invert maps a native 0..1 value back to
 * the legacy 0..1 space — use it to write g_param_mirror when a native
 * .fxp names a legacy-mapped param (fixes the knob-jump bug). NULL for
 * removed rows, the two special_inline rows, and every NEW param.
 *
 * SPECIAL INLINE: LFOFREQ (legacy 17, "LFO1Rate") and LFO_SYNC (legacy 72,
 * "LFO1TempoSync") are special_inline=1 with apply_legacy == NULL. Their
 * legacy handling reads/writes per-instance mirror state and stays inline
 * in main_obxd.cpp — check `special_inline` before falling through to any
 * generic table call. Their NATIVE path (native_apply) is still a plain
 * 1:1 call and is safe to dispatch from the name index.
 *
 * BENDRANGE (legacy 6) is ONE row whose apply_legacy writes BOTH
 * processBendUpRange and processBendDownRange with the same transformed
 * value (secondary_name = "PitchBendDown"). The name index carries both
 * halves as separate entries.
 *
 * Drum classification (PCM instance 9): drum_class routes legacy params
 * (none > smoother > global > voice precedence) and drum_restore_skip is
 * the INDEPENDENT worklet DRUM_STRUCTURAL_SKIP flag — neither derives
 * from the other (see tools/PARAM_SPEC.md).
 * =========================================================================
 */

#ifndef OBXF_PARAM_TABLE_H
#define OBXF_PARAM_TABLE_H

#define OBXF_PT_LEGACY_COUNT 80    /* legacy indices 0..79 (ParamsEnum.h order) */
#define OBXF_PT_NEW_COUNT 28       /* OB-Xf-only params, canonical ordinals 0..27 */
#define OBXF_PT_NAME_INDEX_COUNT 104  /* one entry per streaming name, sorted for bsearch */
#define OBXF_PT_NEW_PARAM_BASE 200    /* UI sentinel: idx = 200 + canonical ordinal */

// --- Drum classification (PCM instance 9) --------------------------------
typedef enum {
    DRUM_NONE = 0,      /* removed / no-op row — nothing to route */
    DRUM_GLOBAL = 1,   /* routes live to instance 9; never per voice */
    DRUM_SMOOTHER = 2, /* applied directly onto the triggered voice */
    DRUM_VOICE = 3,    /* applied per triggered voice via apply_legacy */
} obxf_drum_class_t;

typedef void (*obxf_apply_fn)(SynthEngine&, float); /* engine-space apply */
typedef float (*obxf_invert_fn)(float);             /* native→legacy 0..1 */

// --- Legacy row (one per ParamsEnum.h index 0..79) ----------------------
typedef struct obxf_legacy_param_t {
    int legacy_index;          /* 0..79 == index into obxf_legacy_params */
    const char* legacy_name;   /* ParamsEnum.h identifier (docs) */
    const char* legacy_method; /* OLD OB-Xd method name (docs) */
    const char* name;          /* primary OB-Xf streaming name; "" = removed/no-op */
    const char* secondary_name;/* split-half streaming name (BENDRANGE only); "" */
    obxf_apply_fn apply_legacy;/* forward (legacy→engine) call; NULL for removed
                                  rows AND the two special_inline rows */
    obxf_invert_fn invert;     /* native→legacy (mirror write); NULL where the
                                  spec says null (removed + special_inline) */
    int special_inline;       /* 1 for LFOFREQ(17)/LFO_SYNC(72): C handles them
                                  inline; do NOT call any fn ptr — detect this */
    obxf_drum_class_t drum_class;
    int drum_restore_skip;    /* worklet DRUM_STRUCTURAL_SKIP (orthogonal) */
    const char* notes;
} obxf_legacy_param_t;

// --- NEW param row (one per canonical ordinal 0..27) --------------------
typedef struct obxf_new_param_t {
    const char* name;           /* OB-Xf streaming name (unique, no legacy row) */
    obxf_apply_fn apply_native; /* DIRECT 1:1 processX call (native space) */
    obxf_drum_class_t drum_class; /* DRUM_GLOBAL (verified synth-globals) or DRUM_VOICE (spec) */
    const char* notes;
} obxf_new_param_t;

// --- Name-index entry (streaming-name → both dispatch spaces) ----------
typedef struct obxf_param_name_entry_t {
    const char* name;           /* OB-Xf streaming name (sorted, unique) */
    obxf_apply_fn native_apply; /* DIRECT 1:1 engine call for this name */
    int legacy_index;           /* -1 for NEW params */
    int new_ordinal;            /* canonical ordinal; -1 for legacy-mapped names */
    obxf_invert_fn invert;      /* legacy row's invert; NULL for NEW names and
                                   for legacy rows whose spec invert is null */
} obxf_param_name_entry_t;

// =========================================================================
// Math helpers — verbatim from ObxdImporter.cpp / main_obxd.cpp. Local
// clamps keep this header free of any juce:: dependency.
// =========================================================================
static inline float obxf_pt_clampf(float v, float lo, float hi) {
    return v < lo ? lo : (v > hi ? hi : v);
}
static inline int obxf_pt_clampi(int v, int lo, int hi) {
    return v < lo ? lo : (v > hi ? hi : v);
}

// OB-Xd logsc: ((exp(p*ln(rolloff+1)) - 1) / rolloff) * (hi - lo) + lo
static inline float obxf_pt_xd_logsc(float p, float lo, float hi, float rolloff) {
    return ((std::exp(p * std::log(rolloff + 1.0f)) - 1.0f) / rolloff) * (hi - lo) + lo;
}
// OB-Xd linsc (needed by the invert direction of curve 'lin' rows)
static inline float obxf_pt_xd_linsc(float p, float lo, float hi) {
    return lo + p * (hi - lo);
}
static inline float obxf_pt_xd_inv_linsc(float y, float lo, float hi) {
    if (hi == lo) return 0.0f;
    return obxf_pt_clampf((y - lo) / (hi - lo), 0.0f, 1.0f);
}
static inline float obxf_pt_xd_inv_logsc(float y, float lo, float hi, float rolloff) {
    if (hi == lo) return 0.0f;
    const float t = rolloff * (y - lo) / (hi - lo) + 1.0f;
    if (t <= 0.0f) return 0.0f;
    return obxf_pt_clampf(std::log(t) / std::log(rolloff + 1.0f), 0.0f, 1.0f);
}

// OB-Xd LFO wave bool → continuous blend; importer emits only 0 or 0.5.
static inline float obxf_pt_lfo_bool_to_blend(float v) { return v >= 0.5f ? 0.0f : 0.5f; }
// OB-Xd LFO destination bool → tri-state {Off, On, Inv} = 0 / 0.5 / 1.
static inline float obxf_pt_lfo_bool_to_tristate(float v) { return v >= 0.5f ? 0.5f : 0.0f; }

// =========================================================================
// Shared INVERT helpers (canonical representative inverses — the choice is
// documented in tools/PARAM_SPEC.md §Invert semantics). Kinds whose math
// carries per-row constants (MUL factor, LOGSC_INVLOGSC sets) get one
// generated function per row below instead.
// =========================================================================
static inline float obxf_pt_invert_identity(float v) { return v; }
// SPLIT_BENDRANGE: range = round(n*MAX_BEND_RANGE); any range >= 8 st is the wide knob
static inline float obxf_pt_invert_split_bendrange(float v) {
    const int range = (int)std::round(v * (float)MAX_BEND_RANGE);
    return range > 7 ? 1.0f : 0.0f;
}
// VOICE_COUNT: representative bucket midpoint
static inline float obxf_pt_invert_voice_count(float v) {
    const int voices = obxf_pt_clampi((int)std::round(v * (float)MAX_VOICES), 1, 8);
    return (float)(voices - 1) / 7.0f;
}
static inline float obxf_pt_invert_octave_transpose(float v) {
    const int transpose = (int)std::round(v * 4.0f);
    return obxf_pt_clampf((float)(transpose - 1) / 4.0f, 0.0f, 1.0f);
}
// BOOL_BLEND: native 0 → legacy 1, native 0.5 → legacy 0 (0.25 midpoint)
static inline float obxf_pt_invert_bool_blend(float v) { return v < 0.25f ? 1.0f : 0.0f; }
// BOOL_TRISTATE: the Inv state (n=1) shows as "on" in the legacy UI
static inline float obxf_pt_invert_bool_tristate(float v) { return v >= 0.25f ? 1.0f : 0.0f; }
// NOTEPRIORITY: native 0 = Last → 1, native 0.5 = Low → 0; High shows as Low
static inline float obxf_pt_invert_notepriority(float v) { return v > 0.25f ? 0.0f : 1.0f; }

// =========================================================================
// Forward apply functions — LEGACY space (applyLegacy). One per non-removed,
// non-specialInline legacy row, in legacy-index order.
// =========================================================================
static inline void obxf_apply_volume(SynthEngine& s, float v) {
    s.processVolume(v);
}

static inline void obxf_apply_voice_count(SynthEngine& s, float v) {
    const int xdVoices = obxf_pt_clampi((int)std::round(v * 7.0f) + 1, 1, 8);
    s.processPolyphony(((float)(xdVoices - 1) + 0.5f) / (float)MAX_VOICES);
}

static inline void obxf_apply_tune(SynthEngine& s, float v) {
    s.processTune(v);
}

static inline void obxf_apply_octave(SynthEngine& s, float v) {
    const int transpose = obxf_pt_clampi((int)std::round(v * 4.0f) + 1, 0, 4);
    s.processTranspose((float)transpose * 0.25f);
}

static inline void obxf_apply_bendrange(SynthEngine& s, float v) {
    const int range = (v > 0.5f) ? 12 : 2;
    const float n = (float)range / (float)MAX_BEND_RANGE;
    s.processBendUpRange(n); /* primary: PitchBendUp */
    s.processBendDownRange(n); /* secondary: PitchBendDown (same value) */
}

static inline void obxf_apply_bendosc2(SynthEngine& s, float v) {
    s.processBendOsc2Only(v);
}

static inline void obxf_apply_legatomode(SynthEngine& s, float v) {
    s.processEnvLegatoMode(v);
}

static inline void obxf_apply_bendlforate(SynthEngine& s, float v) {
    float xdv = obxf_pt_xd_logsc(v, 3.0f, 10.0f, 19.0f);
    s.processVibratoLFORate(obxf_pt_xd_inv_linsc(xdv, 2.0f, 12.0f));
}

static inline void obxf_apply_vfltenv(SynthEngine& s, float v) {
    s.processVelToFilterEnv(v);
}

static inline void obxf_apply_vampenv(SynthEngine& s, float v) {
    s.processVelToAmpEnv(v);
}

static inline void obxf_apply_asplayedallocation(SynthEngine& s, float v) {
    s.processNotePriority(v > 0.5f ? 0.0f : 0.5f); /* STRICT >, unlike BOOL_* */
}

static inline void obxf_apply_portamento(SynthEngine& s, float v) {
    s.processPortamento(v);
}

static inline void obxf_apply_unison(SynthEngine& s, float v) {
    s.processUnison(v);
}

static inline void obxf_apply_udet(SynthEngine& s, float v) {
    float xdv = obxf_pt_xd_logsc(v, 0.001f, 0.9f, 19.0f);
    s.processUnisonDetune(obxf_pt_xd_inv_logsc(xdv, 0.001f, 1.0f, 19.0f));
}

static inline void obxf_apply_osc2_det(SynthEngine& s, float v) {
    s.processOsc2Detune(v);
}

static inline void obxf_apply_lfosinwave(SynthEngine& s, float v) {
    s.processLFO1Wave1(obxf_pt_lfo_bool_to_blend(v));
}

static inline void obxf_apply_lfosquarewave(SynthEngine& s, float v) {
    s.processLFO1Wave2(obxf_pt_lfo_bool_to_blend(v));
}

static inline void obxf_apply_lfoshwave(SynthEngine& s, float v) {
    s.processLFO1Wave3(obxf_pt_lfo_bool_to_blend(v));
}

static inline void obxf_apply_lfo1amt(SynthEngine& s, float v) {
    s.processLFO1ModAmount1(v);
}

static inline void obxf_apply_lfo2amt(SynthEngine& s, float v) {
    s.processLFO1ModAmount2(v);
}

static inline void obxf_apply_lfoosc1(SynthEngine& s, float v) {
    s.processLFO1ToOsc1Pitch(obxf_pt_lfo_bool_to_tristate(v));
}

static inline void obxf_apply_lfoosc2(SynthEngine& s, float v) {
    s.processLFO1ToOsc2Pitch(obxf_pt_lfo_bool_to_tristate(v));
}

static inline void obxf_apply_lfofilter(SynthEngine& s, float v) {
    s.processLFO1ToFilterCutoff(obxf_pt_lfo_bool_to_tristate(v));
}

static inline void obxf_apply_lfopw1(SynthEngine& s, float v) {
    s.processLFO1ToOsc1PW(obxf_pt_lfo_bool_to_tristate(v));
}

static inline void obxf_apply_lfopw2(SynthEngine& s, float v) {
    s.processLFO1ToOsc2PW(obxf_pt_lfo_bool_to_tristate(v));
}

static inline void obxf_apply_osc2hs(SynthEngine& s, float v) {
    s.processOscSync(v);
}

static inline void obxf_apply_xmod(SynthEngine& s, float v) {
    s.processCrossmod(v * 0.5f);
}

static inline void obxf_apply_osc1p(SynthEngine& s, float v) {
    s.processOsc1Pitch(v);
}

static inline void obxf_apply_osc2p(SynthEngine& s, float v) {
    s.processOsc2Pitch(v);
}

static inline void obxf_apply_osc1saw(SynthEngine& s, float v) {
    s.processOsc1Saw(v);
}

static inline void obxf_apply_osc1pul(SynthEngine& s, float v) {
    s.processOsc1Pulse(v);
}

static inline void obxf_apply_osc2saw(SynthEngine& s, float v) {
    s.processOsc2Saw(v);
}

static inline void obxf_apply_osc2pul(SynthEngine& s, float v) {
    s.processOsc2Pulse(v);
}

static inline void obxf_apply_pw(SynthEngine& s, float v) {
    s.processOscPW(v);
}

static inline void obxf_apply_brightness(SynthEngine& s, float v) {
    s.processOscBrightness(v);
}

static inline void obxf_apply_envpitch(SynthEngine& s, float v) {
    s.processEnvToPitchAmount(v * 0.9f);
}

static inline void obxf_apply_osc1mix(SynthEngine& s, float v) {
    s.processOsc1Volume(v);
}

static inline void obxf_apply_osc2mix(SynthEngine& s, float v) {
    s.processOsc2Volume(v);
}

static inline void obxf_apply_noisemix(SynthEngine& s, float v) {
    float xdv = obxf_pt_xd_logsc(v, 0.0f, 1.0f, 35.0f);
    s.processNoiseVolume(xdv);
}

static inline void obxf_apply_flt_kf(SynthEngine& s, float v) {
    s.processFilterKeyTrack(v);
}

static inline void obxf_apply_cutoff(SynthEngine& s, float v) {
    s.processFilterCutoff(v);
}

static inline void obxf_apply_resonance(SynthEngine& s, float v) {
    s.processFilterResonance(v);
}

static inline void obxf_apply_multimode(SynthEngine& s, float v) {
    s.processFilterMode(v);
}

static inline void obxf_apply_filter_warm(SynthEngine& s, float v) {
    s.processHQMode(v);
}

static inline void obxf_apply_bandpass(SynthEngine& s, float v) {
    s.processFilter2PoleBPBlend(v);
}

static inline void obxf_apply_fourpole(SynthEngine& s, float v) {
    s.processFilter4PoleMode(v);
}

static inline void obxf_apply_envelope_amt(SynthEngine& s, float v) {
    s.processFilterEnvAmount(v);
}

static inline void obxf_apply_latk(SynthEngine& s, float v) {
    float xdv = obxf_pt_xd_logsc(v, 4.0f, 60000.0f, 900.0f);
    xdv /= 3.0f; /* attack-time compensation */
    s.processAmpEnvAttack(obxf_pt_xd_inv_logsc(xdv, 4.0f, 60000.0f, 900.0f));
}

static inline void obxf_apply_ldec(SynthEngine& s, float v) {
    s.processAmpEnvDecay(v);
}

static inline void obxf_apply_lsus(SynthEngine& s, float v) {
    s.processAmpEnvSustain(v);
}

static inline void obxf_apply_lrel(SynthEngine& s, float v) {
    s.processAmpEnvRelease(v);
}

static inline void obxf_apply_fatk(SynthEngine& s, float v) {
    float xdv = obxf_pt_xd_logsc(v, 1.0f, 60000.0f, 900.0f);
    xdv /= 3.0f; /* attack-time compensation */
    s.processFilterEnvAttack(obxf_pt_xd_inv_logsc(xdv, 1.0f, 60000.0f, 900.0f));
}

static inline void obxf_apply_fdec(SynthEngine& s, float v) {
    s.processFilterEnvDecay(v);
}

static inline void obxf_apply_fsus(SynthEngine& s, float v) {
    s.processFilterEnvSustain(v);
}

static inline void obxf_apply_frel(SynthEngine& s, float v) {
    s.processFilterEnvRelease(v);
}

static inline void obxf_apply_envder(SynthEngine& s, float v) {
    s.processEnvelopeSlop(v);
}

static inline void obxf_apply_filterder(SynthEngine& s, float v) {
    s.processFilterSlop(v);
}

static inline void obxf_apply_portader(SynthEngine& s, float v) {
    s.processPortamentoSlop(v);
}

static inline void obxf_apply_pan1(SynthEngine& s, float v) {
    s.processPan(v, 1);
}

static inline void obxf_apply_pan2(SynthEngine& s, float v) {
    s.processPan(v, 2);
}

static inline void obxf_apply_pan3(SynthEngine& s, float v) {
    s.processPan(v, 3);
}

static inline void obxf_apply_pan4(SynthEngine& s, float v) {
    s.processPan(v, 4);
}

static inline void obxf_apply_pan5(SynthEngine& s, float v) {
    s.processPan(v, 5);
}

static inline void obxf_apply_pan6(SynthEngine& s, float v) {
    s.processPan(v, 6);
}

static inline void obxf_apply_pan7(SynthEngine& s, float v) {
    s.processPan(v, 7);
}

static inline void obxf_apply_pan8(SynthEngine& s, float v) {
    s.processPan(v, 8);
}

static inline void obxf_apply_pw_env(SynthEngine& s, float v) {
    s.processEnvToPWAmount(v * 0.8052631579371191f);
}

static inline void obxf_apply_pw_env_both(SynthEngine& s, float v) {
    s.processEnvToPWBothOscs(v);
}

static inline void obxf_apply_env_pitch_both(SynthEngine& s, float v) {
    s.processPitchBothOscs(v);
}

static inline void obxf_apply_fenv_invert(SynthEngine& s, float v) {
    s.processFilterEnvInvert(v);
}

static inline void obxf_apply_pw_osc2_ofs(SynthEngine& s, float v) {
    s.processOsc2PWOffset(v * 0.7894736842105263f);
}

static inline void obxf_apply_level_dif(SynthEngine& s, float v) {
    s.processLevelSlop(v);
}

static inline void obxf_apply_self_osc_push(SynthEngine& s, float v) {
    s.processFilter2PolePush(v);
}

// =========================================================================
// Per-row INVERT functions (native→legacy) for kinds whose constants differ
// per row: MUL (reciprocal factor) and LOGSC_INVLOGSC (map through xf, then
// xdInvLogsc onto the xd set). Exact inverses — round-trips cleanly.
// =========================================================================
static inline float obxf_invert_bendlforate(float v) {
    float xdv = obxf_pt_xd_linsc(v, 2.0f, 12.0f);
    return obxf_pt_xd_inv_logsc(xdv, 3.0f, 10.0f, 19.0f);
}

static inline float obxf_invert_udet(float v) {
    float xdv = obxf_pt_xd_logsc(v, 0.001f, 1.0f, 19.0f);
    return obxf_pt_xd_inv_logsc(xdv, 0.001f, 0.9f, 19.0f);
}

static inline float obxf_invert_xmod(float v) {
    return v * 2.0f;
}

static inline float obxf_invert_envpitch(float v) {
    return v * 1.1111111111111112f;
}

static inline float obxf_invert_noisemix(float v) {
    float xdv = v;
    return obxf_pt_xd_inv_logsc(xdv, 0.0f, 1.0f, 35.0f);
}

static inline float obxf_invert_latk(float v) {
    float xdv = obxf_pt_xd_logsc(v, 4.0f, 60000.0f, 900.0f);
    xdv *= 3.0f;
    return obxf_pt_xd_inv_logsc(xdv, 4.0f, 60000.0f, 900.0f);
}

static inline float obxf_invert_fatk(float v) {
    float xdv = obxf_pt_xd_logsc(v, 1.0f, 60000.0f, 900.0f);
    xdv *= 3.0f;
    return obxf_pt_xd_inv_logsc(xdv, 1.0f, 60000.0f, 900.0f);
}

static inline float obxf_invert_pw_env(float v) {
    return v * 1.2418300652941177f;
}

static inline float obxf_invert_pw_osc2_ofs(float v) {
    return v * 1.2666666666666666f;
}

// =========================================================================
// Native apply functions — NATIVE space (1:1, NO transform). One per
// streaming name (the name-index targets), sorted by name.
// BENDRANGE halves call separate range methods; PAN names pass voiceIndex.
// =========================================================================
static inline void obxf_native_AmpEnvAttack(SynthEngine& s, float v) {
    s.processAmpEnvAttack(v);
}

static inline void obxf_native_AmpEnvAttackCurve(SynthEngine& s, float v) {
    s.processAmpEnvAttackCurve(v);
}

static inline void obxf_native_AmpEnvDecay(SynthEngine& s, float v) {
    s.processAmpEnvDecay(v);
}

static inline void obxf_native_AmpEnvRelease(SynthEngine& s, float v) {
    s.processAmpEnvRelease(v);
}

static inline void obxf_native_AmpEnvSustain(SynthEngine& s, float v) {
    s.processAmpEnvSustain(v);
}

static inline void obxf_native_BendOsc2Only(SynthEngine& s, float v) {
    s.processBendOsc2Only(v);
}

static inline void obxf_native_EnvLegatoMode(SynthEngine& s, float v) {
    s.processEnvLegatoMode(v);
}

static inline void obxf_native_EnvToPWAmount(SynthEngine& s, float v) {
    s.processEnvToPWAmount(v);
}

static inline void obxf_native_EnvToPWBothOscs(SynthEngine& s, float v) {
    s.processEnvToPWBothOscs(v);
}

static inline void obxf_native_EnvToPWInvert(SynthEngine& s, float v) {
    s.processEnvToPWInvert(v);
}

static inline void obxf_native_EnvToPitchAmount(SynthEngine& s, float v) {
    s.processEnvToPitchAmount(v);
}

static inline void obxf_native_EnvToPitchBothOscs(SynthEngine& s, float v) {
    s.processPitchBothOscs(v);
}

static inline void obxf_native_EnvToPitchInvert(SynthEngine& s, float v) {
    s.processEnvToPitchInvert(v);
}

static inline void obxf_native_EnvelopeSlop(SynthEngine& s, float v) {
    s.processEnvelopeSlop(v);
}

static inline void obxf_native_Filter2PoleBPBlend(SynthEngine& s, float v) {
    s.processFilter2PoleBPBlend(v);
}

static inline void obxf_native_Filter2PolePush(SynthEngine& s, float v) {
    s.processFilter2PolePush(v);
}

static inline void obxf_native_Filter4PoleMode(SynthEngine& s, float v) {
    s.processFilter4PoleMode(v);
}

static inline void obxf_native_Filter4PoleXpander(SynthEngine& s, float v) {
    s.processFilter4PoleXpander(v);
}

static inline void obxf_native_FilterCutoff(SynthEngine& s, float v) {
    s.processFilterCutoff(v);
}

static inline void obxf_native_FilterEnvAmount(SynthEngine& s, float v) {
    s.processFilterEnvAmount(v);
}

static inline void obxf_native_FilterEnvAttack(SynthEngine& s, float v) {
    s.processFilterEnvAttack(v);
}

static inline void obxf_native_FilterEnvAttackCurve(SynthEngine& s, float v) {
    s.processFilterEnvAttackCurve(v);
}

static inline void obxf_native_FilterEnvDecay(SynthEngine& s, float v) {
    s.processFilterEnvDecay(v);
}

static inline void obxf_native_FilterEnvInvert(SynthEngine& s, float v) {
    s.processFilterEnvInvert(v);
}

static inline void obxf_native_FilterEnvRelease(SynthEngine& s, float v) {
    s.processFilterEnvRelease(v);
}

static inline void obxf_native_FilterEnvSustain(SynthEngine& s, float v) {
    s.processFilterEnvSustain(v);
}

static inline void obxf_native_FilterKeyFollow(SynthEngine& s, float v) {
    s.processFilterKeyTrack(v);
}

static inline void obxf_native_FilterMode(SynthEngine& s, float v) {
    s.processFilterMode(v);
}

static inline void obxf_native_FilterResonance(SynthEngine& s, float v) {
    s.processFilterResonance(v);
}

static inline void obxf_native_FilterSlop(SynthEngine& s, float v) {
    s.processFilterSlop(v);
}

static inline void obxf_native_FilterXpanderMode(SynthEngine& s, float v) {
    s.processFilterXpanderMode(v);
}

static inline void obxf_native_HQMode(SynthEngine& s, float v) {
    s.processHQMode(v);
}

static inline void obxf_native_LFO1ModAmount1(SynthEngine& s, float v) {
    s.processLFO1ModAmount1(v);
}

static inline void obxf_native_LFO1ModAmount2(SynthEngine& s, float v) {
    s.processLFO1ModAmount2(v);
}

static inline void obxf_native_LFO1PW(SynthEngine& s, float v) {
    s.processLFO1PW(v);
}

static inline void obxf_native_LFO1Rate(SynthEngine& s, float v) {
    s.processLFO1Rate(v);
}

static inline void obxf_native_LFO1TempoSync(SynthEngine& s, float v) {
    s.processLFO1Sync(v);
}

static inline void obxf_native_LFO1ToFilterCutoff(SynthEngine& s, float v) {
    s.processLFO1ToFilterCutoff(v);
}

static inline void obxf_native_LFO1ToOsc1PW(SynthEngine& s, float v) {
    s.processLFO1ToOsc1PW(v);
}

static inline void obxf_native_LFO1ToOsc1Pitch(SynthEngine& s, float v) {
    s.processLFO1ToOsc1Pitch(v);
}

static inline void obxf_native_LFO1ToOsc2PW(SynthEngine& s, float v) {
    s.processLFO1ToOsc2PW(v);
}

static inline void obxf_native_LFO1ToOsc2Pitch(SynthEngine& s, float v) {
    s.processLFO1ToOsc2Pitch(v);
}

static inline void obxf_native_LFO1ToVolume(SynthEngine& s, float v) {
    s.processLFO1ToVolume(v);
}

static inline void obxf_native_LFO1Wave1(SynthEngine& s, float v) {
    s.processLFO1Wave1(v);
}

static inline void obxf_native_LFO1Wave2(SynthEngine& s, float v) {
    s.processLFO1Wave2(v);
}

static inline void obxf_native_LFO1Wave3(SynthEngine& s, float v) {
    s.processLFO1Wave3(v);
}

static inline void obxf_native_LFO2ModAmount1(SynthEngine& s, float v) {
    s.processLFO2ModAmount1(v);
}

static inline void obxf_native_LFO2ModAmount2(SynthEngine& s, float v) {
    s.processLFO2ModAmount2(v);
}

static inline void obxf_native_LFO2PW(SynthEngine& s, float v) {
    s.processLFO2PW(v);
}

static inline void obxf_native_LFO2Rate(SynthEngine& s, float v) {
    s.processLFO2Rate(v);
}

static inline void obxf_native_LFO2TempoSync(SynthEngine& s, float v) {
    s.processLFO2Sync(v);
}

static inline void obxf_native_LFO2ToFilterCutoff(SynthEngine& s, float v) {
    s.processLFO2ToFilterCutoff(v);
}

static inline void obxf_native_LFO2ToOsc1PW(SynthEngine& s, float v) {
    s.processLFO2ToOsc1PW(v);
}

static inline void obxf_native_LFO2ToOsc1Pitch(SynthEngine& s, float v) {
    s.processLFO2ToOsc1Pitch(v);
}

static inline void obxf_native_LFO2ToOsc2PW(SynthEngine& s, float v) {
    s.processLFO2ToOsc2PW(v);
}

static inline void obxf_native_LFO2ToOsc2Pitch(SynthEngine& s, float v) {
    s.processLFO2ToOsc2Pitch(v);
}

static inline void obxf_native_LFO2ToVolume(SynthEngine& s, float v) {
    s.processLFO2ToVolume(v);
}

static inline void obxf_native_LFO2Wave1(SynthEngine& s, float v) {
    s.processLFO2Wave1(v);
}

static inline void obxf_native_LFO2Wave2(SynthEngine& s, float v) {
    s.processLFO2Wave2(v);
}

static inline void obxf_native_LFO2Wave3(SynthEngine& s, float v) {
    s.processLFO2Wave3(v);
}

static inline void obxf_native_LevelSlop(SynthEngine& s, float v) {
    s.processLevelSlop(v);
}

static inline void obxf_native_NoiseColor(SynthEngine& s, float v) {
    s.processNoiseColor(v);
}

static inline void obxf_native_NoiseMix(SynthEngine& s, float v) {
    s.processNoiseVolume(v);
}

static inline void obxf_native_NotePriority(SynthEngine& s, float v) {
    s.processNotePriority(v);
}

static inline void obxf_native_Osc1Mix(SynthEngine& s, float v) {
    s.processOsc1Volume(v);
}

static inline void obxf_native_Osc1Pitch(SynthEngine& s, float v) {
    s.processOsc1Pitch(v);
}

static inline void obxf_native_Osc1PulseWave(SynthEngine& s, float v) {
    s.processOsc1Pulse(v);
}

static inline void obxf_native_Osc1SawWave(SynthEngine& s, float v) {
    s.processOsc1Saw(v);
}

static inline void obxf_native_Osc2Detune(SynthEngine& s, float v) {
    s.processOsc2Detune(v);
}

static inline void obxf_native_Osc2Keytrack(SynthEngine& s, float v) {
    s.processOsc2Keytrack(v);
}

static inline void obxf_native_Osc2Mix(SynthEngine& s, float v) {
    s.processOsc2Volume(v);
}

static inline void obxf_native_Osc2PWOffset(SynthEngine& s, float v) {
    s.processOsc2PWOffset(v);
}

static inline void obxf_native_Osc2Pitch(SynthEngine& s, float v) {
    s.processOsc2Pitch(v);
}

static inline void obxf_native_Osc2PulseWave(SynthEngine& s, float v) {
    s.processOsc2Pulse(v);
}

static inline void obxf_native_Osc2SawWave(SynthEngine& s, float v) {
    s.processOsc2Saw(v);
}

static inline void obxf_native_OscBrightness(SynthEngine& s, float v) {
    s.processOscBrightness(v);
}

static inline void obxf_native_OscCrossmod(SynthEngine& s, float v) {
    s.processCrossmod(v);
}

static inline void obxf_native_OscPW(SynthEngine& s, float v) {
    s.processOscPW(v);
}

static inline void obxf_native_OscSync(SynthEngine& s, float v) {
    s.processOscSync(v);
}

static inline void obxf_native_PanVoice1(SynthEngine& s, float v) {
    s.processPan(v, 1);
}

static inline void obxf_native_PanVoice2(SynthEngine& s, float v) {
    s.processPan(v, 2);
}

static inline void obxf_native_PanVoice3(SynthEngine& s, float v) {
    s.processPan(v, 3);
}

static inline void obxf_native_PanVoice4(SynthEngine& s, float v) {
    s.processPan(v, 4);
}

static inline void obxf_native_PanVoice5(SynthEngine& s, float v) {
    s.processPan(v, 5);
}

static inline void obxf_native_PanVoice6(SynthEngine& s, float v) {
    s.processPan(v, 6);
}

static inline void obxf_native_PanVoice7(SynthEngine& s, float v) {
    s.processPan(v, 7);
}

static inline void obxf_native_PanVoice8(SynthEngine& s, float v) {
    s.processPan(v, 8);
}

static inline void obxf_native_PitchBendDown(SynthEngine& s, float v) {
    s.processBendDownRange(v);
}

static inline void obxf_native_PitchBendUp(SynthEngine& s, float v) {
    s.processBendUpRange(v);
}

static inline void obxf_native_Polyphony(SynthEngine& s, float v) {
    s.processPolyphony(v);
}

static inline void obxf_native_Portamento(SynthEngine& s, float v) {
    s.processPortamento(v);
}

static inline void obxf_native_PortamentoSlop(SynthEngine& s, float v) {
    s.processPortamentoSlop(v);
}

static inline void obxf_native_RingModMix(SynthEngine& s, float v) {
    s.processRingModVolume(v);
}

static inline void obxf_native_Transpose(SynthEngine& s, float v) {
    s.processTranspose(v);
}

static inline void obxf_native_Tune(SynthEngine& s, float v) {
    s.processTune(v);
}

static inline void obxf_native_Unison(SynthEngine& s, float v) {
    s.processUnison(v);
}

static inline void obxf_native_UnisonDetune(SynthEngine& s, float v) {
    s.processUnisonDetune(v);
}

static inline void obxf_native_UnisonVoices(SynthEngine& s, float v) {
    s.processUnisonVoices(v);
}

static inline void obxf_native_VelToAmpEnv(SynthEngine& s, float v) {
    s.processVelToAmpEnv(v);
}

static inline void obxf_native_VelToFilterEnv(SynthEngine& s, float v) {
    s.processVelToFilterEnv(v);
}

static inline void obxf_native_VibratoRate(SynthEngine& s, float v) {
    s.processVibratoLFORate(v);
}

static inline void obxf_native_VibratoWave(SynthEngine& s, float v) {
    s.processVibratoLFOWave(v);
}

static inline void obxf_native_VoiceReassign(SynthEngine& s, float v) {
    s.processVoiceReassign(v);
}

static inline void obxf_native_Volume(SynthEngine& s, float v) {
    s.processVolume(v);
}

// =========================================================================
// Legacy table — exactly 80 rows, indexed by legacy index.
// =========================================================================
static const obxf_legacy_param_t obxf_legacy_params[OBXF_PT_LEGACY_COUNT] = {
    /*  0 */ { 0, "UNDEFINED", "", "", "", NULL, NULL, 0, DRUM_NONE, 0, "Sentinel / no-op. C is_global_drum_param() also lists it (harmless either way)." },
    /*  1 */ { 1, "MIDILEARN", "(UI-only)", "", "", NULL, NULL, 0, DRUM_NONE, 0, "REMOVED: UI-only, no engine action, no OB-Xf equivalent. C is_global_drum_param() also lists it (no-op either way)." },
    /*  2 */ { 2, "VOLUME", "processVolume", "Volume", "", obxf_apply_volume, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "1:1; both engines linsc(v,0,0.30) internally. Sets synth-global volume." },
    /*  3 */ { 3, "VOICE_COUNT", "setVoiceCount", "Polyphony", "", obxf_apply_voice_count, obxf_pt_invert_voice_count, 0, DRUM_GLOBAL, 1, "RESCALE: old 1..8 voices → new polyphony midpoint (voices-1+0.5)/32. Invert (representative): voices=clamp(round(n*32),1,8) → legacy=(voices-1)/7. drumRestoreSkip: initDrumMode owns drum polyphony." },
    /*  4 */ { 4, "TUNE", "processTune", "Tune", "", obxf_apply_tune, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "1:1; both engines v*2-1 internally." },
    /*  5 */ { 5, "OCTAVE", "processOctave", "Transpose", "", obxf_apply_octave, obxf_pt_invert_octave_transpose, 0, DRUM_GLOBAL, 0, "SEMANTIC SHIFT: old (round(v*4)-2)*12 st; new round((v*2-1)*24) st. Importer: transpose=clamp(round(v*4)+1,0..4)*0.25. Invert (representative): transpose=round(n*4) → legacy=clamp((transpose-1)/4,0,1)." },
    /*  6 */ { 6, "BENDRANGE", "procPitchWheelAmount", "PitchBendUp", "PitchBendDown", obxf_apply_bendrange, obxf_pt_invert_split_bendrange, 0, DRUM_GLOBAL, 0, "SPLIT — ONE spec row covering BOTH halves: n=(v>0.5?12:2)/48 written to processBendUpRange AND processBendDownRange (transform.secondaryNewId=PitchBendDown, secondaryMethod=processBendDownRange) with the SAME value. Legacy rows total 80, not 81. Invert (representative): range=round(n*48) → legacy = range>7 ? 1 : 0." },
    /*  7 */ { 7, "BENDOSC2", "procPitchWheelOsc2Only", "BendOsc2Only", "", obxf_apply_bendosc2, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "1:1; >=0.5 threshold inside both engines." },
    /*  8 */ { 8, "LEGATOMODE", "processLegatoMode", "EnvLegatoMode", "", obxf_apply_legatomode, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "Importer copies 1:1 (quantization happens in the engine). Same 4 modes (Both/Filter/Amp/Retrigger); bucket boundaries differ at v=0.5." },
    /*  9 */ { 9, "BENDLFORATE", "procModWheelFrequency", "VibratoRate", "", obxf_apply_bendlforate, obxf_invert_bendlforate, 0, DRUM_GLOBAL, 0, "RESCALE+RENAME: hzXd=logsc(v,3,10); native=invLinsc(hzXd,2,12). xf curve is LIN, not log. Invert (exact): hz=linsc(n,2,12) → legacy=invLogsc(hz,3,10,19)." },
    /* 10 */ { 10, "VFLTENV", "procFltVelocityAmount", "VelToFilterEnv", "", obxf_apply_vfltenv, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1." },
    /* 11 */ { 11, "VAMPENV", "procAmpVelocityAmount", "VelToAmpEnv", "", obxf_apply_vampenv, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1." },
    /* 12 */ { 12, "ASPLAYEDALLOCATION", "procAsPlayedAlloc", "NotePriority", "", obxf_apply_asplayedallocation, obxf_pt_invert_notepriority, 0, DRUM_GLOBAL, 0, "BOOL→TRI: native = v>0.5 ? 0 : 0.5 (STRICT >). High state (1.0) has no ancestor. Invert (representative): legacy = n>0.25 ? 0 : 1." },
    /* 13 */ { 13, "PORTAMENTO", "processPortamento", "Portamento", "", obxf_apply_portamento, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "1:1; both engines logsc(1-v,0.14,250,150) internally." },
    /* 14 */ { 14, "UNISON", "processUnison", "Unison", "", obxf_apply_unison, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "1:1; >=0.5 threshold." },
    /* 15 */ { 15, "UDET", "processDetune", "UnisonDetune", "", obxf_apply_udet, obxf_invert_udet, 0, DRUM_GLOBAL, 0, "RESCALE: dXd=logsc(v,0.001,0.90); native=invLogsc(dXd,0.001,1.0). Invert (exact): d=logsc(n,0.001,1.0) → legacy=invLogsc(d,0.001,0.90)." },
    /* 16 */ { 16, "OSC2_DET", "processOsc2Det", "Osc2Detune", "", obxf_apply_osc2_det, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines logsc(v,0.001,0.6) internally." },
    /* 17 */ { 17, "LFOFREQ", "processLfoFrequency", "LFO1Rate", "", NULL, NULL, 1, DRUM_GLOBAL, 0, "SPECIAL INLINE: free path logsc(v,0,50,120)→invLogsc(·,0,250,3775) (~75x range shift); synced path (LFO_SYNC mirror>0.5) 9→21 bucket table. Reads instance mirror → stays inline in C before AND after the refactor. Sets synth.globalLFO (shared LFO1) → drumClass global." },
    /* 18 */ { 18, "LFOSINWAVE", "processLfoSine", "LFO1Wave1", "", obxf_apply_lfosinwave, obxf_pt_invert_bool_blend, 0, DRUM_GLOBAL, 0, "BOOL→BLEND: native = v>=0.5 ? 0 : 0.5 (Sine/Triangle). Shared globalLFO → drumClass global. Invert (representative): legacy = n<0.25 ? 1 : 0." },
    /* 19 */ { 19, "LFOSQUAREWAVE", "processLfoSquare", "LFO1Wave2", "", obxf_apply_lfosquarewave, obxf_pt_invert_bool_blend, 0, DRUM_GLOBAL, 0, "BOOL→BLEND, same transform (Pulse/Saw). Invert (representative): legacy = n<0.25 ? 1 : 0." },
    /* 20 */ { 20, "LFOSHWAVE", "processLfoSH", "LFO1Wave3", "", obxf_apply_lfoshwave, obxf_pt_invert_bool_blend, 0, DRUM_GLOBAL, 0, "BOOL→BLEND, same transform (S&H/S&G). Invert (representative): legacy = n<0.25 ? 1 : 0." },
    /* 21 */ { 21, "LFO1AMT", "processLfoAmt1", "LFO1ModAmount1", "", obxf_apply_lfo1amt, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines logsc(logsc(v,0,1,60),0,60,10) internally." },
    /* 22 */ { 22, "LFO2AMT", "processLfoAmt2", "LFO1ModAmount2", "", obxf_apply_lfo2amt, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "AMBIGUOUS NAME: old LFO2AMT is LFO1 second mod amount, NOT LFO2. 1:1; both engines linsc(v,0,0.7)." },
    /* 23 */ { 23, "LFOOSC1", "processLfoOsc1", "LFO1ToOsc1Pitch", "", obxf_apply_lfoosc1, obxf_pt_invert_bool_tristate, 0, DRUM_VOICE, 0, "BOOL→TRI {Off,On,Inv}=0/0.5/1: native = v>=0.5 ? 0.5 : 0. Inv state has no ancestor. Invert (representative): legacy = n>=0.25 ? 1 : 0." },
    /* 24 */ { 24, "LFOOSC2", "processLfoOsc2", "LFO1ToOsc2Pitch", "", obxf_apply_lfoosc2, obxf_pt_invert_bool_tristate, 0, DRUM_VOICE, 0, "BOOL→TRI, same transform. Invert (representative): legacy = n>=0.25 ? 1 : 0." },
    /* 25 */ { 25, "LFOFILTER", "processLfoFilter", "LFO1ToFilterCutoff", "", obxf_apply_lfofilter, obxf_pt_invert_bool_tristate, 0, DRUM_VOICE, 0, "BOOL→TRI, same transform. Invert (representative): legacy = n>=0.25 ? 1 : 0." },
    /* 26 */ { 26, "LFOPW1", "processLfoPw1", "LFO1ToOsc1PW", "", obxf_apply_lfopw1, obxf_pt_invert_bool_tristate, 0, DRUM_VOICE, 0, "BOOL→TRI, same transform. Invert (representative): legacy = n>=0.25 ? 1 : 0." },
    /* 27 */ { 27, "LFOPW2", "processLfoPw2", "LFO1ToOsc2PW", "", obxf_apply_lfopw2, obxf_pt_invert_bool_tristate, 0, DRUM_VOICE, 0, "BOOL→TRI, same transform. NOT LFO2 — LFO1→Osc2PW. Invert (representative): legacy = n>=0.25 ? 1 : 0." },
    /* 28 */ { 28, "OSC2HS", "processOsc2HardSync", "OscSync", "", obxf_apply_osc2hs, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5 threshold." },
    /* 29 */ { 29, "XMOD", "processOsc2Xmod", "OscCrossmod", "", obxf_apply_xmod, obxf_invert_xmod, 0, DRUM_VOICE, 0, "RESCALE: old v*24 st, new v*48 st → native = v*0.5. Invert (exact): legacy = n*2." },
    /* 30 */ { 30, "OSC1P", "processOsc1Pitch", "Osc1Pitch", "", obxf_apply_osc1p, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines v*48 st. Importer additionally has an OCTAVE-compensation branch at .fxp import time (runtime dispatch is 1:1)." },
    /* 31 */ { 31, "OSC2P", "processOsc2Pitch", "Osc2Pitch", "", obxf_apply_osc2p, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines v*48 st. Same importer-side OCTAVE-compensation note as OSC1P." },
    /* 32 */ { 32, "OSCQuantize", "processPitchQuantization", "", "", NULL, NULL, 0, DRUM_NONE, 0, "REMOVED: no runtime param in OB-Xf. Importer only READS it to round osc pitches at import time." },
    /* 33 */ { 33, "OSC1Saw", "processOsc1Saw", "Osc1SawWave", "", obxf_apply_osc1saw, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5 threshold." },
    /* 34 */ { 34, "OSC1Pul", "processOsc1Pulse", "Osc1PulseWave", "", obxf_apply_osc1pul, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5 threshold." },
    /* 35 */ { 35, "OSC2Saw", "processOsc2Saw", "Osc2SawWave", "", obxf_apply_osc2saw, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5 threshold." },
    /* 36 */ { 36, "OSC2Pul", "processOsc2Pulse", "Osc2PulseWave", "", obxf_apply_osc2pul, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5 threshold." },
    /* 37 */ { 37, "PW", "processPulseWidth", "OscPW", "", obxf_apply_pw, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines linsc(v,0,0.95) internally." },
    /* 38 */ { 38, "BRIGHTNESS", "processBrightness", "OscBrightness", "", obxf_apply_brightness, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines linsc(v,7000,26000) internally." },
    /* 39 */ { 39, "ENVPITCH", "processEnvelopeToPitch", "EnvToPitchAmount", "", obxf_apply_envpitch, obxf_invert_envpitch, 0, DRUM_VOICE, 0, "RESCALE: old v*36 st, new v*40 st → native = v*(36/40) = v*0.9. Invert (exact): legacy = n*(40/36)." },
    /* 40 */ { 40, "OSC1MIX", "processOsc1Mix", "Osc1Mix", "", obxf_apply_osc1mix, obxf_pt_invert_identity, 0, DRUM_VOICE, 1, "1:1. THREE names differ: ID string Osc1Mix, C++ ID constant Osc1Vol, method processOsc1Volume. drumRestoreSkip: initDrumMode silences oscillators for PCM voices." },
    /* 41 */ { 41, "OSC2MIX", "processOsc2Mix", "Osc2Mix", "", obxf_apply_osc2mix, obxf_pt_invert_identity, 0, DRUM_VOICE, 1, "1:1. Same three-name split as OSC1MIX (Osc2Mix / Osc2Vol / processOsc2Volume). drumRestoreSkip: initDrumMode silences oscillators." },
    /* 42 */ { 42, "NOISEMIX", "processNoiseMix", "NoiseMix", "", obxf_apply_noisemix, obxf_invert_noisemix, 0, DRUM_VOICE, 1, "LOGSC BAKE: old engine applied logsc(v,0,1,35) INTERNALLY; OB-Xf takes the pre-scaled value → native = logsc(v,0,1,35), xf curve identity (no unmap). Invert (exact): legacy = invLogsc(n,0,1,35). ID NoiseMix (C++ constant NoiseVol), method processNoiseVolume. drumRestoreSkip: noise floor owned by drum init." },
    /* 43 */ { 43, "FLT_KF", "processFilterKeyFollow", "FilterKeyFollow", "", obxf_apply_flt_kf, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1. Names differ: ID FilterKeyFollow (C++ constant FilterKeyTrack), method processFilterKeyTrack." },
    /* 44 */ { 44, "CUTOFF", "processCutoff", "FilterCutoff", "", obxf_apply_cutoff, obxf_pt_invert_identity, 0, DRUM_SMOOTHER, 0, "1:1; both engines linsc(v,0,120) into the cutoff smoother. drumClass smoother: processX writes the synth-GLOBAL cutoffSmoother — drum layers apply it directly per triggered voice (v->par.filter.cutoff)." },
    /* 45 */ { 45, "RESONANCE", "processResonance", "FilterResonance", "", obxf_apply_resonance, obxf_pt_invert_identity, 0, DRUM_SMOOTHER, 0, "1:1; both engines 0.991-logsc(1-v,0,0.991,40). drumClass smoother: resSmoother is synth-global; drum layers set v->filter.setResonance directly." },
    /* 46 */ { 46, "MULTIMODE", "processMultimode", "FilterMode", "", obxf_apply_multimode, obxf_pt_invert_identity, 0, DRUM_SMOOTHER, 0, "1:1 (old per-voice, new smoother — same range). drumClass smoother: filterModeSmoother is synth-global; drum layers set v->filter.setMultimode directly." },
    /* 47 */ { 47, "FILTER_WARM", "processOversampling", "HQMode", "", obxf_apply_filter_warm, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "RENAME+BEHAVIOR: old SetOversample, new SetHQMode AND the engine calls allSoundOff() on toggle — drumClass global so per-voice application cannot cut drum voices mid-trigger." },
    /* 48 */ { 48, "BANDPASS", "processBandpassSw", "Filter2PoleBPBlend", "", obxf_apply_bandpass, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5 threshold." },
    /* 49 */ { 49, "FOURPOLE", "processFourPole", "Filter4PoleMode", "", obxf_apply_fourpole, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5 threshold." },
    /* 50 */ { 50, "ENVELOPE_AMT", "processFilterEnvelopeAmt", "FilterEnvAmount", "", obxf_apply_envelope_amt, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines linsc(v,0,140) internally." },
    /* 51 */ { 51, "LATK", "processLoudnessEnvelopeAttack", "AmpEnvAttack", "", obxf_apply_latk, obxf_invert_latk, 0, DRUM_SMOOTHER, 1, "RESCALE: msXd=logsc(v,4,60000,900); native=invLogsc(msXd/3,4,60000,900) — attack /3 only (decay/release are NOT divided). Invert (exact): msXd=logsc(n,4,60000,900)*3 → legacy=invLogsc(msXd,4,60000,900). drumClass smoother AND drumRestoreSkip — the two flags are orthogonal (direct per-voice setAttack on drum layers; amp attack owned by drum init)." },
    /* 52 */ { 52, "LDEC", "processLoudnessEnvelopeDecay", "AmpEnvDecay", "", obxf_apply_ldec, obxf_pt_invert_identity, 0, DRUM_SMOOTHER, 0, "1:1; both engines logsc(v,4,60000,900). Importer does NOT /3 decay. drumClass smoother: direct per-voice setDecay on drum layers." },
    /* 53 */ { 53, "LSUS", "processLoudnessEnvelopeSustain", "AmpEnvSustain", "", obxf_apply_lsus, obxf_pt_invert_identity, 0, DRUM_SMOOTHER, 0, "1:1. drumClass smoother: direct per-voice setSustain on drum layers." },
    /* 54 */ { 54, "LREL", "processLoudnessEnvelopeRelease", "AmpEnvRelease", "", obxf_apply_lrel, obxf_pt_invert_identity, 0, DRUM_SMOOTHER, 1, "1:1; both engines logsc(v,8,60000,900) (NOTE lo=8, unlike LATK/LDEC lo=4). drumClass smoother AND drumRestoreSkip (orthogonal): direct per-voice setRelease on drum layers; release owned by drum init." },
    /* 55 */ { 55, "FATK", "processFilterEnvelopeAttack", "FilterEnvAttack", "", obxf_apply_fatk, obxf_invert_fatk, 0, DRUM_VOICE, 0, "RESCALE: msXd=logsc(v,1,60000,900); native=invLogsc(msXd/3,1,60000,900) — filter attack /3 (lo=1, not 4). Invert (exact): msXd=logsc(n,1,60000,900)*3 → legacy=invLogsc(msXd,1,60000,900)." },
    /* 56 */ { 56, "FDEC", "processFilterEnvelopeDecay", "FilterEnvDecay", "", obxf_apply_fdec, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines logsc(v,1,60000,900)." },
    /* 57 */ { 57, "FSUS", "processFilterEnvelopeSustain", "FilterEnvSustain", "", obxf_apply_fsus, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1." },
    /* 58 */ { 58, "FREL", "processFilterEnvelopeRelease", "FilterEnvRelease", "", obxf_apply_frel, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines logsc(v,1,60000,900)." },
    /* 59 */ { 59, "ENVDER", "processEnvelopeDetune", "EnvelopeSlop", "", obxf_apply_envder, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; old setEnvDer(linsc(v,0,1)) internally, new setEnvTimingOffset(v)." },
    /* 60 */ { 60, "FILTERDER", "processFilterDetune", "FilterSlop", "", obxf_apply_filterder, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines linsc(v,0,18) internally." },
    /* 61 */ { 61, "PORTADER", "processPortamentoDetune", "PortamentoSlop", "", obxf_apply_portader, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines linsc(v,0,0.75) internally." },
    /* 62 */ { 62, "PAN1", "processPan", "PanVoice1", "", obxf_apply_pan1, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "Value identity; call processPan(v, 1) — method takes an EXTRA voiceIndex argument. processPan writes synth.pannings (no ForEachVoice) → drumClass global; PCM voice panning comes from Voice::pcmPan." },
    /* 63 */ { 63, "PAN2", "processPan", "PanVoice2", "", obxf_apply_pan2, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "processPan(v, 2). See PAN1." },
    /* 64 */ { 64, "PAN3", "processPan", "PanVoice3", "", obxf_apply_pan3, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "processPan(v, 3). See PAN1." },
    /* 65 */ { 65, "PAN4", "processPan", "PanVoice4", "", obxf_apply_pan4, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "processPan(v, 4). See PAN1." },
    /* 66 */ { 66, "PAN5", "processPan", "PanVoice5", "", obxf_apply_pan5, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "processPan(v, 5). Old OB-Xd MAX_VOICES=8 so PAN5..8 were rarely used." },
    /* 67 */ { 67, "PAN6", "processPan", "PanVoice6", "", obxf_apply_pan6, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "processPan(v, 6). See PAN5." },
    /* 68 */ { 68, "PAN7", "processPan", "PanVoice7", "", obxf_apply_pan7, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "processPan(v, 7). See PAN5." },
    /* 69 */ { 69, "PAN8", "processPan", "PanVoice8", "", obxf_apply_pan8, obxf_pt_invert_identity, 0, DRUM_GLOBAL, 0, "processPan(v, 8). See PAN5." },
    /* 70 */ { 70, "UNLEARN", "(UI-only)", "", "", NULL, NULL, 0, DRUM_NONE, 0, "REMOVED: UI-only, no engine action, no OB-Xf equivalent." },
    /* 71 */ { 71, "ECONOMY_MODE", "procEconomyMode", "", "", NULL, NULL, 0, DRUM_NONE, 0, "REMOVED: OB-Xf has no economy mode (HQMode is the successor but maps from FILTER_WARM)." },
    /* 72 */ { 72, "LFO_SYNC", "procLfoSync", "LFO1TempoSync", "", NULL, NULL, 1, DRUM_GLOBAL, 0, "SPECIAL INLINE: processLFO1Sync(v) (method name has no \"Tempo\"), then re-dispatch LFOFREQ from the mirror so a sequentially-loaded .fxp gets the right rate path. Shared globalLFO → drumClass global. Importer warns old sync behavior was unreliable." },
    /* 73 */ { 73, "PW_ENV", "processPwEnv", "EnvToPWAmount", "", obxf_apply_pw_env, obxf_invert_pw_env, 0, DRUM_VOICE, 0, "RESCALE: old linsc(v,0,0.85), new linsc(v,0,1.055555555) → native = v*(0.85/1.0555555555). Invert (exact): legacy = n*(1.0555555555/0.85)." },
    /* 74 */ { 74, "PW_ENV_BOTH", "processPwEnvBoth", "EnvToPWBothOscs", "", obxf_apply_pw_env_both, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5 threshold." },
    /* 75 */ { 75, "ENV_PITCH_BOTH", "processPitchModBoth", "EnvToPitchBothOscs", "", obxf_apply_env_pitch_both, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5. METHOD MISMATCH: method is processPitchBothOscs (no \"EnvTo\" prefix) — NOT processEnvToPitchBothOscs." },
    /* 76 */ { 76, "FENV_INVERT", "processInvertFenv", "FilterEnvInvert", "", obxf_apply_fenv_invert, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5 threshold." },
    /* 77 */ { 77, "PW_OSC2_OFS", "processPwOfs", "Osc2PWOffset", "", obxf_apply_pw_osc2_ofs, obxf_invert_pw_osc2_ofs, 0, DRUM_VOICE, 0, "RESCALE: old linsc(v,0,0.75), new linsc(v,0,0.95) → native = v*(0.75/0.95). Invert (exact): legacy = n*(0.95/0.75)." },
    /* 78 */ { 78, "LEVEL_DIF", "processLoudnessDetune", "LevelSlop", "", obxf_apply_level_dif, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; both engines linsc(v,0,0.67) internally." },
    /* 79 */ { 79, "SELF_OSC_PUSH", "processSelfOscPush", "Filter2PolePush", "", obxf_apply_self_osc_push, obxf_pt_invert_identity, 0, DRUM_VOICE, 0, "1:1; >=0.5 threshold. RENAMED: old selfOscPush, new setFilter2PolePush." },
};

static_assert(sizeof(obxf_legacy_params) / sizeof(obxf_legacy_params[0]) == OBXF_PT_LEGACY_COUNT,
               "legacy table must have exactly OBXF_PT_LEGACY_COUNT rows");

// =========================================================================
// NEW-param table — exactly 28 rows, indexed by canonical ordinal
// (declaration order of streaming IDs in obxf_imported/parameter/SynthParam.h,
// filtered to the params with no legacy ancestor). NOTE: this intentionally
// differs from the legacy runtime sentinel order frozen in
// tools/new-param-order-v1.json (see tools/PARAM_SPEC.md).
// =========================================================================
static const obxf_new_param_t obxf_new_params[OBXF_PT_NEW_COUNT] = {
    /*  0 */ { "UnisonVoices", obxf_native_UnisonVoices, DRUM_GLOBAL, "GLOBAL. processUnisonVoices → synth.setUnisonVoices → Motherboard::unisonVoiceCount (synth-global voice-allocation field, no ForEachVoice) → drumClass global." },
    /*  1 */ { "VoiceReassign", obxf_native_VoiceReassign, DRUM_GLOBAL, "GLOBAL. processVoiceReassign → synth.reallocate (Motherboard bool read by setNoteOn, no ForEachVoice) → drumClass global." },
    /*  2 */ { "Osc2Keytrack", obxf_native_Osc2Keytrack, DRUM_VOICE, "OSCILLATORS." },
    /*  3 */ { "EnvToPitchInvert", obxf_native_EnvToPitchInvert, DRUM_VOICE, "OSCILLATORS." },
    /*  4 */ { "EnvToPWInvert", obxf_native_EnvToPWInvert, DRUM_VOICE, "OSCILLATORS." },
    /*  5 */ { "RingModMix", obxf_native_RingModMix, DRUM_VOICE, "MIXER. ID constant RingModVol; method processRingModVolume." },
    /*  6 */ { "NoiseColor", obxf_native_NoiseColor, DRUM_VOICE, "MIXER." },
    /*  7 */ { "VibratoWave", obxf_native_VibratoWave, DRUM_GLOBAL, "CONTROL. processVibratoLFOWave → synth.vibratoLFO.par.{wave1blend,wave2blend} (shared Motherboard LFO, no ForEachVoice) → drumClass global." },
    /*  8 */ { "Filter4PoleXpander", obxf_native_Filter4PoleXpander, DRUM_VOICE, "FILTER." },
    /*  9 */ { "FilterXpanderMode", obxf_native_FilterXpanderMode, DRUM_VOICE, "FILTER." },
    /* 10 */ { "LFO1PW", obxf_native_LFO1PW, DRUM_GLOBAL, "LFO1. processLFO1PW → synth.globalLFO.par.pw (shared Motherboard LFO1, no ForEachVoice) → drumClass global." },
    /* 11 */ { "LFO1ToVolume", obxf_native_LFO1ToVolume, DRUM_VOICE, "LFO1." },
    /* 12 */ { "LFO2TempoSync", obxf_native_LFO2TempoSync, DRUM_VOICE, "LFO2. Method processLFO2Sync (no \"Tempo\")." },
    /* 13 */ { "LFO2Wave1", obxf_native_LFO2Wave1, DRUM_VOICE, "LFO2. Declaration order puts waves before rate — differs from runtime sentinel order." },
    /* 14 */ { "LFO2Wave2", obxf_native_LFO2Wave2, DRUM_VOICE, "LFO2." },
    /* 15 */ { "LFO2Wave3", obxf_native_LFO2Wave3, DRUM_VOICE, "LFO2." },
    /* 16 */ { "LFO2PW", obxf_native_LFO2PW, DRUM_VOICE, "LFO2." },
    /* 17 */ { "LFO2Rate", obxf_native_LFO2Rate, DRUM_VOICE, "LFO2. Runtime sentinel offset was 13 — canonical ordinal 17." },
    /* 18 */ { "LFO2ModAmount1", obxf_native_LFO2ModAmount1, DRUM_VOICE, "LFO2. Runtime sentinel offset was 14." },
    /* 19 */ { "LFO2ModAmount2", obxf_native_LFO2ModAmount2, DRUM_VOICE, "LFO2. Runtime sentinel offset was 15." },
    /* 20 */ { "LFO2ToOsc1Pitch", obxf_native_LFO2ToOsc1Pitch, DRUM_VOICE, "LFO2." },
    /* 21 */ { "LFO2ToOsc2Pitch", obxf_native_LFO2ToOsc2Pitch, DRUM_VOICE, "LFO2." },
    /* 22 */ { "LFO2ToFilterCutoff", obxf_native_LFO2ToFilterCutoff, DRUM_VOICE, "LFO2." },
    /* 23 */ { "LFO2ToOsc1PW", obxf_native_LFO2ToOsc1PW, DRUM_VOICE, "LFO2." },
    /* 24 */ { "LFO2ToOsc2PW", obxf_native_LFO2ToOsc2PW, DRUM_VOICE, "LFO2." },
    /* 25 */ { "LFO2ToVolume", obxf_native_LFO2ToVolume, DRUM_VOICE, "LFO2." },
    /* 26 */ { "FilterEnvAttackCurve", obxf_native_FilterEnvAttackCurve, DRUM_VOICE, "FILTER ENVELOPE." },
    /* 27 */ { "AmpEnvAttackCurve", obxf_native_AmpEnvAttackCurve, DRUM_VOICE, "AMPLIFIER ENVELOPE." },
};

static_assert(sizeof(obxf_new_params) / sizeof(obxf_new_params[0]) == OBXF_PT_NEW_COUNT,
               "new-param table must have exactly OBXF_PT_NEW_COUNT rows");

// =========================================================================
// Name index — exactly 104 entries, one PER STREAMING NAME
// (all legacy non-empty names INCLUDING both BENDRANGE halves, plus all
// 28 NEW names), sorted bytewise-lexicographically for binary search.
// Lookup: obxf_param_name_find(name, nlen).
// =========================================================================
static const obxf_param_name_entry_t obxf_param_name_index[OBXF_PT_NAME_INDEX_COUNT] = {
    { "AmpEnvAttack", obxf_native_AmpEnvAttack, 51, -1, obxf_invert_latk },
    { "AmpEnvAttackCurve", obxf_native_AmpEnvAttackCurve, -1, 27, NULL },
    { "AmpEnvDecay", obxf_native_AmpEnvDecay, 52, -1, obxf_pt_invert_identity },
    { "AmpEnvRelease", obxf_native_AmpEnvRelease, 54, -1, obxf_pt_invert_identity },
    { "AmpEnvSustain", obxf_native_AmpEnvSustain, 53, -1, obxf_pt_invert_identity },
    { "BendOsc2Only", obxf_native_BendOsc2Only, 7, -1, obxf_pt_invert_identity },
    { "EnvLegatoMode", obxf_native_EnvLegatoMode, 8, -1, obxf_pt_invert_identity },
    { "EnvToPWAmount", obxf_native_EnvToPWAmount, 73, -1, obxf_invert_pw_env },
    { "EnvToPWBothOscs", obxf_native_EnvToPWBothOscs, 74, -1, obxf_pt_invert_identity },
    { "EnvToPWInvert", obxf_native_EnvToPWInvert, -1, 4, NULL },
    { "EnvToPitchAmount", obxf_native_EnvToPitchAmount, 39, -1, obxf_invert_envpitch },
    { "EnvToPitchBothOscs", obxf_native_EnvToPitchBothOscs, 75, -1, obxf_pt_invert_identity },
    { "EnvToPitchInvert", obxf_native_EnvToPitchInvert, -1, 3, NULL },
    { "EnvelopeSlop", obxf_native_EnvelopeSlop, 59, -1, obxf_pt_invert_identity },
    { "Filter2PoleBPBlend", obxf_native_Filter2PoleBPBlend, 48, -1, obxf_pt_invert_identity },
    { "Filter2PolePush", obxf_native_Filter2PolePush, 79, -1, obxf_pt_invert_identity },
    { "Filter4PoleMode", obxf_native_Filter4PoleMode, 49, -1, obxf_pt_invert_identity },
    { "Filter4PoleXpander", obxf_native_Filter4PoleXpander, -1, 8, NULL },
    { "FilterCutoff", obxf_native_FilterCutoff, 44, -1, obxf_pt_invert_identity },
    { "FilterEnvAmount", obxf_native_FilterEnvAmount, 50, -1, obxf_pt_invert_identity },
    { "FilterEnvAttack", obxf_native_FilterEnvAttack, 55, -1, obxf_invert_fatk },
    { "FilterEnvAttackCurve", obxf_native_FilterEnvAttackCurve, -1, 26, NULL },
    { "FilterEnvDecay", obxf_native_FilterEnvDecay, 56, -1, obxf_pt_invert_identity },
    { "FilterEnvInvert", obxf_native_FilterEnvInvert, 76, -1, obxf_pt_invert_identity },
    { "FilterEnvRelease", obxf_native_FilterEnvRelease, 58, -1, obxf_pt_invert_identity },
    { "FilterEnvSustain", obxf_native_FilterEnvSustain, 57, -1, obxf_pt_invert_identity },
    { "FilterKeyFollow", obxf_native_FilterKeyFollow, 43, -1, obxf_pt_invert_identity },
    { "FilterMode", obxf_native_FilterMode, 46, -1, obxf_pt_invert_identity },
    { "FilterResonance", obxf_native_FilterResonance, 45, -1, obxf_pt_invert_identity },
    { "FilterSlop", obxf_native_FilterSlop, 60, -1, obxf_pt_invert_identity },
    { "FilterXpanderMode", obxf_native_FilterXpanderMode, -1, 9, NULL },
    { "HQMode", obxf_native_HQMode, 47, -1, obxf_pt_invert_identity },
    { "LFO1ModAmount1", obxf_native_LFO1ModAmount1, 21, -1, obxf_pt_invert_identity },
    { "LFO1ModAmount2", obxf_native_LFO1ModAmount2, 22, -1, obxf_pt_invert_identity },
    { "LFO1PW", obxf_native_LFO1PW, -1, 10, NULL },
    { "LFO1Rate", obxf_native_LFO1Rate, 17, -1, NULL },
    { "LFO1TempoSync", obxf_native_LFO1TempoSync, 72, -1, NULL },
    { "LFO1ToFilterCutoff", obxf_native_LFO1ToFilterCutoff, 25, -1, obxf_pt_invert_bool_tristate },
    { "LFO1ToOsc1PW", obxf_native_LFO1ToOsc1PW, 26, -1, obxf_pt_invert_bool_tristate },
    { "LFO1ToOsc1Pitch", obxf_native_LFO1ToOsc1Pitch, 23, -1, obxf_pt_invert_bool_tristate },
    { "LFO1ToOsc2PW", obxf_native_LFO1ToOsc2PW, 27, -1, obxf_pt_invert_bool_tristate },
    { "LFO1ToOsc2Pitch", obxf_native_LFO1ToOsc2Pitch, 24, -1, obxf_pt_invert_bool_tristate },
    { "LFO1ToVolume", obxf_native_LFO1ToVolume, -1, 11, NULL },
    { "LFO1Wave1", obxf_native_LFO1Wave1, 18, -1, obxf_pt_invert_bool_blend },
    { "LFO1Wave2", obxf_native_LFO1Wave2, 19, -1, obxf_pt_invert_bool_blend },
    { "LFO1Wave3", obxf_native_LFO1Wave3, 20, -1, obxf_pt_invert_bool_blend },
    { "LFO2ModAmount1", obxf_native_LFO2ModAmount1, -1, 18, NULL },
    { "LFO2ModAmount2", obxf_native_LFO2ModAmount2, -1, 19, NULL },
    { "LFO2PW", obxf_native_LFO2PW, -1, 16, NULL },
    { "LFO2Rate", obxf_native_LFO2Rate, -1, 17, NULL },
    { "LFO2TempoSync", obxf_native_LFO2TempoSync, -1, 12, NULL },
    { "LFO2ToFilterCutoff", obxf_native_LFO2ToFilterCutoff, -1, 22, NULL },
    { "LFO2ToOsc1PW", obxf_native_LFO2ToOsc1PW, -1, 23, NULL },
    { "LFO2ToOsc1Pitch", obxf_native_LFO2ToOsc1Pitch, -1, 20, NULL },
    { "LFO2ToOsc2PW", obxf_native_LFO2ToOsc2PW, -1, 24, NULL },
    { "LFO2ToOsc2Pitch", obxf_native_LFO2ToOsc2Pitch, -1, 21, NULL },
    { "LFO2ToVolume", obxf_native_LFO2ToVolume, -1, 25, NULL },
    { "LFO2Wave1", obxf_native_LFO2Wave1, -1, 13, NULL },
    { "LFO2Wave2", obxf_native_LFO2Wave2, -1, 14, NULL },
    { "LFO2Wave3", obxf_native_LFO2Wave3, -1, 15, NULL },
    { "LevelSlop", obxf_native_LevelSlop, 78, -1, obxf_pt_invert_identity },
    { "NoiseColor", obxf_native_NoiseColor, -1, 6, NULL },
    { "NoiseMix", obxf_native_NoiseMix, 42, -1, obxf_invert_noisemix },
    { "NotePriority", obxf_native_NotePriority, 12, -1, obxf_pt_invert_notepriority },
    { "Osc1Mix", obxf_native_Osc1Mix, 40, -1, obxf_pt_invert_identity },
    { "Osc1Pitch", obxf_native_Osc1Pitch, 30, -1, obxf_pt_invert_identity },
    { "Osc1PulseWave", obxf_native_Osc1PulseWave, 34, -1, obxf_pt_invert_identity },
    { "Osc1SawWave", obxf_native_Osc1SawWave, 33, -1, obxf_pt_invert_identity },
    { "Osc2Detune", obxf_native_Osc2Detune, 16, -1, obxf_pt_invert_identity },
    { "Osc2Keytrack", obxf_native_Osc2Keytrack, -1, 2, NULL },
    { "Osc2Mix", obxf_native_Osc2Mix, 41, -1, obxf_pt_invert_identity },
    { "Osc2PWOffset", obxf_native_Osc2PWOffset, 77, -1, obxf_invert_pw_osc2_ofs },
    { "Osc2Pitch", obxf_native_Osc2Pitch, 31, -1, obxf_pt_invert_identity },
    { "Osc2PulseWave", obxf_native_Osc2PulseWave, 36, -1, obxf_pt_invert_identity },
    { "Osc2SawWave", obxf_native_Osc2SawWave, 35, -1, obxf_pt_invert_identity },
    { "OscBrightness", obxf_native_OscBrightness, 38, -1, obxf_pt_invert_identity },
    { "OscCrossmod", obxf_native_OscCrossmod, 29, -1, obxf_invert_xmod },
    { "OscPW", obxf_native_OscPW, 37, -1, obxf_pt_invert_identity },
    { "OscSync", obxf_native_OscSync, 28, -1, obxf_pt_invert_identity },
    { "PanVoice1", obxf_native_PanVoice1, 62, -1, obxf_pt_invert_identity },
    { "PanVoice2", obxf_native_PanVoice2, 63, -1, obxf_pt_invert_identity },
    { "PanVoice3", obxf_native_PanVoice3, 64, -1, obxf_pt_invert_identity },
    { "PanVoice4", obxf_native_PanVoice4, 65, -1, obxf_pt_invert_identity },
    { "PanVoice5", obxf_native_PanVoice5, 66, -1, obxf_pt_invert_identity },
    { "PanVoice6", obxf_native_PanVoice6, 67, -1, obxf_pt_invert_identity },
    { "PanVoice7", obxf_native_PanVoice7, 68, -1, obxf_pt_invert_identity },
    { "PanVoice8", obxf_native_PanVoice8, 69, -1, obxf_pt_invert_identity },
    { "PitchBendDown", obxf_native_PitchBendDown, 6, -1, obxf_pt_invert_split_bendrange },
    { "PitchBendUp", obxf_native_PitchBendUp, 6, -1, obxf_pt_invert_split_bendrange },
    { "Polyphony", obxf_native_Polyphony, 3, -1, obxf_pt_invert_voice_count },
    { "Portamento", obxf_native_Portamento, 13, -1, obxf_pt_invert_identity },
    { "PortamentoSlop", obxf_native_PortamentoSlop, 61, -1, obxf_pt_invert_identity },
    { "RingModMix", obxf_native_RingModMix, -1, 5, NULL },
    { "Transpose", obxf_native_Transpose, 5, -1, obxf_pt_invert_octave_transpose },
    { "Tune", obxf_native_Tune, 4, -1, obxf_pt_invert_identity },
    { "Unison", obxf_native_Unison, 14, -1, obxf_pt_invert_identity },
    { "UnisonDetune", obxf_native_UnisonDetune, 15, -1, obxf_invert_udet },
    { "UnisonVoices", obxf_native_UnisonVoices, -1, 0, NULL },
    { "VelToAmpEnv", obxf_native_VelToAmpEnv, 11, -1, obxf_pt_invert_identity },
    { "VelToFilterEnv", obxf_native_VelToFilterEnv, 10, -1, obxf_pt_invert_identity },
    { "VibratoRate", obxf_native_VibratoRate, 9, -1, obxf_invert_bendlforate },
    { "VibratoWave", obxf_native_VibratoWave, -1, 7, NULL },
    { "VoiceReassign", obxf_native_VoiceReassign, -1, 1, NULL },
    { "Volume", obxf_native_Volume, 2, -1, obxf_pt_invert_identity },
};

static_assert(sizeof(obxf_param_name_index) / sizeof(obxf_param_name_index[0]) == OBXF_PT_NAME_INDEX_COUNT,
               "name index must have exactly OBXF_PT_NAME_INDEX_COUNT entries");

// =========================================================================
// Lookup helpers
// =========================================================================
// Compare a (name, nlen) slice — NOT null-terminated — against a C string,
// bytewise. Returns 0 on exact full match (same semantics as main_obxd.cpp
// nameeq()), <0 when the slice sorts first, >0 when the entry sorts first.
// This is the ordering the name index above is sorted by.
static inline int obxf_param_name_cmp(const char* a, int alen, const char* b) {
    for (int i = 0; i < alen; ++i) {
        const unsigned char ca = (unsigned char)a[i];
        const unsigned char cb = (unsigned char)b[i];
        if (cb == 0) return 1; /* a is longer than b */
        if (ca != cb) return (int)ca - (int)cb;
    }
    return b[alen] == 0 ? 0 : -1; /* a is a proper prefix of b */
}

// Binary search the sorted name index. Returns the matching entry, or NULL
// for unknown names (metadata attributes like programName/author/etc.).
static inline const obxf_param_name_entry_t* obxf_param_name_find(const char* name, int nlen) {
    if (!name || nlen <= 0) return 0;
    int lo = 0, hi = OBXF_PT_NAME_INDEX_COUNT - 1;
    while (lo <= hi) {
        const int mid = lo + ((hi - lo) >> 1);
        const int c = obxf_param_name_cmp(name, nlen, obxf_param_name_index[mid].name);
        if (c == 0) return &obxf_param_name_index[mid];
        if (c < 0) hi = mid - 1;
        else lo = mid + 1;
    }
    return 0;
}

#endif /* OBXF_PARAM_TABLE_H */
