// AUTO-GENERATED by tools/prep-mixer-wasm.mjs — do not edit by hand.
// Source: CakeMix crates/mixer-wasm/pkg/mixer_wasm.js (wasm-bindgen,
// web target), stripped to a classic script for AudioWorkletGlobalScope.
//
// The glue body is wrapped in an IIFE: its internal top-level lets
// (`wasmModule`, `wasm`, `cachedTextDecoder`, …) would collide with the
// combined worklet script's own declarations (the processor tail already
// declares `wasmModule`). Only two bridge names escape the IIFE, exposed
// as top-level vars in the script's declarative record (bare-name access
// from the tail — the same mechanism the emcc factory names rely on):
//   __cmxInitSync(module) — initSync({module: new WebAssembly.Module(bytes)})
//   __cmxMixerWasm        — the MixerWasm class (constructor + methods)

var __cmxInitSync, __cmxMixerWasm;
(function () {
/* @ts-self-types="./mixer_wasm.d.ts" */

/**
 * WASM binding for the oximedia-mixer audio engine.
 *
 * # Architecture per block (staging → 9 engine instances → bus tail)
 *
 * 1. FIFO drain: elastic per-channel input FIFOs → `block_inputs`
 *    (raw mono rows, 128 × bs; starvation = zeros).
 * 2. STAGING: every existing strip's raw source signal is copied into
 *    its `staged` row, then the strip's own dynamics
 *    (gate → expander → compressor) and 6-band EQ run in place.
 *    Input strips (0-127) stage their own drained row; bus slots
 *    (128-255) stage the RAW row of their assigned source channel —
 *    a parallel raw tap, so the source strip's mute/fader/EQ/dynamics
 *    have ZERO effect on the bus path (pinned by tests/bus_parallel_test.rs).
 * 3. Per-channel metering (post-dynamics/EQ, pre-fader) and the
 *    channel direct-out tap (staged × input gain × phase × fader × VCA,
 *    pre-pan; muted/solo-gated strips tap silence).
 * 4. NINE engine instances perform ALL summing via `process_mix_rt`
 *    (input gain/phase → effects → fader × VCA → pan → PDC → sends →
 *    routing): `main` mixes strips 0-127 that exist, are not
 *    effectively muted, and have `main_assign`; bus engine i mixes its
 *    16 slots under the same rules.
 * 5. BUS TAIL: each bus's engine output × bus gain (mute → silence) →
 *    `bus_pub` (the bus's own published stereo output); buses with
 *    `feeds_main` && !bus_muted accumulate into master.
 * 6. Master gain → master limiter (L/R) → interleave → MasterMeter.
 *
 * Channel direct-out tap: `set_channel_tap()` captures each input
 * channel's MONO signal at the pan-stage input (post input gain/phase,
 * post gate/comp/EQ, post fader) during `process()` for external
 * publishing (WebSRT Nch out).
 */
class MixerWasm {
    __destroy_into_raw() {
        const ptr = this.__wbg_ptr;
        this.__wbg_ptr = 0;
        MixerWasmFinalization.unregister(this);
        return ptr;
    }
    free() {
        const ptr = this.__destroy_into_raw();
        wasm.__wbg_mixerwasm_free(ptr, 0);
    }
    /**
     * @returns {string}
     */
    bus_meters_json() {
        let deferred1_0;
        let deferred1_1;
        try {
            const ret = wasm.mixerwasm_bus_meters_json(this.__wbg_ptr);
            deferred1_0 = ret[0];
            deferred1_1 = ret[1];
            return getStringFromWasm0(ret[0], ret[1]);
        } finally {
            wasm.__wbindgen_free(deferred1_0, deferred1_1, 1);
        }
    }
    /**
     * @param {number} bus
     * @returns {number}
     */
    bus_peak_db(bus) {
        const ret = wasm.mixerwasm_bus_peak_db(this.__wbg_ptr, bus);
        return ret;
    }
    /**
     * @param {number} bus
     * @returns {number}
     */
    bus_rms_db(bus) {
        const ret = wasm.mixerwasm_bus_rms_db(this.__wbg_ptr, bus);
        return ret;
    }
    /**
     * The strip's compressor gain reduction (dB, positive = attenuation)
     * from the most recent processed block. 0.0 when the strip has no
     * compressor.
     * @param {number} ch
     * @returns {number}
     */
    channel_comp_gr_db(ch) {
        const ret = wasm.mixerwasm_channel_comp_gr_db(this.__wbg_ptr, ch);
        return ret;
    }
    /**
     * @returns {string}
     */
    channel_meters_json() {
        let deferred1_0;
        let deferred1_1;
        try {
            const ret = wasm.mixerwasm_channel_meters_json(this.__wbg_ptr);
            deferred1_0 = ret[0];
            deferred1_1 = ret[1];
            return getStringFromWasm0(ret[0], ret[1]);
        } finally {
            wasm.__wbindgen_free(deferred1_0, deferred1_1, 1);
        }
    }
    /**
     * @param {number} ch
     * @returns {number}
     */
    channel_peak_db(ch) {
        const ret = wasm.mixerwasm_channel_peak_db(this.__wbg_ptr, ch);
        return ret;
    }
    /**
     * @param {number} ch
     * @returns {number}
     */
    channel_rms_db(ch) {
        const ret = wasm.mixerwasm_channel_rms_db(this.__wbg_ptr, ch);
        return ret;
    }
    /**
     * @param {number} bus
     * @param {number} slot
     */
    clear_bus_source(bus, slot) {
        wasm.mixerwasm_clear_bus_source(this.__wbg_ptr, bus, slot);
    }
    /**
     * Serialize the console state for the UI as JSON — the reply to
     * the worklet's `get-params` pull after a `scene-recalled`
     * notification. Field names mirror the SolidJS stores exactly
     * (see `console_params_json_inner`, the pure-Rust core). During a
     * timed cross-fade the fade target serializes, so the UI shows the
     * recalled state the moment a fade starts.
     * @returns {string}
     */
    console_params_json() {
        let deferred1_0;
        let deferred1_1;
        try {
            const ret = wasm.mixerwasm_console_params_json(this.__wbg_ptr);
            deferred1_0 = ret[0];
            deferred1_1 = ret[1];
            return getStringFromWasm0(ret[0], ret[1]);
        } finally {
            wasm.__wbindgen_free(deferred1_0, deferred1_1, 1);
        }
    }
    /**
     * Drop scene `id` (unknown ids are a no-op).
     * @param {number} id
     */
    delete_scene(id) {
        wasm.mixerwasm_delete_scene(this.__wbg_ptr, id);
    }
    /**
     * @param {number} ch
     */
    disable_compressor(ch) {
        wasm.mixerwasm_disable_compressor(this.__wbg_ptr, ch);
    }
    /**
     * @param {number} ch
     */
    disable_expander(ch) {
        wasm.mixerwasm_disable_expander(this.__wbg_ptr, ch);
    }
    /**
     * @param {number} ch
     */
    disable_gate(ch) {
        wasm.mixerwasm_disable_gate(this.__wbg_ptr, ch);
    }
    /**
     * Total insert slips applied (net-slow delivery corrections).
     * @returns {bigint}
     */
    elastic_inserts() {
        const ret = wasm.mixerwasm_elastic_inserts(this.__wbg_ptr);
        return BigInt.asUintN(64, ret);
    }
    /**
     * Total trim slips applied (net-fast delivery corrections).
     * @returns {bigint}
     */
    elastic_slips() {
        const ret = wasm.mixerwasm_elastic_slips(this.__wbg_ptr);
        return BigInt.asUintN(64, ret);
    }
    /**
     * Enable compressor on a channel with broadcast defaults (-12 dB threshold, 3:1 ratio).
     * @param {number} ch
     */
    enable_compressor(ch) {
        const ret = wasm.mixerwasm_enable_compressor(this.__wbg_ptr, ch);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     */
    enable_expander(ch) {
        const ret = wasm.mixerwasm_enable_expander(this.__wbg_ptr, ch);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     */
    enable_gate(ch) {
        const ret = wasm.mixerwasm_enable_gate(this.__wbg_ptr, ch);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * Core interleaved feed (shared by the wasm binding and native
     * tests): deinterleave `interleaved` into channels
     * `ch_start..ch_start + num_channels`, appending to each channel's
     * elastic FIFO.
     * @param {number} ch_start
     * @param {Float32Array} interleaved
     * @param {number} num_channels
     */
    feed_interleaved(ch_start, interleaved, num_channels) {
        const ptr0 = passArrayF32ToWasm0(interleaved, wasm.__wbindgen_malloc);
        const len0 = WASM_VECTOR_LEN;
        const ret = wasm.mixerwasm_feed_interleaved(this.__wbg_ptr, ch_start, ptr0, len0, num_channels);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} pid
     * @param {Float32Array} data
     */
    feed_pcm(pid, data) {
        const ret = wasm.mixerwasm_feed_pcm(this.__wbg_ptr, pid, data);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * Keyed twin of `feed_pcm`: unmapped key → counted drop (never an
     * error), unsubscribed → silent drop; otherwise the JS buffer is
     * copied once and routed through the pure-Rust `feed_interleaved`
     * (same copy-then-inner structure as `set_channel_input_interleaved`,
     * so native tests can exercise the same path without a JS runtime).
     * @param {number} key
     * @param {Float32Array} data
     */
    feed_pcm_keyed(key, data) {
        const ret = wasm.mixerwasm_feed_pcm_keyed(this.__wbg_ptr, key, data);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * Deepest current FIFO depth across all channels (frames).
     * @returns {number}
     */
    fifo_max_depth() {
        const ret = wasm.mixerwasm_fifo_max_depth(this.__wbg_ptr);
        return ret >>> 0;
    }
    /**
     * @returns {number}
     */
    limiter_gain_reduction_db() {
        const ret = wasm.mixerwasm_limiter_gain_reduction_db(this.__wbg_ptr);
        return ret;
    }
    /**
     * @param {number} pid
     * @param {number} ch_start
     * @param {number} channel_count
     */
    map_pid(pid, ch_start, channel_count) {
        const ret = wasm.mixerwasm_map_pid(this.__wbg_ptr, pid, ch_start, channel_count);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} key
     * @param {number} ch_start
     * @param {number} channel_count
     */
    map_pid_keyed(key, ch_start, channel_count) {
        const ret = wasm.mixerwasm_map_pid_keyed(this.__wbg_ptr, key, ch_start, channel_count);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * Clear the sticky master clip indicators (both channels).
     */
    master_clear_clip() {
        wasm.mixerwasm_master_clear_clip(this.__wbg_ptr);
    }
    /**
     * @returns {boolean}
     */
    master_clipping() {
        const ret = wasm.mixerwasm_master_clipping(this.__wbg_ptr);
        return ret !== 0;
    }
    /**
     * @returns {number}
     */
    master_peak_db_l() {
        const ret = wasm.mixerwasm_master_peak_db_l(this.__wbg_ptr);
        return ret;
    }
    /**
     * @returns {number}
     */
    master_peak_db_r() {
        const ret = wasm.mixerwasm_master_peak_db_r(this.__wbg_ptr);
        return ret;
    }
    /**
     * @returns {number}
     */
    master_rms_db_l() {
        const ret = wasm.mixerwasm_master_rms_db_l(this.__wbg_ptr);
        return ret;
    }
    /**
     * @returns {number}
     */
    master_rms_db_r() {
        const ret = wasm.mixerwasm_master_rms_db_r(this.__wbg_ptr);
        return ret;
    }
    /**
     * @param {number} sample_rate
     * @param {number} buffer_size
     * @param {number} max_channels
     */
    constructor(sample_rate, buffer_size, max_channels) {
        const ret = wasm.mixerwasm_new(sample_rate, buffer_size, max_channels);
        if (ret[2]) {
            throw takeFromExternrefTable0(ret[1]);
        }
        this.__wbg_ptr = ret[0];
        MixerWasmFinalization.register(this, this.__wbg_ptr, this);
        return this;
    }
    /**
     * @param {number} pid
     * @returns {number}
     */
    pid_channel(pid) {
        const ret = wasm.mixerwasm_pid_channel(this.__wbg_ptr, pid);
        return ret;
    }
    /**
     * @param {number} pid
     * @returns {number}
     */
    pid_channel_count(pid) {
        const ret = wasm.mixerwasm_pid_channel_count(this.__wbg_ptr, pid);
        return ret >>> 0;
    }
    /**
     * @param {number} key
     * @returns {number}
     */
    pid_channel_count_keyed(key) {
        const ret = wasm.mixerwasm_pid_channel_count_keyed(this.__wbg_ptr, key);
        return ret >>> 0;
    }
    /**
     * @param {number} key
     * @returns {number}
     */
    pid_channel_keyed(key) {
        const ret = wasm.mixerwasm_pid_channel_keyed(this.__wbg_ptr, key);
        return ret;
    }
    /**
     * Process one block and return the interleaved stereo output.
     *
     * Thin wrapper over [`MixerWasm::process_block`] (the pure-Rust core,
     * also used by native tests) that copies the result into a fresh
     * `Float32Array` for JS.
     * @param {number} block_size
     * @returns {Float32Array}
     */
    process(block_size) {
        const ret = wasm.mixerwasm_process(this.__wbg_ptr, block_size);
        if (ret[2]) {
            throw takeFromExternrefTable0(ret[1]);
        }
        return takeFromExternrefTable0(ret[0]);
    }
    /**
     * Instantly recall scene `id`: every captured parameter is
     * reapplied through the SAME setter paths the JS surface uses, so
     * engine state, staged EQ/dynamics params and the derived mute/solo
     * state all stay consistent. Any in-progress cross-fade is dropped
     * (an instant recall is itself a scene change — the user takes
     * over). Unknown id → Err.
     * @param {number} id
     */
    recall_scene(id) {
        const ret = wasm.mixerwasm_recall_scene(this.__wbg_ptr, id);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * Recall scene `id` as a timed cross-fade over `fade_ms`: the
     * current console (snapshotted at call time) is the "from" state,
     * the stored scene the "to" state, and `process_block` interpolates
     * between them at block granularity (audio-rate, no timers or
     * threads — see `apply_scene_interp` for the per-parameter domains;
     * booleans snap at the half-way point).
     *
     * * Unknown id → Err (same as instant recall). `fade_ms < 0` (or
     *   NaN) → Err. `fade_ms == 0` delegates to instant `recall_scene`.
     * * Cancel-on-set: any scene-affecting setter called while the fade
     *   is running drops it immediately — the user takes over from the
     *   already-applied interpolation (nothing further is applied).
     *   Stream-state operations (PID mapping, PCM feeds, subscribe,
     *   limiter, tap) do NOT cancel: they aren't console state.
     * * Control-plane allocations happen HERE only (the two scene
     *   snapshots, plus HashSets pre-reserved so boolean snaps can
     *   never grow them on the audio thread); the per-block
     *   interpolation is allocation-free (pinned by alloc_test).
     * * Non-audio state snaps immediately: strip NAMES (String clones
     *   are control-plane-only work; the RT path never touches them).
     * * Replaces any fade already in progress (from-state = whatever
     *   the console holds at call time).
     * @param {number} id
     * @param {number} fade_ms
     */
    recall_scene_fade(id, fade_ms) {
        const ret = wasm.mixerwasm_recall_scene_fade(this.__wbg_ptr, id, fade_ms);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * Capture the current console state and store it under a fresh
     * scene id. Saving is read-only — it never disturbs audio or
     * control state. Returns the new id (ids start at 1).
     * @returns {number}
     */
    save_scene() {
        const ret = wasm.mixerwasm_save_scene(this.__wbg_ptr);
        return ret >>> 0;
    }
    /**
     * Number of stored scenes.
     * @returns {number}
     */
    scene_count() {
        const ret = wasm.mixerwasm_scene_count(this.__wbg_ptr);
        return ret >>> 0;
    }
    /**
     * Whether bus `bus` accumulates into the master mix (default true).
     * Independent of the bus's own published output
     * (`take_bus_output` still returns signal).
     * @param {number} bus
     * @param {boolean} on
     */
    set_bus_feeds_main(bus, on) {
        wasm.mixerwasm_set_bus_feeds_main(this.__wbg_ptr, bus, on);
    }
    /**
     * @param {number} bus
     * @param {number} gain
     */
    set_bus_gain(bus, gain) {
        wasm.mixerwasm_set_bus_gain(this.__wbg_ptr, bus, gain);
    }
    /**
     * @param {number} bus
     * @param {boolean} muted
     */
    set_bus_mute(bus, muted) {
        wasm.mixerwasm_set_bus_mute(this.__wbg_ptr, bus, muted);
    }
    /**
     * Assign bus `bus` slot `slot` to tap input channel `ch` (a parallel
     * RAW tap — `ch`'s own mute/fader/EQ/dynamics never affect the bus
     * path). Lazily creates the slot's engine channel / EQ / dynamics
     * (flat strip index 128 + bus*16 + slot).
     * @param {number} bus
     * @param {number} slot
     * @param {number} ch
     */
    set_bus_source(bus, slot, ch) {
        const ret = wasm.mixerwasm_set_bus_source(this.__wbg_ptr, bus, slot, ch);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {number} gain
     */
    set_channel_gain(ch, gain) {
        const ret = wasm.mixerwasm_set_channel_gain(this.__wbg_ptr, ch, gain);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {Float32Array} data
     */
    set_channel_input(ch, data) {
        const ret = wasm.mixerwasm_set_channel_input(this.__wbg_ptr, ch, data);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {number} gain_db
     */
    set_channel_input_gain(ch, gain_db) {
        const ret = wasm.mixerwasm_set_channel_input_gain(this.__wbg_ptr, ch, gain_db);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch_start
     * @param {Float32Array} data
     * @param {number} num_channels
     */
    set_channel_input_interleaved(ch_start, data, num_channels) {
        const ret = wasm.mixerwasm_set_channel_input_interleaved(this.__wbg_ptr, ch_start, data, num_channels);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * Include/exclude an input strip from the main-bus mix (strips
     * 0-127 only; other indices are ignored). Default true. Purely
     * removes the strip from the main engine's call list — the strip is
     * still staged, metered, tapped, and still feeds any bus slots
     * assigned to it.
     * @param {number} ch
     * @param {boolean} on
     */
    set_channel_main_assign(ch, on) {
        wasm.mixerwasm_set_channel_main_assign(this.__wbg_ptr, ch, on);
    }
    /**
     * @param {number} ch
     * @param {boolean} muted
     */
    set_channel_mute(ch, muted) {
        const ret = wasm.mixerwasm_set_channel_mute(this.__wbg_ptr, ch, muted);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {string} name
     */
    set_channel_name(ch, name) {
        const ptr0 = passStringToWasm0(name, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
        const len0 = WASM_VECTOR_LEN;
        const ret = wasm.mixerwasm_set_channel_name(this.__wbg_ptr, ch, ptr0, len0);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {number} pan
     */
    set_channel_pan(ch, pan) {
        const ret = wasm.mixerwasm_set_channel_pan(this.__wbg_ptr, ch, pan);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {number} law
     */
    set_channel_pan_law(ch, law) {
        const ret = wasm.mixerwasm_set_channel_pan_law(this.__wbg_ptr, ch, law);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {boolean} inverted
     */
    set_channel_phase(ch, inverted) {
        const ret = wasm.mixerwasm_set_channel_phase(this.__wbg_ptr, ch, inverted);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {boolean} soloed
     */
    set_channel_solo(ch, soloed) {
        const ret = wasm.mixerwasm_set_channel_solo(this.__wbg_ptr, ch, soloed);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * Enable the per-channel direct-out tap: during `process()`, channels
     * `0..channels` are captured MONO at the pan-stage input — post input
     * gain and phase inversion, post gate/comp/EQ chain, post fader gain,
     * PRE pan (pan is a stereo-bus concept; direct outs are mono per
     * channel). Drain the captured block with `take_channel_tap()`.
     *
     * * `channels = 0` (or never calling this) disables the tap. Clamped
     *   to 0..=128; slot channels (128-255, bus slots) are never tapped.
     * * Idempotent; re-enabling with a different N resizes the accumulator.
     * * Muted channels tap SILENCE, and solo gating applies exactly as it
     *   does to the mix: when any channel is soloed, non-soloed channels
     *   are silent in the tap too (a muted/solo-gated channel produces no
     *   output anywhere, direct out included).
     * * Channels with no input data contribute zeros.
     * * `process()` output is identical whether the tap is on or off.
     * @param {number} channels
     */
    set_channel_tap(channels) {
        wasm.mixerwasm_set_channel_tap(this.__wbg_ptr, channels);
    }
    /**
     * @param {number} ch
     * @param {number} param
     * @param {number} value
     */
    set_comp_param(ch, param, value) {
        const ret = wasm.mixerwasm_set_comp_param(this.__wbg_ptr, ch, param, value);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {number} band
     * @param {number} freq_hz
     */
    set_eq_band_freq(ch, band, freq_hz) {
        const ret = wasm.mixerwasm_set_eq_band_freq(this.__wbg_ptr, ch, band, freq_hz);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {number} band
     * @param {number} gain_db
     */
    set_eq_band_gain(ch, band, gain_db) {
        const ret = wasm.mixerwasm_set_eq_band_gain(this.__wbg_ptr, ch, band, gain_db);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {number} band
     * @param {number} q
     */
    set_eq_band_q(ch, band, q) {
        const ret = wasm.mixerwasm_set_eq_band_q(this.__wbg_ptr, ch, band, q);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {boolean} bypassed
     */
    set_eq_bypass(ch, bypassed) {
        const ret = wasm.mixerwasm_set_eq_bypass(this.__wbg_ptr, ch, bypassed);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {number} param
     * @param {number} value
     */
    set_expander_param(ch, param, value) {
        const ret = wasm.mixerwasm_set_expander_param(this.__wbg_ptr, ch, param, value);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * @param {number} ch
     * @param {number} param
     * @param {number} value
     */
    set_gate_param(ch, param, value) {
        const ret = wasm.mixerwasm_set_gate_param(this.__wbg_ptr, ch, param, value);
        if (ret[1]) {
            throw takeFromExternrefTable0(ret[0]);
        }
    }
    /**
     * Live-update the limiter ceiling. Assigns `threshold_db` on both L/R
     * limiters and calls `recalculate()`, which recomputes only the
     * derived coefficients — `gain_env`, look-ahead delay and oversample
     * state survive, so turning the knob mid-stream is click-free
     * (the previous reconstruct-via-`new()` reset the envelope, causing
     * an audible gain jump).
     * @param {number} ceiling_db
     */
    set_limiter_ceiling(ceiling_db) {
        wasm.mixerwasm_set_limiter_ceiling(this.__wbg_ptr, ceiling_db);
    }
    /**
     * @param {boolean} enabled
     */
    set_limiter_enabled(enabled) {
        wasm.mixerwasm_set_limiter_enabled(this.__wbg_ptr, enabled);
    }
    /**
     * Live-update the limiter release. Same rationale as
     * `set_limiter_ceiling`: `recalculate()` preserves the gain envelope,
     * so release changes never reset limiting mid-stream.
     * @param {number} release_ms
     */
    set_limiter_release(release_ms) {
        wasm.mixerwasm_set_limiter_release(this.__wbg_ptr, release_ms);
    }
    /**
     * @param {number} gain
     */
    set_master_gain(gain) {
        wasm.mixerwasm_set_master_gain(this.__wbg_ptr, gain);
    }
    /**
     * Channel-blocks that drained an empty FIFO (starvation events).
     * @returns {bigint}
     */
    starved_blocks() {
        const ret = wasm.mixerwasm_starved_blocks(this.__wbg_ptr);
        return BigInt.asUintN(64, ret);
    }
    /**
     * @param {number} pid
     */
    subscribe_pid(pid) {
        wasm.mixerwasm_subscribe_pid(this.__wbg_ptr, pid);
    }
    /**
     * @param {number} key
     */
    subscribe_pid_keyed(key) {
        wasm.mixerwasm_subscribe_pid_keyed(this.__wbg_ptr, key);
    }
    /**
     * Drain bus `bus`'s own stereo output from the most recent
     * `process()` call: one block of bs frames, interleaved L/R, post
     * bus-gain (a muted bus publishes silence). Per-bus drain contract
     * matching `take_channel_tap`:
     *
     * * Empty Float32Array when the bus index is invalid (≥ 8) or no
     *   new block has been processed since the last take of that bus.
     * * Taking bus A does not consume bus B's block; if two `process()`
     *   calls happen without a take in between, only the LATEST block
     *   is kept.
     * @param {number} bus
     * @returns {Float32Array}
     */
    take_bus_output(bus) {
        const ret = wasm.mixerwasm_take_bus_output(this.__wbg_ptr, bus);
        return ret;
    }
    /**
     * Drain the channel direct-out tap captured by the last `process()`
     * call: one block of `bs` frames × N channels, interleaved per frame
     * (frame i: ch0[i], ch1[i], ..., chN-1[i]). Empties the accumulator —
     * call once per processed block.
     *
     * Returns an empty Float32Array when the tap is disabled or no block
     * has been processed since the last take. If two `process()` calls
     * happen without a take in between, only the LATEST block is kept.
     * @returns {Float32Array}
     */
    take_channel_tap() {
        const ret = wasm.mixerwasm_take_channel_tap(this.__wbg_ptr);
        return ret;
    }
    /**
     * @param {number} pid
     */
    unmap_pid(pid) {
        wasm.mixerwasm_unmap_pid(this.__wbg_ptr, pid);
    }
    /**
     * @param {number} key
     */
    unmap_pid_keyed(key) {
        wasm.mixerwasm_unmap_pid_keyed(this.__wbg_ptr, key);
    }
    /**
     * Count of PCM packets dropped due to unmapped PID (for diagnostics).
     * @returns {bigint}
     */
    unmapped_pid_count() {
        const ret = wasm.mixerwasm_unmapped_pid_count(this.__wbg_ptr);
        return BigInt.asUintN(64, ret);
    }
    /**
     * @param {number} pid
     */
    unsubscribe_pid(pid) {
        wasm.mixerwasm_unsubscribe_pid(this.__wbg_ptr, pid);
    }
    /**
     * @param {number} key
     */
    unsubscribe_pid_keyed(key) {
        wasm.mixerwasm_unsubscribe_pid_keyed(this.__wbg_ptr, key);
    }
}
if (Symbol.dispose) MixerWasm.prototype[Symbol.dispose] = MixerWasm.prototype.free;
function __wbg_get_imports() {
    const import0 = {
        __proto__: null,
        __wbg___wbindgen_throw_bb96b2010945f0bc: function(arg0, arg1) {
            throw new Error(getStringFromWasm0(arg0, arg1));
        },
        __wbg_error_757e9472f8410341: function(arg0, arg1) {
            let deferred0_0;
            let deferred0_1;
            try {
                deferred0_0 = arg0;
                deferred0_1 = arg1;
                console.error(getStringFromWasm0(arg0, arg1));
            } finally {
                wasm.__wbindgen_free(deferred0_0, deferred0_1, 1);
            }
        },
        __wbg_getRandomValues_e446ea5ffdd14ee5: function() { return handleError(function (arg0, arg1) {
            globalThis.crypto.getRandomValues(getArrayU8FromWasm0(arg0, arg1));
        }, arguments); },
        __wbg_length_1009454859bb3e03: function(arg0) {
            const ret = arg0.length;
            return ret;
        },
        __wbg_new_227d7c05414eb861: function() {
            const ret = new Error();
            return ret;
        },
        __wbg_new_with_length_ef112d2291d8ab95: function(arg0) {
            const ret = new Float32Array(arg0 >>> 0);
            return ret;
        },
        __wbg_prototypesetcall_10722f4fde830f07: function(arg0, arg1, arg2) {
            Float32Array.prototype.set.call(getArrayF32FromWasm0(arg0, arg1), arg2);
        },
        __wbg_set_577f5f7485b6744e: function(arg0, arg1, arg2) {
            arg0.set(getArrayF32FromWasm0(arg1, arg2));
        },
        __wbg_stack_3b0d974bbf31e44f: function(arg0, arg1) {
            const ret = arg1.stack;
            const ptr1 = passStringToWasm0(ret, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
            const len1 = WASM_VECTOR_LEN;
            getDataViewMemory0().setInt32(arg0 + 4 * 1, len1, true);
            getDataViewMemory0().setInt32(arg0 + 4 * 0, ptr1, true);
        },
        __wbindgen_cast_0000000000000001: function(arg0, arg1) {
            // Cast intrinsic for `Ref(String) -> Externref`.
            const ret = getStringFromWasm0(arg0, arg1);
            return ret;
        },
        __wbindgen_init_externref_table: function() {
            const table = wasm.__wbindgen_externrefs;
            const offset = table.grow(4);
            table.set(0, undefined);
            table.set(offset + 0, undefined);
            table.set(offset + 1, null);
            table.set(offset + 2, true);
            table.set(offset + 3, false);
        },
    };
    return {
        __proto__: null,
        "./mixer_wasm_bg.js": import0,
    };
}

const MixerWasmFinalization = (typeof FinalizationRegistry === 'undefined')
    ? { register: () => {}, unregister: () => {} }
    : new FinalizationRegistry(ptr => wasm.__wbg_mixerwasm_free(ptr, 1));

function addToExternrefTable0(obj) {
    const idx = wasm.__externref_table_alloc();
    wasm.__wbindgen_externrefs.set(idx, obj);
    return idx;
}

function getArrayF32FromWasm0(ptr, len) {
    ptr = ptr >>> 0;
    return getFloat32ArrayMemory0().subarray(ptr / 4, ptr / 4 + len);
}

function getArrayU8FromWasm0(ptr, len) {
    ptr = ptr >>> 0;
    return getUint8ArrayMemory0().subarray(ptr / 1, ptr / 1 + len);
}

let cachedDataViewMemory0 = null;
function getDataViewMemory0() {
    if (cachedDataViewMemory0 === null || cachedDataViewMemory0.buffer.detached === true || (cachedDataViewMemory0.buffer.detached === undefined && cachedDataViewMemory0.buffer !== wasm.memory.buffer)) {
        cachedDataViewMemory0 = new DataView(wasm.memory.buffer);
    }
    return cachedDataViewMemory0;
}

let cachedFloat32ArrayMemory0 = null;
function getFloat32ArrayMemory0() {
    if (cachedFloat32ArrayMemory0 === null || cachedFloat32ArrayMemory0.byteLength === 0) {
        cachedFloat32ArrayMemory0 = new Float32Array(wasm.memory.buffer);
    }
    return cachedFloat32ArrayMemory0;
}

function getStringFromWasm0(ptr, len) {
    return decodeText(ptr >>> 0, len);
}

let cachedUint8ArrayMemory0 = null;
function getUint8ArrayMemory0() {
    if (cachedUint8ArrayMemory0 === null || cachedUint8ArrayMemory0.byteLength === 0) {
        cachedUint8ArrayMemory0 = new Uint8Array(wasm.memory.buffer);
    }
    return cachedUint8ArrayMemory0;
}

function handleError(f, args) {
    try {
        return f.apply(this, args);
    } catch (e) {
        const idx = addToExternrefTable0(e);
        wasm.__wbindgen_exn_store(idx);
    }
}

function passArrayF32ToWasm0(arg, malloc) {
    const ptr = malloc(arg.length * 4, 4) >>> 0;
    getFloat32ArrayMemory0().set(arg, ptr / 4);
    WASM_VECTOR_LEN = arg.length;
    return ptr;
}

function passStringToWasm0(arg, malloc, realloc) {
    if (realloc === undefined) {
        const buf = cachedTextEncoder.encode(arg);
        const ptr = malloc(buf.length, 1) >>> 0;
        getUint8ArrayMemory0().subarray(ptr, ptr + buf.length).set(buf);
        WASM_VECTOR_LEN = buf.length;
        return ptr;
    }

    let len = arg.length;
    let ptr = malloc(len, 1) >>> 0;

    const mem = getUint8ArrayMemory0();

    let offset = 0;

    for (; offset < len; offset++) {
        const code = arg.charCodeAt(offset);
        if (code > 0x7F) break;
        mem[ptr + offset] = code;
    }
    if (offset !== len) {
        if (offset !== 0) {
            arg = arg.slice(offset);
        }
        ptr = realloc(ptr, len, len = offset + arg.length * 3, 1) >>> 0;
        const view = getUint8ArrayMemory0().subarray(ptr + offset, ptr + len);
        const ret = cachedTextEncoder.encodeInto(arg, view);

        offset += ret.written;
        ptr = realloc(ptr, len, offset, 1) >>> 0;
    }

    WASM_VECTOR_LEN = offset;
    return ptr;
}

function takeFromExternrefTable0(idx) {
    const value = wasm.__wbindgen_externrefs.get(idx);
    wasm.__externref_table_dealloc(idx);
    return value;
}

let cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
cachedTextDecoder.decode();
const MAX_SAFARI_DECODE_BYTES = 2146435072;
let numBytesDecoded = 0;
function decodeText(ptr, len) {
    numBytesDecoded += len;
    if (numBytesDecoded >= MAX_SAFARI_DECODE_BYTES) {
        cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
        cachedTextDecoder.decode();
        numBytesDecoded = len;
    }
    return cachedTextDecoder.decode(getUint8ArrayMemory0().subarray(ptr, ptr + len));
}

const cachedTextEncoder = new TextEncoder();

if (!('encodeInto' in cachedTextEncoder)) {
    cachedTextEncoder.encodeInto = function (arg, view) {
        const buf = cachedTextEncoder.encode(arg);
        view.set(buf);
        return {
            read: arg.length,
            written: buf.length
        };
    };
}

let WASM_VECTOR_LEN = 0;

let wasmModule, wasmInstance, wasm;
function __wbg_finalize_init(instance, module) {
    wasmInstance = instance;
    wasm = instance.exports;
    wasmModule = module;
    cachedDataViewMemory0 = null;
    cachedFloat32ArrayMemory0 = null;
    cachedUint8ArrayMemory0 = null;
    wasm.__wbindgen_start();
    return wasm;
}

async function __wbg_load(module, imports) {
    if (typeof Response === 'function' && module instanceof Response) {
        if (!module.ok) {
            throw new Error(`failed to fetch Wasm: ${module.status} ${module.statusText} fetching '${module.url}'`);
        }

        if (typeof WebAssembly.instantiateStreaming === 'function') {
            try {
                return await WebAssembly.instantiateStreaming(module, imports);
            } catch (e) {
                const validResponse = expectedResponseType(module.type);

                if (validResponse && module.headers.get('Content-Type') !== 'application/wasm') {
                    console.warn("`WebAssembly.instantiateStreaming` failed because your server does not serve Wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\n", e);

                } else { throw e; }
            }
        }

        const bytes = await module.arrayBuffer();
        return await WebAssembly.instantiate(bytes, imports);
    } else {
        const instance = await WebAssembly.instantiate(module, imports);

        if (instance instanceof WebAssembly.Instance) {
            return { instance, module };
        } else {
            return instance;
        }
    }

    function expectedResponseType(type) {
        switch (type) {
            case 'basic': case 'cors': case 'default': return true;
        }
        return false;
    }
}

function initSync(module) {
    if (wasm !== undefined) return wasm;


    if (module !== undefined) {
        if (Object.getPrototypeOf(module) === Object.prototype) {
            ({module} = module)
        } else {
            console.warn('using deprecated parameters for `initSync()`; pass a single object instead')
        }
    }

    const imports = __wbg_get_imports();
    if (!(module instanceof WebAssembly.Module)) {
        module = new WebAssembly.Module(module);
    }
    const instance = new WebAssembly.Instance(module, imports);
    return __wbg_finalize_init(instance, module);
}

async function __wbg_init(module_or_path) {
    if (wasm !== undefined) return wasm;


    if (module_or_path !== undefined) {
        if (Object.getPrototypeOf(module_or_path) === Object.prototype) {
            ({module_or_path} = module_or_path)
        } else {
            console.warn('using deprecated parameters for the initialization function; pass a single object instead')
        }
    }

    if (module_or_path === undefined) {
        module_or_path = undefined; // stripped for worklet
    }
    const imports = __wbg_get_imports();

    if (typeof module_or_path === 'string' || (typeof Request === 'function' && module_or_path instanceof Request) || (typeof URL === 'function' && module_or_path instanceof URL)) {
        module_or_path = fetch(module_or_path);
    }

    const { instance, module } = await __wbg_load(await module_or_path, imports);

    return __wbg_finalize_init(instance, module);
}


__cmxInitSync = initSync;
__cmxMixerWasm = MixerWasm;
})();
