/**
 * Guitarix FX param tables (OctOBX per-instance insert chains).
 *
 * AUTO-GENERATED by tools/gen-gxfx-params.mjs — DO NOT EDIT THIS FILE BY
 * HAND. Param data sources: the v1 eleven are pinned in
 * tools/gxfx-param-spec.json (hand-verified labels/values); new effects
 * are parsed from the guitarix bundle ttl files + orphan .cc connect
 * comments (third_party/guitarix, pinned submodule).
 * Cross-checked against the C engine by test/gxfx-params.test.ts +
 * verify-obxd-wasm.mjs.
 *
 * Regenerate with:    node tools/gen-gxfx-params.mjs
 * Freshness check:    node tools/gen-gxfx-params.mjs --check   (CI gate)
 */

export const FX_COUNT = 81;
export const FX_SLOTS = 11;
export const FX_INSTANCE_COUNT = 10;
export const FX_SLOT_PARAMS = 48;

export interface FxParamDef {
    port: number;      // PortIndex value passed to fx_set_param's `param`
    symbol: string;
    name: string;
    default: number;   // ENGINE units (ttl range, not 0..1)
    min: number;
    max: number;
    step: number;
    integer?: boolean;
}

/** Menu category (full fx v2 vocabulary). */
export type FxCategory =
    | "wah" | "drive" | "eq" | "filter" | "dynamics" | "modulation"
    | "delay" | "reverb" | "amp" | "tonestack" | "multiband" | "special" | "utility";

export interface FxEffectDef {
    id: number;
    key: string;       // 'wah' | 'overdrive' | ... (manifest order = generator id order)
    label: string;
    category: FxCategory;
    stereo: boolean;
    offset: number;    // cumulative param offset into the flat 479-slot mirror
    params: FxParamDef[];
}

/** Effect catalog in id order (generator manifest). The canonical default
 * chain is ids 0..10 (wah → overdrive → distortion → compressor → chorus →
 * flanger → phaser → tremolo → delay → echo → reverb); ids 11+ are the
 * Phase-1 additions selectable per slot.
 * Param counts 2,1,3,5,4,6,3,4,7,7,5,2,4,3,3,2,3,3,2,2,2,2,2,1,1,1,5,2,11,30,5,2,6,1,5,3,0,1,8,5,5,8,10,7,3,5,8,8,8,10,10,8,5,3,3,2,2,11,3,5,12,6,4,12,5,2,34,19,15,14,24,3,1,1,1,7,4,9,4,4,10 → offsets 0,2,3,6,11,15,21,24,28,35,42,47,49,53,56,59,61,64,67,69,71,73,75,77,78,79,80,85,87,98,128,133,135,141,142,147,150,150,151,159,164,169,177,187,194,197,202,210,218,226,236,246,254,259,262,265,267,269,280,283,288,300,306,310,322,327,329,363,382,397,411,435,438,439,440,441,448,452,461,465,469. */
export const FX_EFFECTS: FxEffectDef[] = [
    {
        id: 0, key: "wah", label: "Wah", category: "wah", stereo: false, offset: 0,
        params: [
            { port: 2, symbol: "VOLUME", name: "Volume", default: 0, min: -20, max: 4, step: 0.1 },
            { port: 3, symbol: "HOTPOTZ", name: "Wah", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 1, key: "overdrive", label: "Overdrive", category: "drive", stereo: false, offset: 2,
        params: [
            { port: 2, symbol: "SCREAM", name: "Scream", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 2, key: "distortion", label: "Distortion", category: "drive", stereo: false, offset: 3,
        params: [
            { port: 2, symbol: "LEVEL", name: "Level", default: -2, min: -20, max: 12, step: 0.1 },
            { port: 3, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "DRIVE", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 3, key: "compressor", label: "Compressor", category: "dynamics", stereo: false, offset: 6,
        params: [
            { port: 0, symbol: "RATIO", name: "Ratio", default: 2, min: 1, max: 20, step: 0.1 },
            { port: 1, symbol: "KNEE", name: "Knee", default: 3, min: 0, max: 20, step: 0.1 },
            { port: 2, symbol: "THRESHOLD", name: "Threshold", default: -20, min: -96, max: 10, step: 0.1 },
            { port: 3, symbol: "RELEASE", name: "Release", default: 0.5, min: 0, max: 10, step: 0.01 },
            { port: 4, symbol: "ATTACK", name: "Attack", default: 0.002, min: 0, max: 1, step: 0.001 },
        ],
    },
    {
        id: 4, key: "chorus", label: "Chorus", category: "modulation", stereo: true, offset: 11,
        params: [
            { port: 0, symbol: "level", name: "Level", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "delay", name: "Delay", default: 0.02, min: 0, max: 0.2, step: 0.01 },
            { port: 2, symbol: "depth", name: "Depth", default: 0.02, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "freq", name: "Freq", default: 3, min: 0.1, max: 10, step: 0.01 },
        ],
    },
    {
        id: 5, key: "flanger", label: "Flanger", category: "modulation", stereo: false, offset: 15,
        params: [
            { port: 0, symbol: "depth", name: "Depth", default: 0.5, min: 0, max: 5, step: 0.01 },
            { port: 1, symbol: "width", name: "Width", default: 5, min: 0, max: 10, step: 0.01 },
            { port: 2, symbol: "freq", name: "Freq", default: 0.2, min: 0.05, max: 10, step: 1.06 },
            { port: 3, symbol: "feedback", name: "Feedback", default: -0.707, min: -0.99, max: 0.99, step: 0.01 },
            { port: 4, symbol: "dry_wet", name: "Wet", default: 100, min: 0, max: 100, step: 1 },
            { port: 5, symbol: "mix", name: "Mix", default: 0, min: -1, max: 1, step: 0.1 },
        ],
    },
    {
        id: 6, key: "phaser", label: "Phaser", category: "modulation", stereo: false, offset: 21,
        params: [
            { port: 0, symbol: "dry_wet", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
            { port: 1, symbol: "level", name: "Level", default: 0, min: -60, max: 10, step: 0.1 },
            { port: 2, symbol: "speed", name: "Speed", default: 0.5, min: 0, max: 10, step: 0.01 },
        ],
    },
    {
        id: 7, key: "tremolo", label: "Tremolo", category: "modulation", stereo: false, offset: 24,
        params: [
            { port: 0, symbol: "dry_wet", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
            { port: 1, symbol: "mode", name: "Mode", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 2, symbol: "depth", name: "Depth", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "freq", name: "Freq", default: 5, min: 0.1, max: 50, step: 0.1 },
        ],
    },
    {
        id: 8, key: "delay", label: "Delay", category: "delay", stereo: true, offset: 28,
        params: [
            { port: 0, symbol: "mode", name: "Mode", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 1, symbol: "level_r", name: "R Level", default: -10, min: -20, max: 20, step: 0.1 },
            { port: 2, symbol: "timt_r", name: "R Time", default: 1000, min: 1, max: 5000, step: 10 },
            { port: 3, symbol: "level_l", name: "L Level", default: -10, min: -20, max: 20, step: 0.1 },
            { port: 4, symbol: "timt_l", name: "L Time", default: 1000, min: 1, max: 5000, step: 10 },
            { port: 5, symbol: "lfo", name: "LFO", default: 0.2, min: 0.2, max: 5, step: 0.01 },
            { port: 6, symbol: "link", name: "Link (L+R)", default: 0, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 9, key: "echo", label: "Echo", category: "delay", stereo: true, offset: 35,
        params: [
            { port: 0, symbol: "mode", name: "Mode", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 1, symbol: "level_r", name: "R Level", default: 30, min: 0, max: 100, step: 0.1 },
            { port: 2, symbol: "timt_r", name: "R Time", default: 100, min: 1, max: 2000, step: 1 },
            { port: 3, symbol: "level_l", name: "L Level", default: 30, min: 0, max: 100, step: 0.1 },
            { port: 4, symbol: "timt_l", name: "L Time", default: 100, min: 1, max: 2000, step: 1 },
            { port: 5, symbol: "lfo", name: "LFO", default: 0.2, min: 0.2, max: 5, step: 0.01 },
            { port: 6, symbol: "link", name: "Link (L+R)", default: 0, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 10, key: "reverb", label: "Reverb", category: "reverb", stereo: true, offset: 42,
        params: [
            { port: 0, symbol: "dry_wet", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
            { port: 1, symbol: "lfo", name: "LFO", default: 0.2, min: 0.2, max: 5, step: 0.01 },
            { port: 2, symbol: "roomsize", name: "Roomsize", default: 0.5, min: 0, max: 1, step: 0.025 },
            { port: 3, symbol: "damp", name: "Damp", default: 0.2, min: 0, max: 1, step: 0.025 },
            { port: 4, symbol: "mode", name: "Mode", default: 0, min: 0, max: 1, step: 1, integer: true },
        ],
    },
    {
        id: 11, key: "fuzzface", label: "Fuzz Face", category: "drive", stereo: false, offset: 47,
        params: [
            { port: 2, symbol: "FUZZ", name: "Fuzz", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "LEVEL", name: "Level", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 12, key: "fuzzfacefm", label: "Fuzz Face FM", category: "drive", stereo: false, offset: 49,
        params: [
            { port: 2, symbol: "DRIVE", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "FUZZ", name: "Fuzz", default: 0.5, min: 0, max: 0.99, step: 0.01 },
            { port: 4, symbol: "INPUT", name: "Input", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 5, symbol: "LEVEL", name: "Level", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 13, key: "fumaster", label: "Fuzz Master", category: "drive", stereo: false, offset: 53,
        params: [
            { port: 2, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "VOLUME", name: "Volume", default: 0.1, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 14, key: "hornet", label: "Hornet", category: "drive", stereo: false, offset: 56,
        params: [
            { port: 2, symbol: "FUZZ", name: "Fuzz", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "SUSTAIN", name: "Sustain", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 15, key: "muff", label: "Muff", category: "drive", stereo: false, offset: 59,
        params: [
            { port: 2, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 16, key: "cstb", label: "Tone Bender", category: "drive", stereo: false, offset: 61,
        params: [
            { port: 2, symbol: "ATTACK", name: "Attack", default: 0.5, min: 0, max: 0.95, step: 0.01 },
            { port: 3, symbol: "LEVEL", name: "Level", default: 0.2, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "WET_DRY", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 17, key: "aclipper", label: "Rat", category: "drive", stereo: false, offset: 64,
        params: [
            { port: 2, symbol: "DRIVE", name: "Drive", default: 0.3, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "LEVEL", name: "Level", default: -7, min: -20, max: 12, step: 1 },
            { port: 4, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 18, key: "mxrdist", label: "MXR Distortion", category: "drive", stereo: false, offset: 67,
        params: [
            { port: 2, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "DRIVE", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 19, key: "rangem", label: "Range Master", category: "drive", stereo: false, offset: 69,
        params: [
            { port: 2, symbol: "BOOST", name: "Boost", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 20, key: "mole", label: "Mole", category: "drive", stereo: false, offset: 71,
        params: [
            { port: 2, symbol: "BOOST", name: "Boost", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 21, key: "hfb", label: "HF Brightener", category: "drive", stereo: false, offset: 73,
        params: [
            { port: 2, symbol: "INTENSITY", name: "Intensity", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 22, key: "hogsfoot", label: "Hogs Foot", category: "drive", stereo: false, offset: 75,
        params: [
            { port: 2, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 23, key: "softclip", label: "Softclip", category: "drive", stereo: false, offset: 77,
        params: [
            { port: 0, symbol: "FUZZ", name: "Fuzz", default: 0, min: 0, max: 1.99, step: 0.01 },
        ],
    },
    {
        id: 24, key: "bassbooster", label: "Bass Booster", category: "drive", stereo: false, offset: 78,
        params: [
            { port: 0, symbol: "LEVEL", name: "Level", default: 10, min: 0.5, max: 20, step: 0.5 },
        ],
    },
    {
        id: 25, key: "highbooster", label: "High Booster", category: "drive", stereo: false, offset: 79,
        params: [
            { port: 0, symbol: "LEVEL", name: "Level", default: 0.5, min: 0, max: 20, step: 0.5 },
        ],
    },
    {
        id: 26, key: "expander", label: "Expander", category: "dynamics", stereo: false, offset: 80,
        params: [
            { port: 0, symbol: "RATIO", name: "Ratio", default: 2, min: 1, max: 20, step: 0.1 },
            { port: 1, symbol: "KNEE", name: "Knee", default: 3, min: 0, max: 20, step: 0.1 },
            { port: 2, symbol: "THRESHOLD", name: "Threshold", default: -40, min: -96, max: 10, step: 1 },
            { port: 3, symbol: "RELEASE", name: "Release", default: 0.1, min: 0, max: 10, step: 0.1 },
            { port: 4, symbol: "ATTACK", name: "Attack", default: 0.001, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 27, key: "susta", label: "Sustainer", category: "dynamics", stereo: false, offset: 85,
        params: [
            { port: 2, symbol: "SUSTAIN", name: "Sustain", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 28, key: "graphiceq", label: "Graphic EQ", category: "eq", stereo: false, offset: 87,
        params: [
            { port: 0, symbol: "G1", name: "G1", default: 0, min: -30, max: 20, step: 1 },
            { port: 1, symbol: "G2", name: "G2", default: 0, min: -30, max: 20, step: 1 },
            { port: 2, symbol: "G3", name: "G3", default: 0, min: -30, max: 20, step: 1 },
            { port: 3, symbol: "G4", name: "G4", default: 0, min: -30, max: 20, step: 1 },
            { port: 4, symbol: "G5", name: "G5", default: 0, min: -30, max: 20, step: 1 },
            { port: 5, symbol: "G6", name: "G6", default: 0, min: -30, max: 20, step: 1 },
            { port: 6, symbol: "G7", name: "G7", default: 0, min: -30, max: 20, step: 1 },
            { port: 7, symbol: "G8", name: "G8", default: 0, min: -30, max: 20, step: 1 },
            { port: 8, symbol: "G9", name: "G9", default: 0, min: -30, max: 20, step: 1 },
            { port: 9, symbol: "G10", name: "G10", default: 0, min: -30, max: 20, step: 1 },
            { port: 10, symbol: "G11", name: "G11", default: 0, min: -30, max: 20, step: 1 },
        ],
    },
    {
        id: 29, key: "selecteq", label: "Scaleable EQ", category: "eq", stereo: false, offset: 98,
        params: [
            { port: 0, symbol: "QS125", name: "Q 125", default: 50, min: 1, max: 100, step: 1 },
            { port: 1, symbol: "QS16K", name: "Q 16k", default: 50, min: 1, max: 100, step: 1 },
            { port: 2, symbol: "QS1K", name: "Q 1k", default: 50, min: 1, max: 100, step: 1 },
            { port: 3, symbol: "QS250", name: "Q 250", default: 50, min: 1, max: 100, step: 1 },
            { port: 4, symbol: "QS2K", name: "Q 2k", default: 50, min: 1, max: 100, step: 1 },
            { port: 5, symbol: "QS31_25", name: "Q 31.25", default: 50, min: 1, max: 100, step: 1 },
            { port: 6, symbol: "QS4K", name: "Q 4k", default: 50, min: 1, max: 100, step: 1 },
            { port: 7, symbol: "QS500", name: "Q 500", default: 50, min: 1, max: 100, step: 1 },
            { port: 8, symbol: "QS62_5", name: "Q 62.5", default: 50, min: 1, max: 100, step: 1 },
            { port: 9, symbol: "QS8K", name: "Q 8k", default: 50, min: 1, max: 100, step: 1 },
            { port: 10, symbol: "FREQ125", name: "Freq 125", default: 125, min: 20, max: 20000, step: 1 },
            { port: 11, symbol: "FREQ16K", name: "Freq 16k", default: 16000, min: 20, max: 20000, step: 1 },
            { port: 12, symbol: "FREQ1K", name: "Freq 1k", default: 1000, min: 20, max: 20000, step: 1 },
            { port: 13, symbol: "FREQ250", name: "Freq 250", default: 250, min: 20, max: 20000, step: 1 },
            { port: 14, symbol: "FREQ2K", name: "Freq 2k", default: 2000, min: 20, max: 20000, step: 1 },
            { port: 15, symbol: "FREQ31_25", name: "Freq 31.25", default: 31, min: 20, max: 20000, step: 1 },
            { port: 16, symbol: "FREQ4K", name: "Freq 4k", default: 4000, min: 20, max: 20000, step: 1 },
            { port: 17, symbol: "FREQ500", name: "Freq 500", default: 500, min: 20, max: 20000, step: 1 },
            { port: 18, symbol: "FREQ62_5", name: "Freq 62.5", default: 62, min: 20, max: 20000, step: 1 },
            { port: 19, symbol: "FREQ8K", name: "Freq 8k", default: 8000, min: 20, max: 20000, step: 1 },
            { port: 20, symbol: "FS125", name: "Gain 125", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 21, symbol: "FS16K", name: "Gain 16k", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 22, symbol: "FS1K", name: "Gain 1k", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 23, symbol: "FS250", name: "Gain 250", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 24, symbol: "FS2K", name: "Gain 2k", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 25, symbol: "FS31_25", name: "Gain 31.25", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 26, symbol: "FS4K", name: "Gain 4k", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 27, symbol: "FS500", name: "Gain 500", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 28, symbol: "FS62_5", name: "Gain 62.5", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 29, symbol: "FS8K", name: "Gain 8k", default: 0, min: -50, max: 10, step: 0.1 },
        ],
    },
    {
        id: 30, key: "tonecontroll", label: "3 Band EQ", category: "eq", stereo: true, offset: 128,
        params: [
            { port: 0, symbol: "BASS", name: "Bass", default: 0, min: -5, max: 5, step: 0.01 },
            { port: 1, symbol: "MIDDLE", name: "Middle", default: 0, min: -5, max: 5, step: 0.01 },
            { port: 2, symbol: "ON", name: "On", default: 0, min: 0, max: 1, step: 1 },
            { port: 3, symbol: "TREBLE", name: "Treble", default: 0, min: -5, max: 5, step: 0.01 },
            { port: 4, symbol: "SHARPER", name: "Sharper", default: -2, min: -2.5, max: 5, step: 0.1 },
        ],
    },
    {
        id: 31, key: "moog", label: "Moog Filter", category: "eq", stereo: true, offset: 133,
        params: [
            { port: 0, symbol: "Q", name: "Q", default: 1, min: 0, max: 4, step: 0.1 },
            { port: 1, symbol: "FR", name: "Frequency", default: 3000, min: 440, max: 6000, step: 10 },
        ],
    },
    {
        id: 32, key: "low_high_pass", label: "Low/High Filter", category: "eq", stereo: false, offset: 135,
        params: [
            { port: 0, symbol: "HIGHFREQ", name: "BP High Freq", default: 5000, min: 1000, max: 12000, step: 10 },
            { port: 1, symbol: "LOWFREQ", name: "BP Low Freq", default: 130, min: 20, max: 1000, step: 10 },
            { port: 2, symbol: "ONOFF", name: "BP On/Off", default: 0, min: 0, max: 1, step: 1 },
            { port: 3, symbol: "HIGH_FREQ", name: "HP Freq", default: 130, min: 20, max: 7040, step: 10 },
            { port: 4, symbol: "LOW_FREQ", name: "LP Freq", default: 5000, min: 20, max: 12000, step: 10 },
            { port: 5, symbol: "ON_OFF", name: "LP/HP On/Off", default: 0, min: 0, max: 1, step: 1 },
        ],
    },
    {
        id: 33, key: "noise_shaper", label: "Noise Shaper", category: "eq", stereo: false, offset: 141,
        params: [
            { port: 0, symbol: "SHARPER", name: "Sharper", default: 1, min: 1, max: 10, step: 1 },
        ],
    },
    {
        id: 34, key: "wahmodel", label: "Wah Model", category: "wah", stereo: false, offset: 142,
        params: [
            { port: 2, symbol: "WAH", name: "Wah", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "FREQ", name: "Freq", default: 24, min: 24, max: 360, step: 10 },
            { port: 4, symbol: "MODE", name: "Mode", default: 0, min: 0, max: 2, step: 1, integer: true },
            { port: 5, symbol: "MODEL", name: "Model", default: 0, min: 0, max: 6, step: 1, integer: true },
            { port: 6, symbol: "WET_DRY", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 35, key: "crybaby", label: "Crybaby", category: "wah", stereo: false, offset: 147,
        params: [
            { port: 0, symbol: "LEVEL", name: "Level", default: 0.1, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "WAH", name: "Wah", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 36, key: "autowah", label: "Auto Wah", category: "wah", stereo: false, offset: 150,
        params: [
        ],
    },
    {
        id: 37, key: "dunwah", label: "Classic Wah", category: "wah", stereo: false, offset: 150,
        params: [
            { port: 3, symbol: "WAH", name: "Wah", default: 0, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 38, key: "vibe", label: "Vibe", category: "modulation", stereo: true, offset: 151,
        params: [
            { port: 0, symbol: "WIDTH", name: "Width", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "DEPTH", name: "Depth", default: 0.37, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "WETDRY", name: "Dry/Wet", default: 1, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "FB", name: "Feedback", default: -0.6, min: -1, max: 1, step: 0.01 },
            { port: 4, symbol: "TEMPO", name: "Tempo", default: 4.4, min: 0.1, max: 10, step: 0.1 },
            { port: 7, symbol: "DF", name: "L/R Phase", default: 0.11, min: -0.5, max: 0.5, step: 0.01 },
            { port: 8, symbol: "PAN", name: "Pan", default: 0, min: -1, max: 1, step: 0.01 },
            { port: 9, symbol: "CROSS", name: "Cross", default: 0, min: -1, max: 1, step: 0.01 },
        ],
    },
    {
        id: 39, key: "tubetremelo", label: "Tube Tremolo", category: "modulation", stereo: false, offset: 159,
        params: [
            { port: 0, symbol: "sinewave", name: "Sine Wave", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 1, symbol: "depth", name: "Depth", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "speed", name: "Speed", default: 3, min: 0.1, max: 14, step: 0.1 },
            { port: 3, symbol: "drive", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "output", name: "Output", default: 0, min: -20, max: 20, step: 1 },
        ],
    },
    {
        id: 40, key: "tubevibrato", label: "Tube Vibrato", category: "modulation", stereo: false, offset: 164,
        params: [
            { port: 0, symbol: "sinewave", name: "Sine Wave", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 1, symbol: "depth", name: "Depth", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "speed", name: "Speed", default: 3, min: 0.1, max: 14, step: 0.1 },
            { port: 3, symbol: "drive", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "output", name: "Output", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 41, key: "switched_tremolo", label: "Switched Tremolo", category: "modulation", stereo: false, offset: 169,
        params: [
            { port: 2, symbol: "DEPTH", name: "Depth", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "FREQ0", name: "Freq 0", default: 1, min: 0.25, max: 15, step: 0.1 },
            { port: 4, symbol: "FREQ1", name: "Freq 1", default: 2, min: 0.25, max: 15, step: 0.1 },
            { port: 5, symbol: "FREQ2", name: "Freq 2", default: 4, min: 0.25, max: 15, step: 0.1 },
            { port: 6, symbol: "FREQ3", name: "Freq 3", default: 8, min: 0.25, max: 15, step: 0.1 },
            { port: 7, symbol: "STEPS", name: "Steps", default: 4, min: 1, max: 4, step: 0.01 },
            { port: 8, symbol: "SWITCHFREQ", name: "Switch Freq", default: 1, min: 0.25, max: 5, step: 0.1 },
            { port: 9, symbol: "WET_DRY", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 42, key: "phaser_st", label: "Classic Phaser", category: "modulation", stereo: true, offset: 177,
        params: [
            { port: 0, symbol: "MAXNOTCH1FREQ", name: "Max Notch Freq", default: 800, min: 20, max: 10000, step: 1 },
            { port: 1, symbol: "MINNOTCH1FREQ", name: "Min Notch Freq", default: 100, min: 20, max: 5000, step: 1 },
            { port: 2, symbol: "NOTCHWIDTH", name: "Notch Width", default: 1000, min: 10, max: 5000, step: 1 },
            { port: 3, symbol: "NOTCHFREQ", name: "Notch Freq", default: 1.5, min: 1.1, max: 4, step: 0.01 },
            { port: 4, symbol: "SPEED", name: "Speed", default: 0.5, min: 0, max: 10, step: 0.01 },
            { port: 5, symbol: "VIBRATOMODE", name: "Vibrato Mode", default: 0, min: 0, max: 1, step: 1 },
            { port: 6, symbol: "DEPTH", name: "Depth", default: 1, min: 0, max: 1, step: 0.01 },
            { port: 7, symbol: "FEEDBACKGAIN", name: "Feedback Gain", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 8, symbol: "INVERT", name: "Invert", default: 0, min: 0, max: 1, step: 1 },
            { port: 9, symbol: "LEVEL", name: "Level", default: 0, min: -60, max: 10, step: 0.1 },
        ],
    },
    {
        id: 43, key: "flanger_st", label: "Classic Flanger", category: "modulation", stereo: true, offset: 187,
        params: [
            { port: 0, symbol: "LFOFREQ", name: "LFO Freq", default: 0.2, min: 0, max: 5, step: 0.01 },
            { port: 1, symbol: "DEPTH", name: "Depth", default: 1, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "FEEDBACKGAIN", name: "Feedback Gain", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "DELAY", name: "Delay", default: 10, min: 0, max: 20, step: 0.01 },
            { port: 4, symbol: "DELAYOFFSET", name: "Delay Offset", default: 1, min: 0, max: 20, step: 0.01 },
            { port: 5, symbol: "INVERT", name: "Invert", default: 0, min: 0, max: 1, step: 1 },
            { port: 6, symbol: "LEVEL", name: "Level", default: 0, min: -60, max: 10, step: 0.1 },
        ],
    },
    {
        id: 44, key: "chorus_mono", label: "Chorus Mono", category: "modulation", stereo: false, offset: 194,
        params: [
            { port: 0, symbol: "FREQ", name: "Freq", default: 2, min: 0, max: 10, step: 0.01 },
            { port: 1, symbol: "LEVEL", name: "Level", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 45, key: "duck_delay", label: "Duck Delay", category: "delay", stereo: false, offset: 197,
        params: [
            { port: 2, symbol: "AMOUNT", name: "Amount", default: 0.5, min: 0, max: 56, step: 1 },
            { port: 3, symbol: "ATTACK", name: "Attack", default: 0.1, min: 0.05, max: 0.5, step: 0.01 },
            { port: 4, symbol: "FEEDBACK", name: "Feedback", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 5, symbol: "RELESE", name: "Release", default: 0.1, min: 0.05, max: 2, step: 0.01 },
            { port: 6, symbol: "TIME", name: "Time", default: 500, min: 1, max: 2000, step: 10 },
        ],
    },
    {
        id: 46, key: "duck_delay_st", label: "Duck Delay Stereo", category: "delay", stereo: true, offset: 202,
        params: [
            { port: 4, symbol: "AMOUNT", name: "Amount", default: 0.5, min: 0, max: 56, step: 1 },
            { port: 5, symbol: "ATTACK", name: "Attack", default: 0.1, min: 0.05, max: 0.5, step: 0.01 },
            { port: 6, symbol: "COLORATION", name: "Coloration", default: 0, min: -1, max: 1, step: 0.01 },
            { port: 7, symbol: "EFFECT", name: "Effect", default: 0, min: -16, max: 4, step: 0.1 },
            { port: 8, symbol: "FEEDBACK", name: "Feedback", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 9, symbol: "PINGPONG", name: "Ping-Pong", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 10, symbol: "RELEASE", name: "Release", default: 0.1, min: 0.05, max: 2, step: 0.01 },
            { port: 11, symbol: "TIME", name: "Time", default: 500, min: 1, max: 2000, step: 10 },
        ],
    },
    {
        id: 47, key: "digital_delay", label: "Digital Delay", category: "delay", stereo: false, offset: 210,
        params: [
            { port: 2, symbol: "BPM", name: "BPM", default: 120, min: 24, max: 360, step: 10 },
            { port: 3, symbol: "FEEDBACK", name: "Feedback", default: 50, min: 1, max: 100, step: 1 },
            { port: 4, symbol: "GAIN", name: "Gain", default: 100, min: 0, max: 120, step: 1 },
            { port: 5, symbol: "HIGHPASS", name: "Highpass", default: 120, min: 20, max: 20000, step: 10 },
            { port: 6, symbol: "HOWPASS", name: "Lowpass", default: 12000, min: 20, max: 20000, step: 10 },
            { port: 7, symbol: "LEVEL", name: "Level", default: 50, min: 1, max: 100, step: 1 },
            { port: 8, symbol: "MODE", name: "Mode", default: 0, min: 0, max: 3, step: 1, integer: true },
            { port: 9, symbol: "NOTES", name: "Notes", default: 4, min: 0, max: 17, step: 1, integer: true },
        ],
    },
    {
        id: 48, key: "digital_delay_st", label: "Digital Delay Stereo", category: "delay", stereo: true, offset: 218,
        params: [
            { port: 4, symbol: "BPM", name: "BPM", default: 120, min: 24, max: 360, step: 10 },
            { port: 5, symbol: "FEEDBACK", name: "Feedback", default: 50, min: 1, max: 100, step: 1 },
            { port: 6, symbol: "GAIN", name: "Gain", default: 100, min: 0, max: 120, step: 1 },
            { port: 7, symbol: "HIGHPASS", name: "Highpass", default: 120, min: 20, max: 20000, step: 10 },
            { port: 8, symbol: "HOWPASS", name: "Lowpass", default: 12000, min: 20, max: 20000, step: 10 },
            { port: 9, symbol: "LEVEL", name: "Level", default: 50, min: 1, max: 100, step: 1 },
            { port: 10, symbol: "MODE", name: "Mode", default: 0, min: 0, max: 3, step: 1, integer: true },
            { port: 11, symbol: "NOTES", name: "Notes", default: 4, min: 0, max: 17, step: 1, integer: true },
        ],
    },
    {
        id: 49, key: "gxtape", label: "Tape", category: "delay", stereo: false, offset: 226,
        params: [
            { port: 0, symbol: "on", name: "On", default: 1, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "drive", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "wowdepth", name: "Wow Depth", default: 0.02, min: 0, max: 0.03, step: 0.01 },
            { port: 3, symbol: "wowfreq", name: "Wow Freq", default: 1.4, min: 0, max: 4, step: 0.1 },
            { port: 4, symbol: "flutdepth", name: "Flutter Depth", default: 0.02, min: 0, max: 0.03, step: 0.01 },
            { port: 5, symbol: "flutfreq", name: "Flutter Freq", default: 20, min: 4, max: 60, step: 1 },
            { port: 6, symbol: "hiss", name: "Tape Hiss", default: 0.4, min: 0, max: 1, step: 0.01 },
            { port: 7, symbol: "type", name: "Tape Type", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 8, symbol: "speed", name: "Speed", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 9, symbol: "gain", name: "Gain", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 50, key: "gxtape_st", label: "Tape Stereo", category: "delay", stereo: true, offset: 236,
        params: [
            { port: 0, symbol: "on", name: "On", default: 1, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "drive", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "wowdepth", name: "Wow Depth", default: 0.02, min: 0, max: 0.03, step: 0.01 },
            { port: 3, symbol: "wowfreq", name: "Wow Freq", default: 1.4, min: 0, max: 4, step: 0.1 },
            { port: 4, symbol: "flutdepth", name: "Flutter Depth", default: 0.02, min: 0, max: 0.03, step: 0.01 },
            { port: 5, symbol: "flutfreq", name: "Flutter Freq", default: 20, min: 4, max: 60, step: 1 },
            { port: 6, symbol: "hiss", name: "Tape Hiss", default: 0.4, min: 0, max: 1, step: 0.01 },
            { port: 7, symbol: "type", name: "Tape Type", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 8, symbol: "speed", name: "Speed", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 9, symbol: "gain", name: "Gain", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 51, key: "gxechocat", label: "Echo Cat", category: "delay", stereo: false, offset: 246,
        params: [
            { port: 0, symbol: "input", name: "Input", default: 0.25, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "swell", name: "Swell", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "sustain", name: "Sustain", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "output", name: "Output", default: 1, min: 0, max: 4, step: 0.1 },
            { port: 4, symbol: "bpm", name: "BPM", default: 120, min: 24, max: 360, step: 10 },
            { port: 5, symbol: "head1", name: "Head 1", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 6, symbol: "head2", name: "Head 2", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 7, symbol: "head3", name: "Head 3", default: 0, min: 0, max: 1, step: 1, integer: true },
        ],
    },
    {
        id: 52, key: "gxtubedelay", label: "Tube Delay", category: "delay", stereo: false, offset: 254,
        params: [
            { port: 0, symbol: "drive", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "delay", name: "Delay", default: 160, min: 1, max: 2500, step: 10 },
            { port: 2, symbol: "feedback", name: "Feedback", default: 0.35, min: 0.01, max: 0.7, step: 0.01 },
            { port: 3, symbol: "level", name: "Level", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "output", name: "Output", default: 0, min: -20, max: 20, step: 1 },
        ],
    },
    {
        id: 53, key: "ts9", label: "TS-9", category: "drive", stereo: false, offset: 259,
        params: [
            { port: 0, symbol: "fslider0_", name: "Level", default: -16, min: -20, max: 4, step: 0.1 },
            { port: 1, symbol: "fslider1_", name: "Tone", default: 400, min: 100, max: 1000, step: 10 },
            { port: 2, symbol: "fslider2_", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 54, key: "oc_2", label: "OC-2 Octave", category: "special", stereo: false, offset: 262,
        params: [
            { port: 2, symbol: "DIRECT", name: "Direct", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "OCTAVE1", name: "Octave 1", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "OCTAVE2", name: "Octave 2", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 55, key: "classic_delay", label: "Classic Delay", category: "delay", stereo: false, offset: 265,
        params: [
            { port: 0, symbol: "DELAY", name: "Delay", default: 0, min: 0, max: 5000, step: 10 },
            { port: 1, symbol: "GAIN", name: "Gain", default: 0, min: -20, max: 20, step: 0.1 },
        ],
    },
    {
        id: 56, key: "classic_echo", label: "Classic Echo", category: "delay", stereo: false, offset: 267,
        params: [
            { port: 0, symbol: "PERCENT", name: "Wet %", default: 0, min: 0, max: 100, step: 0.1 },
            { port: 1, symbol: "TIME", name: "Time", default: 1, min: 1, max: 2000, step: 1 },
        ],
    },
    {
        id: 57, key: "zita_rev1", label: "Zita Reverb", category: "reverb", stereo: true, offset: 269,
        params: [
            { port: 0, symbol: "level", name: "Level", default: 0, min: -60, max: 4, step: 1 },
            { port: 1, symbol: "EQ2_FREQ", name: "EQ2 Freq", default: 1500, min: 160, max: 10000, step: 10 },
            { port: 2, symbol: "EQ1_LEVEL", name: "EQ1 Level", default: 0, min: -15, max: 15, step: 0.1 },
            { port: 3, symbol: "EQ1_FREQ", name: "EQ1 Freq", default: 315, min: 40, max: 2500, step: 10 },
            { port: 4, symbol: "IN_DELAY", name: "Predelay", default: 60, min: 20, max: 100, step: 1 },
            { port: 5, symbol: "LOW_RT60", name: "Low RT60", default: 3, min: 1, max: 8, step: 0.1 },
            { port: 6, symbol: "LF_X", name: "LF X", default: 200, min: 50, max: 1000, step: 10 },
            { port: 7, symbol: "HF_DAMPING", name: "HF Damping", default: 6000, min: 1500, max: 23520, step: 10 },
            { port: 8, symbol: "MID_RT60", name: "Mid RT60", default: 2, min: 1, max: 8, step: 0.1 },
            { port: 9, symbol: "DRY_WET_MIX", name: "Dry/Wet Mix", default: 0, min: -1, max: 1, step: 0.01 },
            { port: 10, symbol: "EQ2_LEVEL", name: "EQ2 Level", default: 0, min: -15, max: 15, step: 0.1 },
        ],
    },
    {
        id: 58, key: "freeverb", label: "Freeverb", category: "reverb", stereo: false, offset: 280,
        params: [
            { port: 0, symbol: "ROOMSIZE", name: "Room Size", default: 0.5, min: 0, max: 1, step: 0.025 },
            { port: 1, symbol: "DAMP", name: "Damping", default: 0.5, min: 0, max: 1, step: 0.025 },
            { port: 2, symbol: "WET_DRY", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 59, key: "room_simulator", label: "Room Simulator", category: "reverb", stereo: false, offset: 283,
        params: [
            { port: 2, symbol: "EFFECT", name: "Effect", default: 1, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "PREDELAYMS", name: "Predelay Ms", default: 20, min: 1, max: 200, step: 1 },
            { port: 4, symbol: "RT", name: "Decay", default: 0.3, min: 0, max: 1, step: 0.01 },
            { port: 5, symbol: "ROOMSIZE", name: "Room Size", default: 1, min: 0, max: 3, step: 0.01 },
            { port: 6, symbol: "DRYWET", name: "Dry/Wet", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 60, key: "shimmizita", label: "Shimmizita", category: "reverb", stereo: true, offset: 288,
        params: [
            { port: 4, symbol: "CONTROL", name: "Env Control", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 5, symbol: "DEPTH", name: "Depth", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 6, symbol: "DRYWET", name: "Dry/Wet", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 7, symbol: "ENVELOPE", name: "Envelope", default: 1, min: 0.1, max: 3, step: 0.01 },
            { port: 8, symbol: "F1", name: "F1", default: 200, min: 50, max: 1000, step: 10 },
            { port: 9, symbol: "F2", name: "F2", default: 6000, min: 1500, max: 23520, step: 10 },
            { port: 10, symbol: "MODE", name: "Mode", default: 0, min: -3, max: 3, step: 0.1 },
            { port: 11, symbol: "PSDRYWET", name: "Pitch Dry/Wet", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 12, symbol: "SHIFT", name: "Pitch Shift", default: 0, min: -6, max: 6, step: 0.1 },
            { port: 13, symbol: "SPEED", name: "Speed", default: 0.1, min: 0.1, max: 10, step: 0.1 },
            { port: 14, symbol: "T60DS", name: "T60 Low", default: 3, min: 1, max: 8, step: 0.1 },
            { port: 15, symbol: "T60M", name: "T60 Mid", default: 2, min: 1, max: 8, step: 0.1 },
        ],
    },
    {
        id: 61, key: "ampmodel", label: "Amp Model", category: "amp", stereo: false, offset: 300,
        params: [
            { port: 0, symbol: "MasterGain", name: "Master Gain", default: 0, min: -20, max: 20, step: 1 },
            { port: 1, symbol: "PreGain", name: "Pre Gain", default: 0, min: -20, max: 20, step: 1 },
            { port: 2, symbol: "Distortion", name: "Distortion", default: 20, min: 1, max: 100, step: 1 },
            { port: 3, symbol: "Drive", name: "Drive", default: 0.25, min: 0.01, max: 1, step: 0.01 },
            { port: 9, symbol: "model", name: "Model", default: 0, min: 0, max: 18, step: 1, integer: true },
            { port: 18, symbol: "HIGHGAIN", name: "High Gain", default: 0, min: 0, max: 1, step: 1 },
        ],
    },
    {
        id: 62, key: "tonestack", label: "Tone Stack", category: "tonestack", stereo: true, offset: 306,
        params: [
            { port: 4, symbol: "Middle", name: "Middle", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 5, symbol: "Bass", name: "Bass", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 6, symbol: "Treble", name: "Treble", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 10, symbol: "Model", name: "Model", default: 0, min: 0, max: 26, step: 1, integer: true },
        ],
    },
    {
        id: 63, key: "studiopre", label: "Studio Pre", category: "amp", stereo: true, offset: 310,
        params: [
            { port: 0, symbol: "bright_l", name: "Bright L", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 1, symbol: "volume_l", name: "Volume L", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "bass_l", name: "Bass L", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "middle_l", name: "Middle L", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "treble_l", name: "Treble L", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 5, symbol: "master_l", name: "Master L", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 6, symbol: "bright_r", name: "Bright R", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 7, symbol: "volume_r", name: "Volume R", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 8, symbol: "bass_r", name: "Bass R", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 9, symbol: "middle_r", name: "Middle R", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 10, symbol: "treble_r", name: "Treble R", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 11, symbol: "master_r", name: "Master R", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 64, key: "alembic", label: "Alembic Pre", category: "amp", stereo: false, offset: 322,
        params: [
            { port: 0, symbol: "input", name: "Input", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "bass", name: "Bass", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "middle", name: "Middle", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "treble", name: "Treble", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "volume", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 65, key: "w20", label: "W20 Pre", category: "amp", stereo: false, offset: 327,
        params: [
            { port: 0, symbol: "gain", name: "Gain", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "level", name: "Level", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 66, key: "mbcompressor", label: "MB Compressor", category: "multiband", stereo: false, offset: 329,
        params: [
            { port: 0, symbol: "MODE1", name: "Mode 1", default: 1, min: 1, max: 3, step: 1, integer: true },
            { port: 1, symbol: "MODE2", name: "Mode 2", default: 1, min: 1, max: 3, step: 1, integer: true },
            { port: 2, symbol: "MODE3", name: "Mode 3", default: 1, min: 1, max: 3, step: 1, integer: true },
            { port: 3, symbol: "MODE4", name: "Mode 4", default: 1, min: 1, max: 3, step: 1, integer: true },
            { port: 4, symbol: "MODE5", name: "Mode 5", default: 1, min: 1, max: 3, step: 1, integer: true },
            { port: 5, symbol: "MAKEUP1", name: "Makeup 1", default: 10, min: -50, max: 50, step: 1 },
            { port: 6, symbol: "MAKEUP2", name: "Makeup 2", default: 10, min: -50, max: 50, step: 1 },
            { port: 7, symbol: "MAKEUP3", name: "Makeup 3", default: 10, min: -50, max: 50, step: 1 },
            { port: 8, symbol: "MAKEUP4", name: "Makeup 4", default: 10, min: -50, max: 50, step: 1 },
            { port: 9, symbol: "MAKEUP5", name: "Makeup 5", default: 10, min: -50, max: 50, step: 1 },
            { port: 10, symbol: "MAKEUPTHRESHOLD1", name: "Makeup Thresh 1", default: 2, min: 0, max: 10, step: 0.1 },
            { port: 11, symbol: "MAKEUPTHRESHOLD2", name: "Makeup Thresh 2", default: 2, min: 0, max: 10, step: 0.1 },
            { port: 12, symbol: "MAKEUPTHRESHOLD3", name: "Makeup Thresh 3", default: 2, min: 0, max: 10, step: 0.1 },
            { port: 13, symbol: "MAKEUPTHRESHOLD4", name: "Makeup Thresh 4", default: 2, min: 0, max: 10, step: 0.1 },
            { port: 14, symbol: "MAKEUPTHRESHOLD5", name: "Makeup Thresh 5", default: 2, min: 0, max: 10, step: 0.1 },
            { port: 15, symbol: "RATIO1", name: "Ratio 1", default: 13, min: 1, max: 100, step: 1 },
            { port: 16, symbol: "RATIO2", name: "Ratio 2", default: 10, min: 1, max: 100, step: 1 },
            { port: 17, symbol: "RATIO3", name: "Ratio 3", default: 4, min: 1, max: 100, step: 1 },
            { port: 18, symbol: "RATIO4", name: "Ratio 4", default: 8, min: 1, max: 100, step: 1 },
            { port: 19, symbol: "RATIO5", name: "Ratio 5", default: 11, min: 1, max: 100, step: 1 },
            { port: 20, symbol: "ATTACK1", name: "Attack 1", default: 0.012, min: 0.001, max: 1, step: 0.01 },
            { port: 21, symbol: "ATTACK2", name: "Attack 2", default: 0.012, min: 0.001, max: 1, step: 0.01 },
            { port: 22, symbol: "ATTACK3", name: "Attack 3", default: 0.012, min: 0.001, max: 1, step: 0.01 },
            { port: 23, symbol: "ATTACK4", name: "Attack 4", default: 0.012, min: 0.001, max: 1, step: 0.01 },
            { port: 24, symbol: "ATTACK5", name: "Attack 5", default: 0.012, min: 0.001, max: 1, step: 0.01 },
            { port: 25, symbol: "RELEASE1", name: "Release 1", default: 1.25, min: 0.01, max: 10, step: 0.1 },
            { port: 26, symbol: "RELEASE2", name: "Release 2", default: 1.25, min: 0.01, max: 10, step: 0.1 },
            { port: 27, symbol: "RELEASE3", name: "Release 3", default: 1.25, min: 0.01, max: 10, step: 0.1 },
            { port: 28, symbol: "RELEASE4", name: "Release 4", default: 1.25, min: 0.01, max: 10, step: 0.1 },
            { port: 29, symbol: "RELEASE5", name: "Release 5", default: 1.25, min: 0.01, max: 10, step: 0.1 },
            { port: 30, symbol: "CROSSOVER_B1_B2", name: "Crossover B1/B2", default: 80, min: 20, max: 20000, step: 10 },
            { port: 31, symbol: "CROSSOVER_B2_B3", name: "Crossover B2/B3", default: 210, min: 20, max: 20000, step: 10 },
            { port: 32, symbol: "CROSSOVER_B3_B4", name: "Crossover B3/B4", default: 1700, min: 20, max: 20000, step: 10 },
            { port: 33, symbol: "CROSSOVER_B4_B5", name: "Crossover B4/B5", default: 5000, min: 20, max: 20000, step: 10 },
        ],
    },
    {
        id: 67, key: "mbdelay", label: "MB Delay", category: "multiband", stereo: false, offset: 363,
        params: [
            { port: 0, symbol: "DELAY1", name: "Delay 1", default: 30, min: 24, max: 360, step: 10 },
            { port: 1, symbol: "DELAY2", name: "Delay 2", default: 60, min: 24, max: 360, step: 10 },
            { port: 2, symbol: "DELAY3", name: "Delay 3", default: 90, min: 24, max: 360, step: 10 },
            { port: 3, symbol: "DELAY4", name: "Delay 4", default: 120, min: 24, max: 360, step: 10 },
            { port: 4, symbol: "DELAY5", name: "Delay 5", default: 150, min: 24, max: 360, step: 10 },
            { port: 5, symbol: "FEEDBACK1", name: "Feedback 1", default: 50, min: 1, max: 100, step: 1 },
            { port: 6, symbol: "FEEDBACK2", name: "Feedback 2", default: 50, min: 1, max: 100, step: 1 },
            { port: 7, symbol: "FEEDBACK3", name: "Feedback 3", default: 50, min: 1, max: 100, step: 1 },
            { port: 8, symbol: "FEEDBACK4", name: "Feedback 4", default: 50, min: 1, max: 100, step: 1 },
            { port: 9, symbol: "FEEDBACK5", name: "Feedback 5", default: 50, min: 1, max: 100, step: 1 },
            { port: 10, symbol: "GAIN1", name: "Gain 1", default: -10, min: -40, max: 2, step: 1 },
            { port: 11, symbol: "GAIN2", name: "Gain 2", default: -5, min: -40, max: 2, step: 1 },
            { port: 12, symbol: "GAIN3", name: "Gain 3", default: -2, min: -40, max: 2, step: 1 },
            { port: 13, symbol: "GAIN4", name: "Gain 4", default: 0, min: -40, max: 2, step: 1 },
            { port: 14, symbol: "GAIN5", name: "Gain 5", default: -10, min: -40, max: 2, step: 1 },
            { port: 15, symbol: "CROSSOVER_B1_B2", name: "Crossover B1/B2", default: 90, min: 20, max: 20000, step: 10 },
            { port: 16, symbol: "CROSSOVER_B2_B3", name: "Crossover B2/B3", default: 410, min: 20, max: 20000, step: 10 },
            { port: 17, symbol: "CROSSOVER_B3_B4", name: "Crossover B3/B4", default: 1800, min: 20, max: 20000, step: 10 },
            { port: 18, symbol: "CROSSOVER_B4_B5", name: "Crossover B4/B5", default: 6153, min: 20, max: 20000, step: 10 },
        ],
    },
    {
        id: 68, key: "mbdistortion", label: "MB Distortion", category: "multiband", stereo: false, offset: 382,
        params: [
            { port: 0, symbol: "DRIVE1", name: "Drive 1", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "DRIVE2", name: "Drive 2", default: 0.25, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "DRIVE3", name: "Drive 3", default: 0.65, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "DRIVE4", name: "Drive 4", default: 0.25, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "DRIVE5", name: "Drive 5", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 5, symbol: "GAIN", name: "Gain", default: -15, min: -40, max: 4, step: 1 },
            { port: 6, symbol: "OFFSET1", name: "Offset 1", default: 0.17, min: 0, max: 0.5, step: 0.01 },
            { port: 7, symbol: "OFFSET2", name: "Offset 2", default: 0.2, min: 0, max: 0.5, step: 0.01 },
            { port: 8, symbol: "OFFSET3", name: "Offset 3", default: 0.2, min: 0, max: 0.5, step: 0.01 },
            { port: 9, symbol: "OFFSET4", name: "Offset 4", default: 0.2, min: 0, max: 0.5, step: 0.01 },
            { port: 10, symbol: "OFFSET5", name: "Offset 5", default: 0.17, min: 0, max: 0.5, step: 0.01 },
            { port: 11, symbol: "CROSSOVER_B1_B2", name: "Crossover B1/B2", default: 80, min: 20, max: 20000, step: 10 },
            { port: 12, symbol: "CROSSOVER_B2_B3", name: "Crossover B2/B3", default: 210, min: 20, max: 20000, step: 10 },
            { port: 13, symbol: "CROSSOVER_B3_B4", name: "Crossover B3/B4", default: 1700, min: 20, max: 20000, step: 10 },
            { port: 14, symbol: "CROSSOVER_B4_B5", name: "Crossover B4/B5", default: 5000, min: 20, max: 20000, step: 10 },
        ],
    },
    {
        id: 69, key: "mbecho", label: "MB Echo", category: "multiband", stereo: false, offset: 397,
        params: [
            { port: 0, symbol: "PERCENT1", name: "Wet 1", default: 10, min: 0, max: 100, step: 1 },
            { port: 1, symbol: "PERCENT2", name: "Wet 2", default: 30, min: 0, max: 100, step: 1 },
            { port: 2, symbol: "PERCENT3", name: "Wet 3", default: 45, min: 0, max: 100, step: 1 },
            { port: 3, symbol: "PERCENT4", name: "Wet 4", default: 20, min: 0, max: 100, step: 1 },
            { port: 4, symbol: "PERCENT5", name: "Wet 5", default: 0, min: 0, max: 100, step: 1 },
            { port: 5, symbol: "TIME1", name: "Time 1", default: 30, min: 24, max: 360, step: 10 },
            { port: 6, symbol: "TIME2", name: "Time 2", default: 60, min: 24, max: 360, step: 10 },
            { port: 7, symbol: "TIME3", name: "Time 3", default: 120, min: 24, max: 360, step: 10 },
            { port: 8, symbol: "TIME4", name: "Time 4", default: 150, min: 24, max: 360, step: 10 },
            { port: 9, symbol: "TIME5", name: "Time 5", default: 240, min: 24, max: 360, step: 10 },
            { port: 10, symbol: "CROSSOVER_B1_B2", name: "Crossover B1/B2", default: 80, min: 20, max: 20000, step: 10 },
            { port: 11, symbol: "CROSSOVER_B2_B3", name: "Crossover B2/B3", default: 210, min: 20, max: 20000, step: 10 },
            { port: 12, symbol: "CROSSOVER_B3_B4", name: "Crossover B3/B4", default: 1700, min: 20, max: 20000, step: 10 },
            { port: 13, symbol: "CROSSOVER_B4_B5", name: "Crossover B4/B5", default: 5000, min: 20, max: 20000, step: 10 },
        ],
    },
    {
        id: 70, key: "barkgraphiceq", label: "Bark Graphic EQ", category: "multiband", stereo: false, offset: 411,
        params: [
            { port: 0, symbol: "G1", name: "G1", default: 0, min: -30, max: 20, step: 1 },
            { port: 1, symbol: "G2", name: "G2", default: 0, min: -30, max: 20, step: 1 },
            { port: 2, symbol: "G3", name: "G3", default: 0, min: -30, max: 20, step: 1 },
            { port: 3, symbol: "G4", name: "G4", default: 0, min: -30, max: 20, step: 1 },
            { port: 4, symbol: "G5", name: "G5", default: 0, min: -30, max: 20, step: 1 },
            { port: 5, symbol: "G6", name: "G6", default: 0, min: -30, max: 20, step: 1 },
            { port: 6, symbol: "G7", name: "G7", default: 0, min: -30, max: 20, step: 1 },
            { port: 7, symbol: "G8", name: "G8", default: 0, min: -30, max: 20, step: 1 },
            { port: 8, symbol: "G9", name: "G9", default: 0, min: -30, max: 20, step: 1 },
            { port: 9, symbol: "G10", name: "G10", default: 0, min: -30, max: 20, step: 1 },
            { port: 10, symbol: "G11", name: "G11", default: 0, min: -30, max: 20, step: 1 },
            { port: 11, symbol: "G12", name: "G12", default: 0, min: -30, max: 20, step: 1 },
            { port: 12, symbol: "G13", name: "G13", default: 0, min: -30, max: 20, step: 1 },
            { port: 13, symbol: "G14", name: "G14", default: 0, min: -30, max: 20, step: 1 },
            { port: 14, symbol: "G15", name: "G15", default: 0, min: -30, max: 20, step: 1 },
            { port: 15, symbol: "G16", name: "G16", default: 0, min: -30, max: 20, step: 1 },
            { port: 16, symbol: "G17", name: "G17", default: 0, min: -30, max: 20, step: 1 },
            { port: 17, symbol: "G18", name: "G18", default: 0, min: -30, max: 20, step: 1 },
            { port: 18, symbol: "G19", name: "G19", default: 0, min: -30, max: 20, step: 1 },
            { port: 19, symbol: "G20", name: "G20", default: 0, min: -30, max: 20, step: 1 },
            { port: 20, symbol: "G21", name: "G21", default: 0, min: -30, max: 20, step: 1 },
            { port: 21, symbol: "G22", name: "G22", default: 0, min: -30, max: 20, step: 1 },
            { port: 22, symbol: "G23", name: "G23", default: 0, min: -30, max: 20, step: 1 },
            { port: 23, symbol: "G24", name: "G24", default: 0, min: -30, max: 20, step: 1 },
        ],
    },
    {
        id: 71, key: "bigmuffpi", label: "Big Muff Pi", category: "drive", stereo: false, offset: 435,
        params: [
            { port: 2, symbol: "SUSTAIN", name: "Sustain", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 72, key: "balance", label: "Balance", category: "utility", stereo: true, offset: 438,
        params: [
            { port: 0, symbol: "BALANCE", name: "Balance", default: 0, min: -1, max: 1, step: 0.1 },
        ],
    },
    {
        id: 73, key: "outputlevel", label: "Output Level", category: "utility", stereo: true, offset: 439,
        params: [
            { port: 0, symbol: "OUT_MASTER", name: "Level", default: 0, min: -50, max: 4, step: 0.1 },
        ],
    },
    {
        id: 74, key: "ampout", label: "Amp Out", category: "utility", stereo: false, offset: 440,
        params: [
            { port: 0, symbol: "OUT_AMP", name: "Level", default: 0, min: -20, max: 4, step: 0.1 },
        ],
    },
    {
        id: 75, key: "ampmodul", label: "Postamp", category: "utility", stereo: true, offset: 441,
        params: [
            { port: 0, symbol: "FEEDBAC", name: "Dry Feedback", default: 0, min: -1, max: 1, step: 0.01 },
            { port: 1, symbol: "FEEDBACK", name: "Feedback", default: 0, min: -1, max: 1, step: 0.01 },
            { port: 2, symbol: "LEVEL", name: "Level", default: -20, min: -40, max: 4, step: 0.1 },
            { port: 3, symbol: "HIGHGAIN", name: "High Gain", default: 0, min: 0, max: 1, step: 1 },
            { port: 4, symbol: "TUBE1", name: "Tube 1", default: 6, min: -20, max: 20, step: 0.1 },
            { port: 5, symbol: "TUBE2", name: "Tube 2", default: 6, min: -20, max: 20, step: 0.1 },
            { port: 6, symbol: "WET_DRY", name: "Dry/Wet", default: 0, min: -1, max: 1, step: 0.1 },
        ],
    },
    {
        id: 76, key: "cabinet", label: "Cabinet", category: "amp", stereo: false, offset: 448,
        params: [
            { port: 0, symbol: "CLevel", name: "Cabinet", default: 1, min: 0.5, max: 5, step: 0.1 },
            { port: 1, symbol: "CBass", name: "Bass", default: 0, min: -10, max: 10, step: 0.1 },
            { port: 2, symbol: "CTreble", name: "Treble", default: 0, min: -10, max: 10, step: 0.1 },
            { port: 3, symbol: "c_model", name: "Cab Model", default: 0, min: 0, max: 18, step: 1, integer: true },
        ],
    },
    {
        id: 77, key: "redeye", label: "Redeye", category: "amp", stereo: false, offset: 452,
        params: [
            { port: 0, symbol: "Gain", name: "Gain", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "Tone", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "Volume", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "Feedback", name: "Feedback", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 4, symbol: "Vibe", name: "Vibe", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 5, symbol: "Speed", name: "Speed", default: 5, min: 0.1, max: 10, step: 0.1 },
            { port: 6, symbol: "Intensity", name: "Intensity", default: 0, min: 0, max: 10, step: 0.1 },
            { port: 7, symbol: "Sinewave", name: "Sinewave", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 10, symbol: "Model", name: "Model", default: 0, min: 0, max: 2, step: 1, integer: true },
        ],
    },
    {
        id: 78, key: "metalamp", label: "Metal Amp", category: "amp", stereo: false, offset: 461,
        params: [
            { port: 0, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "DRIVE", name: "Drive", default: 10.5, min: 1, max: 20, step: 0.1 },
            { port: 2, symbol: "PREGAIN", name: "Pre Gain", default: 0, min: -20, max: 20, step: 1 },
            { port: 3, symbol: "GAIN1", name: "Gain 1", default: 0, min: -20, max: 20, step: 1 },
        ],
    },
    {
        id: 79, key: "metalhead", label: "Metal Head", category: "amp", stereo: false, offset: 465,
        params: [
            { port: 0, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "DRIVE", name: "Drive", default: 0.32, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "PREGAIN", name: "Pre Gain", default: 0, min: -20, max: 20, step: 1 },
            { port: 3, symbol: "GAIN1", name: "Gain 1", default: 0, min: -20, max: 20, step: 1 },
        ],
    },
    {
        id: 80, key: "detune", label: "Detune", category: "special", stereo: false, offset: 469,
        params: [
            { port: 2, symbol: "DETUNE", name: "Detune", default: 0, min: -12, max: 12, step: 0.1 },
            { port: 3, symbol: "OCTAVE", name: "Octave", default: 0, min: 0, max: 2, step: 1, integer: true },
            { port: 4, symbol: "COMPENSATE", name: "Compensate", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 5, symbol: "LATENCY", name: "Latency", default: 0, min: 0, max: 2, step: 1, integer: true },
            { port: 6, symbol: "WET", name: "Wet", default: 50, min: 0, max: 100, step: 1 },
            { port: 7, symbol: "DRY", name: "Dry", default: 50, min: 0, max: 100, step: 1 },
            { port: 8, symbol: "LOW", name: "Low", default: 1, min: 0, max: 2, step: 0.01 },
            { port: 9, symbol: "MIDDLELOW", name: "Middle Low", default: 1, min: 0, max: 2, step: 0.01 },
            { port: 10, symbol: "MIDDLETREBLE", name: "Mid Treble", default: 1, min: 0, max: 2, step: 0.01 },
            { port: 11, symbol: "TREBLE", name: "Treble", default: 1, min: 0, max: 2, step: 0.01 },
        ],
    },
];

export const FX_TOTAL_PARAMS = 479;

// --- 0..1 knob space <-> engine space (linear; log knobs would need per-param curves later) ---

function fxLookupParam(fxId: number, param: number): FxParamDef | null {
    const fx = FX_EFFECTS[fxId];
    if (!fx || !Number.isInteger(param) || param < 0 || param >= fx.params.length) return null;
    return fx.params[param];
}

function clamp01(v: number): number {
    return v < 0 ? 0 : v > 1 ? 1 : v;
}

/** 0..1 knob position → engine value (clamped; integer params round). */
export function fxParamFrom01(fxId: number, param: number, v01: number): number {
    const def = fxLookupParam(fxId, param);
    if (!def) return NaN;
    const v = def.min + clamp01(v01) * (def.max - def.min);
    const r = def.integer ? Math.round(v) : v;
    return r < def.min ? def.min : r > def.max ? def.max : r;
}

/** Engine value → 0..1 knob position (clamped). */
export function fxParamTo01(fxId: number, param: number, v: number): number {
    const def = fxLookupParam(fxId, param);
    if (!def) return NaN;
    const span = def.max - def.min;
    if (span === 0) return 0;
    return clamp01((v - def.min) / span);
}

/** Default value expressed in 0..1 knob space. */
export function fxParamDefault01(fxId: number, param: number): number {
    const def = fxLookupParam(fxId, param);
    if (!def) return NaN;
    return fxParamTo01(fxId, param, def.default);
}

// --- flat-mirror helpers (used by persistence + worklet bulk state) ---

/** Index into the flat FX_TOTAL_PARAMS mirror: cumulative offset + param. */
export function fxFlatIndex(fxId: number, param: number): number {
    const fx = FX_EFFECTS[fxId];
    if (!fx || !Number.isInteger(param) || param < 0 || param >= fx.params.length) return -1;
    return fx.offset + param;
}

export function isFxId(v: number): boolean {
    return Number.isInteger(v) && v >= 0 && v < FX_COUNT;
}
