/**
 * Guitarix FX param tables (OctOBX per-instance insert chains).
 *
 * AUTO-GENERATED by tools/gen-gxfx-params.mjs — DO NOT EDIT THIS FILE BY
 * HAND. Param data sources: the v1 eleven are pinned in
 * tools/gxfx-param-spec.json (hand-verified labels/values); new effects
 * are parsed from the guitarix bundle ttl files + orphan .cc connect
 * comments (third_party/guitarix, pinned submodule).
 * Cross-checked against the C engine by test/gxfx-params.test.ts +
 * verify-obxd-wasm.mjs.
 *
 * Regenerate with:    node tools/gen-gxfx-params.mjs
 * Freshness check:    node tools/gen-gxfx-params.mjs --check   (CI gate)
 */

export const FX_COUNT = 45;
export const FX_SLOTS = 11;
export const FX_INSTANCE_COUNT = 10;
export const FX_SLOT_PARAMS = 48;

export interface FxParamDef {
    port: number;      // PortIndex value passed to fx_set_param's `param`
    symbol: string;
    name: string;
    default: number;   // ENGINE units (ttl range, not 0..1)
    min: number;
    max: number;
    step: number;
    integer?: boolean;
}

/** Menu category (full fx v2 vocabulary). */
export type FxCategory =
    | "wah" | "drive" | "eq" | "filter" | "dynamics" | "modulation"
    | "delay" | "reverb" | "amp" | "tonestack" | "multiband" | "special" | "utility";

export interface FxEffectDef {
    id: number;
    key: string;       // 'wah' | 'overdrive' | ... (manifest order = generator id order)
    label: string;
    category: FxCategory;
    stereo: boolean;
    offset: number;    // cumulative param offset into the flat 197-slot mirror
    params: FxParamDef[];
}

/** Effect catalog in id order (generator manifest). The canonical default
 * chain is ids 0..10 (wah → overdrive → distortion → compressor → chorus →
 * flanger → phaser → tremolo → delay → echo → reverb); ids 11+ are the
 * Phase-1 additions selectable per slot.
 * Param counts 2,1,3,5,4,6,3,4,7,7,5,2,4,3,3,2,3,3,2,2,2,2,2,1,1,1,5,2,11,30,5,2,6,1,5,3,0,1,8,5,5,8,10,7,3 → offsets 0,2,3,6,11,15,21,24,28,35,42,47,49,53,56,59,61,64,67,69,71,73,75,77,78,79,80,85,87,98,128,133,135,141,142,147,150,150,151,159,164,169,177,187,194. */
export const FX_EFFECTS: FxEffectDef[] = [
    {
        id: 0, key: "wah", label: "Wah", category: "wah", stereo: false, offset: 0,
        params: [
            { port: 2, symbol: "VOLUME", name: "Volume", default: 0, min: -20, max: 4, step: 0.1 },
            { port: 3, symbol: "HOTPOTZ", name: "Wah", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 1, key: "overdrive", label: "Overdrive", category: "drive", stereo: false, offset: 2,
        params: [
            { port: 2, symbol: "SCREAM", name: "Scream", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 2, key: "distortion", label: "Distortion", category: "drive", stereo: false, offset: 3,
        params: [
            { port: 2, symbol: "LEVEL", name: "Level", default: -2, min: -20, max: 12, step: 0.1 },
            { port: 3, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "DRIVE", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 3, key: "compressor", label: "Compressor", category: "dynamics", stereo: false, offset: 6,
        params: [
            { port: 0, symbol: "RATIO", name: "Ratio", default: 2, min: 1, max: 20, step: 0.1 },
            { port: 1, symbol: "KNEE", name: "Knee", default: 3, min: 0, max: 20, step: 0.1 },
            { port: 2, symbol: "THRESHOLD", name: "Threshold", default: -20, min: -96, max: 10, step: 0.1 },
            { port: 3, symbol: "RELEASE", name: "Release", default: 0.5, min: 0, max: 10, step: 0.01 },
            { port: 4, symbol: "ATTACK", name: "Attack", default: 0.002, min: 0, max: 1, step: 0.001 },
        ],
    },
    {
        id: 4, key: "chorus", label: "Chorus", category: "modulation", stereo: true, offset: 11,
        params: [
            { port: 0, symbol: "level", name: "Level", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "delay", name: "Delay", default: 0.02, min: 0, max: 0.2, step: 0.01 },
            { port: 2, symbol: "depth", name: "Depth", default: 0.02, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "freq", name: "Freq", default: 3, min: 0.1, max: 10, step: 0.01 },
        ],
    },
    {
        id: 5, key: "flanger", label: "Flanger", category: "modulation", stereo: false, offset: 15,
        params: [
            { port: 0, symbol: "depth", name: "Depth", default: 0.5, min: 0, max: 5, step: 0.01 },
            { port: 1, symbol: "width", name: "Width", default: 5, min: 0, max: 10, step: 0.01 },
            { port: 2, symbol: "freq", name: "Freq", default: 0.2, min: 0.05, max: 10, step: 1.06 },
            { port: 3, symbol: "feedback", name: "Feedback", default: -0.707, min: -0.99, max: 0.99, step: 0.01 },
            { port: 4, symbol: "dry_wet", name: "Wet", default: 100, min: 0, max: 100, step: 1 },
            { port: 5, symbol: "mix", name: "Mix", default: 0, min: -1, max: 1, step: 0.1 },
        ],
    },
    {
        id: 6, key: "phaser", label: "Phaser", category: "modulation", stereo: false, offset: 21,
        params: [
            { port: 0, symbol: "dry_wet", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
            { port: 1, symbol: "level", name: "Level", default: 0, min: -60, max: 10, step: 0.1 },
            { port: 2, symbol: "speed", name: "Speed", default: 0.5, min: 0, max: 10, step: 0.01 },
        ],
    },
    {
        id: 7, key: "tremolo", label: "Tremolo", category: "modulation", stereo: false, offset: 24,
        params: [
            { port: 0, symbol: "dry_wet", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
            { port: 1, symbol: "mode", name: "Mode", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 2, symbol: "depth", name: "Depth", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "freq", name: "Freq", default: 5, min: 0.1, max: 50, step: 0.1 },
        ],
    },
    {
        id: 8, key: "delay", label: "Delay", category: "delay", stereo: true, offset: 28,
        params: [
            { port: 0, symbol: "mode", name: "Mode", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 1, symbol: "level_r", name: "R Level", default: -10, min: -20, max: 20, step: 0.1 },
            { port: 2, symbol: "timt_r", name: "R Time", default: 1000, min: 1, max: 5000, step: 10 },
            { port: 3, symbol: "level_l", name: "L Level", default: -10, min: -20, max: 20, step: 0.1 },
            { port: 4, symbol: "timt_l", name: "L Time", default: 1000, min: 1, max: 5000, step: 10 },
            { port: 5, symbol: "lfo", name: "LFO", default: 0.2, min: 0.2, max: 5, step: 0.01 },
            { port: 6, symbol: "link", name: "Link (L+R)", default: 0, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 9, key: "echo", label: "Echo", category: "delay", stereo: true, offset: 35,
        params: [
            { port: 0, symbol: "mode", name: "Mode", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 1, symbol: "level_r", name: "R Level", default: 30, min: 0, max: 100, step: 0.1 },
            { port: 2, symbol: "timt_r", name: "R Time", default: 100, min: 1, max: 2000, step: 1 },
            { port: 3, symbol: "level_l", name: "L Level", default: 30, min: 0, max: 100, step: 0.1 },
            { port: 4, symbol: "timt_l", name: "L Time", default: 100, min: 1, max: 2000, step: 1 },
            { port: 5, symbol: "lfo", name: "LFO", default: 0.2, min: 0.2, max: 5, step: 0.01 },
            { port: 6, symbol: "link", name: "Link (L+R)", default: 0, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 10, key: "reverb", label: "Reverb", category: "reverb", stereo: true, offset: 42,
        params: [
            { port: 0, symbol: "dry_wet", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
            { port: 1, symbol: "lfo", name: "LFO", default: 0.2, min: 0.2, max: 5, step: 0.01 },
            { port: 2, symbol: "roomsize", name: "Roomsize", default: 0.5, min: 0, max: 1, step: 0.025 },
            { port: 3, symbol: "damp", name: "Damp", default: 0.2, min: 0, max: 1, step: 0.025 },
            { port: 4, symbol: "mode", name: "Mode", default: 0, min: 0, max: 1, step: 1, integer: true },
        ],
    },
    {
        id: 11, key: "fuzzface", label: "Fuzz Face", category: "drive", stereo: false, offset: 47,
        params: [
            { port: 2, symbol: "FUZZ", name: "Fuzz", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "LEVEL", name: "Level", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 12, key: "fuzzfacefm", label: "Fuzz Face FM", category: "drive", stereo: false, offset: 49,
        params: [
            { port: 2, symbol: "DRIVE", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "FUZZ", name: "Fuzz", default: 0.5, min: 0, max: 0.99, step: 0.01 },
            { port: 4, symbol: "INPUT", name: "Input", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 5, symbol: "LEVEL", name: "Level", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 13, key: "fumaster", label: "Fuzz Master", category: "drive", stereo: false, offset: 53,
        params: [
            { port: 2, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "VOLUME", name: "Volume", default: 0.1, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 14, key: "hornet", label: "Hornet", category: "drive", stereo: false, offset: 56,
        params: [
            { port: 2, symbol: "FUZZ", name: "Fuzz", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "SUSTAIN", name: "Sustain", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 15, key: "muff", label: "Muff", category: "drive", stereo: false, offset: 59,
        params: [
            { port: 2, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 16, key: "cstb", label: "Tone Bender", category: "drive", stereo: false, offset: 61,
        params: [
            { port: 2, symbol: "ATTACK", name: "Attack", default: 0.5, min: 0, max: 0.95, step: 0.01 },
            { port: 3, symbol: "LEVEL", name: "Level", default: 0.2, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "WET_DRY", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 17, key: "aclipper", label: "Rat", category: "drive", stereo: false, offset: 64,
        params: [
            { port: 2, symbol: "DRIVE", name: "Drive", default: 0.3, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "LEVEL", name: "Level", default: -7, min: -20, max: 12, step: 1 },
            { port: 4, symbol: "TONE", name: "Tone", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 18, key: "mxrdist", label: "MXR Distortion", category: "drive", stereo: false, offset: 67,
        params: [
            { port: 2, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "DRIVE", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 19, key: "rangem", label: "Range Master", category: "drive", stereo: false, offset: 69,
        params: [
            { port: 2, symbol: "BOOST", name: "Boost", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 20, key: "mole", label: "Mole", category: "drive", stereo: false, offset: 71,
        params: [
            { port: 2, symbol: "BOOST", name: "Boost", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 21, key: "hfb", label: "HF Brightener", category: "drive", stereo: false, offset: 73,
        params: [
            { port: 2, symbol: "INTENSITY", name: "Intensity", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 22, key: "hogsfoot", label: "Hogs Foot", category: "drive", stereo: false, offset: 75,
        params: [
            { port: 2, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 23, key: "softclip", label: "Softclip", category: "drive", stereo: false, offset: 77,
        params: [
            { port: 0, symbol: "FUZZ", name: "Fuzz", default: 0, min: 0, max: 1.99, step: 0.01 },
        ],
    },
    {
        id: 24, key: "bassbooster", label: "Bass Booster", category: "drive", stereo: false, offset: 78,
        params: [
            { port: 0, symbol: "LEVEL", name: "Level", default: 10, min: 0.5, max: 20, step: 0.5 },
        ],
    },
    {
        id: 25, key: "highbooster", label: "High Booster", category: "drive", stereo: false, offset: 79,
        params: [
            { port: 0, symbol: "LEVEL", name: "Level", default: 0.5, min: 0, max: 20, step: 0.5 },
        ],
    },
    {
        id: 26, key: "expander", label: "Expander", category: "dynamics", stereo: false, offset: 80,
        params: [
            { port: 0, symbol: "RATIO", name: "Ratio", default: 2, min: 1, max: 20, step: 0.1 },
            { port: 1, symbol: "KNEE", name: "Knee", default: 3, min: 0, max: 20, step: 0.1 },
            { port: 2, symbol: "THRESHOLD", name: "Threshold", default: -40, min: -96, max: 10, step: 1 },
            { port: 3, symbol: "RELEASE", name: "Release", default: 0.1, min: 0, max: 10, step: 0.1 },
            { port: 4, symbol: "ATTACK", name: "Attack", default: 0.001, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 27, key: "susta", label: "Sustainer", category: "dynamics", stereo: false, offset: 85,
        params: [
            { port: 2, symbol: "SUSTAIN", name: "Sustain", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "VOLUME", name: "Volume", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 28, key: "graphiceq", label: "Graphic EQ", category: "eq", stereo: false, offset: 87,
        params: [
            { port: 0, symbol: "G1", name: "G1", default: 0, min: -30, max: 20, step: 1 },
            { port: 1, symbol: "G2", name: "G2", default: 0, min: -30, max: 20, step: 1 },
            { port: 2, symbol: "G3", name: "G3", default: 0, min: -30, max: 20, step: 1 },
            { port: 3, symbol: "G4", name: "G4", default: 0, min: -30, max: 20, step: 1 },
            { port: 4, symbol: "G5", name: "G5", default: 0, min: -30, max: 20, step: 1 },
            { port: 5, symbol: "G6", name: "G6", default: 0, min: -30, max: 20, step: 1 },
            { port: 6, symbol: "G7", name: "G7", default: 0, min: -30, max: 20, step: 1 },
            { port: 7, symbol: "G8", name: "G8", default: 0, min: -30, max: 20, step: 1 },
            { port: 8, symbol: "G9", name: "G9", default: 0, min: -30, max: 20, step: 1 },
            { port: 9, symbol: "G10", name: "G10", default: 0, min: -30, max: 20, step: 1 },
            { port: 10, symbol: "G11", name: "G11", default: 0, min: -30, max: 20, step: 1 },
        ],
    },
    {
        id: 29, key: "selecteq", label: "Scaleable EQ", category: "eq", stereo: false, offset: 98,
        params: [
            { port: 0, symbol: "QS125", name: "Q 125", default: 50, min: 1, max: 100, step: 1 },
            { port: 1, symbol: "QS16K", name: "Q 16k", default: 50, min: 1, max: 100, step: 1 },
            { port: 2, symbol: "QS1K", name: "Q 1k", default: 50, min: 1, max: 100, step: 1 },
            { port: 3, symbol: "QS250", name: "Q 250", default: 50, min: 1, max: 100, step: 1 },
            { port: 4, symbol: "QS2K", name: "Q 2k", default: 50, min: 1, max: 100, step: 1 },
            { port: 5, symbol: "QS31_25", name: "Q 31.25", default: 50, min: 1, max: 100, step: 1 },
            { port: 6, symbol: "QS4K", name: "Q 4k", default: 50, min: 1, max: 100, step: 1 },
            { port: 7, symbol: "QS500", name: "Q 500", default: 50, min: 1, max: 100, step: 1 },
            { port: 8, symbol: "QS62_5", name: "Q 62.5", default: 50, min: 1, max: 100, step: 1 },
            { port: 9, symbol: "QS8K", name: "Q 8k", default: 50, min: 1, max: 100, step: 1 },
            { port: 10, symbol: "FREQ125", name: "Freq 125", default: 125, min: 20, max: 20000, step: 1 },
            { port: 11, symbol: "FREQ16K", name: "Freq 16k", default: 16000, min: 20, max: 20000, step: 1 },
            { port: 12, symbol: "FREQ1K", name: "Freq 1k", default: 1000, min: 20, max: 20000, step: 1 },
            { port: 13, symbol: "FREQ250", name: "Freq 250", default: 250, min: 20, max: 20000, step: 1 },
            { port: 14, symbol: "FREQ2K", name: "Freq 2k", default: 2000, min: 20, max: 20000, step: 1 },
            { port: 15, symbol: "FREQ31_25", name: "Freq 31.25", default: 31, min: 20, max: 20000, step: 1 },
            { port: 16, symbol: "FREQ4K", name: "Freq 4k", default: 4000, min: 20, max: 20000, step: 1 },
            { port: 17, symbol: "FREQ500", name: "Freq 500", default: 500, min: 20, max: 20000, step: 1 },
            { port: 18, symbol: "FREQ62_5", name: "Freq 62.5", default: 62, min: 20, max: 20000, step: 1 },
            { port: 19, symbol: "FREQ8K", name: "Freq 8k", default: 8000, min: 20, max: 20000, step: 1 },
            { port: 20, symbol: "FS125", name: "Gain 125", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 21, symbol: "FS16K", name: "Gain 16k", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 22, symbol: "FS1K", name: "Gain 1k", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 23, symbol: "FS250", name: "Gain 250", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 24, symbol: "FS2K", name: "Gain 2k", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 25, symbol: "FS31_25", name: "Gain 31.25", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 26, symbol: "FS4K", name: "Gain 4k", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 27, symbol: "FS500", name: "Gain 500", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 28, symbol: "FS62_5", name: "Gain 62.5", default: 0, min: -50, max: 10, step: 0.1 },
            { port: 29, symbol: "FS8K", name: "Gain 8k", default: 0, min: -50, max: 10, step: 0.1 },
        ],
    },
    {
        id: 30, key: "tonecontroll", label: "3 Band EQ", category: "eq", stereo: true, offset: 128,
        params: [
            { port: 0, symbol: "BASS", name: "Bass", default: 0, min: -5, max: 5, step: 0.01 },
            { port: 1, symbol: "MIDDLE", name: "Middle", default: 0, min: -5, max: 5, step: 0.01 },
            { port: 2, symbol: "ON", name: "On", default: 0, min: 0, max: 1, step: 1 },
            { port: 3, symbol: "TREBLE", name: "Treble", default: 0, min: -5, max: 5, step: 0.01 },
            { port: 4, symbol: "SHARPER", name: "Sharper", default: -2, min: -2.5, max: 5, step: 0.1 },
        ],
    },
    {
        id: 31, key: "moog", label: "Moog Filter", category: "eq", stereo: true, offset: 133,
        params: [
            { port: 0, symbol: "Q", name: "Q", default: 1, min: 0, max: 4, step: 0.1 },
            { port: 1, symbol: "FR", name: "Frequency", default: 3000, min: 440, max: 6000, step: 10 },
        ],
    },
    {
        id: 32, key: "low_high_pass", label: "Low/High Filter", category: "eq", stereo: false, offset: 135,
        params: [
            { port: 0, symbol: "HIGHFREQ", name: "BP High Freq", default: 5000, min: 1000, max: 12000, step: 10 },
            { port: 1, symbol: "LOWFREQ", name: "BP Low Freq", default: 130, min: 20, max: 1000, step: 10 },
            { port: 2, symbol: "ONOFF", name: "BP On/Off", default: 0, min: 0, max: 1, step: 1 },
            { port: 3, symbol: "HIGH_FREQ", name: "HP Freq", default: 130, min: 20, max: 7040, step: 10 },
            { port: 4, symbol: "LOW_FREQ", name: "LP Freq", default: 5000, min: 20, max: 12000, step: 10 },
            { port: 5, symbol: "ON_OFF", name: "LP/HP On/Off", default: 0, min: 0, max: 1, step: 1 },
        ],
    },
    {
        id: 33, key: "noise_shaper", label: "Noise Shaper", category: "eq", stereo: false, offset: 141,
        params: [
            { port: 0, symbol: "SHARPER", name: "Sharper", default: 1, min: 1, max: 10, step: 1 },
        ],
    },
    {
        id: 34, key: "wahmodel", label: "Wah Model", category: "wah", stereo: false, offset: 142,
        params: [
            { port: 2, symbol: "WAH", name: "Wah", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "FREQ", name: "Freq", default: 24, min: 24, max: 360, step: 10 },
            { port: 4, symbol: "MODE", name: "Mode", default: 0, min: 0, max: 2, step: 1, integer: true },
            { port: 5, symbol: "MODEL", name: "Model", default: 0, min: 0, max: 6, step: 1, integer: true },
            { port: 6, symbol: "WET_DRY", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 35, key: "crybaby", label: "Crybaby", category: "wah", stereo: false, offset: 147,
        params: [
            { port: 0, symbol: "LEVEL", name: "Level", default: 0.1, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "WAH", name: "Wah", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 36, key: "autowah", label: "Auto Wah", category: "wah", stereo: false, offset: 150,
        params: [
        ],
    },
    {
        id: 37, key: "dunwah", label: "Classic Wah", category: "wah", stereo: false, offset: 150,
        params: [
            { port: 3, symbol: "WAH", name: "Wah", default: 0, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 38, key: "vibe", label: "Vibe", category: "modulation", stereo: true, offset: 151,
        params: [
            { port: 0, symbol: "WIDTH", name: "Width", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 1, symbol: "DEPTH", name: "Depth", default: 0.37, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "WETDRY", name: "Dry/Wet", default: 1, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "FB", name: "Feedback", default: -0.6, min: -1, max: 1, step: 0.01 },
            { port: 4, symbol: "TEMPO", name: "Tempo", default: 4.4, min: 0.1, max: 10, step: 0.1 },
            { port: 7, symbol: "DF", name: "L/R Phase", default: 0.11, min: -0.5, max: 0.5, step: 0.01 },
            { port: 8, symbol: "PAN", name: "Pan", default: 0, min: -1, max: 1, step: 0.01 },
            { port: 9, symbol: "CROSS", name: "Cross", default: 0, min: -1, max: 1, step: 0.01 },
        ],
    },
    {
        id: 39, key: "tubetremelo", label: "Tube Tremolo", category: "modulation", stereo: false, offset: 159,
        params: [
            { port: 0, symbol: "sinewave", name: "Sine Wave", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 1, symbol: "depth", name: "Depth", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "speed", name: "Speed", default: 3, min: 0.1, max: 14, step: 0.1 },
            { port: 3, symbol: "drive", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "output", name: "Output", default: 0, min: -20, max: 20, step: 1 },
        ],
    },
    {
        id: 40, key: "tubevibrato", label: "Tube Vibrato", category: "modulation", stereo: false, offset: 164,
        params: [
            { port: 0, symbol: "sinewave", name: "Sine Wave", default: 0, min: 0, max: 1, step: 1, integer: true },
            { port: 1, symbol: "depth", name: "Depth", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "speed", name: "Speed", default: 3, min: 0.1, max: 14, step: 0.1 },
            { port: 3, symbol: "drive", name: "Drive", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 4, symbol: "output", name: "Output", default: 0.5, min: 0, max: 1, step: 0.01 },
        ],
    },
    {
        id: 41, key: "switched_tremolo", label: "Switched Tremolo", category: "modulation", stereo: false, offset: 169,
        params: [
            { port: 2, symbol: "DEPTH", name: "Depth", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "FREQ0", name: "Freq 0", default: 1, min: 0.25, max: 15, step: 0.1 },
            { port: 4, symbol: "FREQ1", name: "Freq 1", default: 2, min: 0.25, max: 15, step: 0.1 },
            { port: 5, symbol: "FREQ2", name: "Freq 2", default: 4, min: 0.25, max: 15, step: 0.1 },
            { port: 6, symbol: "FREQ3", name: "Freq 3", default: 8, min: 0.25, max: 15, step: 0.1 },
            { port: 7, symbol: "STEPS", name: "Steps", default: 4, min: 1, max: 4, step: 0.01 },
            { port: 8, symbol: "SWITCHFREQ", name: "Switch Freq", default: 1, min: 0.25, max: 5, step: 0.1 },
            { port: 9, symbol: "WET_DRY", name: "Dry/Wet", default: 50, min: 0, max: 100, step: 1 },
        ],
    },
    {
        id: 42, key: "phaser_st", label: "Classic Phaser", category: "modulation", stereo: true, offset: 177,
        params: [
            { port: 0, symbol: "MAXNOTCH1FREQ", name: "Max Notch Freq", default: 800, min: 20, max: 10000, step: 1 },
            { port: 1, symbol: "MINNOTCH1FREQ", name: "Min Notch Freq", default: 100, min: 20, max: 5000, step: 1 },
            { port: 2, symbol: "NOTCHWIDTH", name: "Notch Width", default: 1000, min: 10, max: 5000, step: 1 },
            { port: 3, symbol: "NOTCHFREQ", name: "Notch Freq", default: 1.5, min: 1.1, max: 4, step: 0.01 },
            { port: 4, symbol: "SPEED", name: "Speed", default: 0.5, min: 0, max: 10, step: 0.01 },
            { port: 5, symbol: "VIBRATOMODE", name: "Vibrato Mode", default: 0, min: 0, max: 1, step: 1 },
            { port: 6, symbol: "DEPTH", name: "Depth", default: 1, min: 0, max: 1, step: 0.01 },
            { port: 7, symbol: "FEEDBACKGAIN", name: "Feedback Gain", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 8, symbol: "INVERT", name: "Invert", default: 0, min: 0, max: 1, step: 1 },
            { port: 9, symbol: "LEVEL", name: "Level", default: 0, min: -60, max: 10, step: 0.1 },
        ],
    },
    {
        id: 43, key: "flanger_st", label: "Classic Flanger", category: "modulation", stereo: true, offset: 187,
        params: [
            { port: 0, symbol: "LFOFREQ", name: "LFO Freq", default: 0.2, min: 0, max: 5, step: 0.01 },
            { port: 1, symbol: "DEPTH", name: "Depth", default: 1, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "FEEDBACKGAIN", name: "Feedback Gain", default: 0, min: 0, max: 1, step: 0.01 },
            { port: 3, symbol: "DELAY", name: "Delay", default: 10, min: 0, max: 20, step: 0.01 },
            { port: 4, symbol: "DELAYOFFSET", name: "Delay Offset", default: 1, min: 0, max: 20, step: 0.01 },
            { port: 5, symbol: "INVERT", name: "Invert", default: 0, min: 0, max: 1, step: 1 },
            { port: 6, symbol: "LEVEL", name: "Level", default: 0, min: -60, max: 10, step: 0.1 },
        ],
    },
    {
        id: 44, key: "chorus_mono", label: "Chorus Mono", category: "modulation", stereo: false, offset: 194,
        params: [
            { port: 0, symbol: "FREQ", name: "Freq", default: 2, min: 0, max: 10, step: 0.01 },
            { port: 1, symbol: "LEVEL", name: "Level", default: 0.5, min: 0, max: 1, step: 0.01 },
            { port: 2, symbol: "WET_DRY", name: "Dry/Wet", default: 100, min: 0, max: 100, step: 1 },
        ],
    },
];

export const FX_TOTAL_PARAMS = 197;

// --- 0..1 knob space <-> engine space (linear; log knobs would need per-param curves later) ---

function fxLookupParam(fxId: number, param: number): FxParamDef | null {
    const fx = FX_EFFECTS[fxId];
    if (!fx || !Number.isInteger(param) || param < 0 || param >= fx.params.length) return null;
    return fx.params[param];
}

function clamp01(v: number): number {
    return v < 0 ? 0 : v > 1 ? 1 : v;
}

/** 0..1 knob position → engine value (clamped; integer params round). */
export function fxParamFrom01(fxId: number, param: number, v01: number): number {
    const def = fxLookupParam(fxId, param);
    if (!def) return NaN;
    const v = def.min + clamp01(v01) * (def.max - def.min);
    const r = def.integer ? Math.round(v) : v;
    return r < def.min ? def.min : r > def.max ? def.max : r;
}

/** Engine value → 0..1 knob position (clamped). */
export function fxParamTo01(fxId: number, param: number, v: number): number {
    const def = fxLookupParam(fxId, param);
    if (!def) return NaN;
    const span = def.max - def.min;
    if (span === 0) return 0;
    return clamp01((v - def.min) / span);
}

/** Default value expressed in 0..1 knob space. */
export function fxParamDefault01(fxId: number, param: number): number {
    const def = fxLookupParam(fxId, param);
    if (!def) return NaN;
    return fxParamTo01(fxId, param, def.default);
}

// --- flat-mirror helpers (used by persistence + worklet bulk state) ---

/** Index into the flat FX_TOTAL_PARAMS mirror: cumulative offset + param. */
export function fxFlatIndex(fxId: number, param: number): number {
    const fx = FX_EFFECTS[fxId];
    if (!fx || !Number.isInteger(param) || param < 0 || param >= fx.params.length) return -1;
    return fx.offset + param;
}

export function isFxId(v: number): boolean {
    return Number.isInteger(v) && v >= 0 && v < FX_COUNT;
}
