/*
 * obxd-processor.tail.js — appended to the emcc-generated obxd_wasm.js
 * (and, since the combined-worklet migration, the emcc-generated
 * octopus_wasm.js concatenated ahead of it) at build time to produce a
 * single wasm/build/obxd-processor.js fed to audioWorklet.addModule().
 *
 * AudioWorkletGlobalScope disallows `importScripts()` (removed in Chrome 105+)
 * AND dynamic `import()` (rejected with "import() is disallowed on
 * WorkletGlobalScope"). So we cannot load the emcc module from a separate
 * file at runtime — we have to ship it in the same classic script the host
 * calls addModule() with. build.sh concatenates the two halves.
 *
 * When this file runs, the emcc JS above has already executed and defined
 * `ObxdModuleFactory` as a global function declaration (which becomes a
 * property of `self` in worklet scope). We invoke it; it returns a Promise
 * that resolves with the WASM module instance. Until that resolves, process()
 * returns silence.
 *
 * Combined worklet: the concatenated octopus_wasm.js also defines
 * `OctopusModuleFactory` in this same classic script. ensureOctopus()
 * (below) instantiates the sequencer against the shared WebAssembly.Memory
 * passed via processorOptions.octopusMemory (the glue is built with
 * -sIMPORTED_MEMORY), runs engine_init, optionally replays an initial
 * state blob, and builds the synth-ring views over the octopus module's
 * own heap. From then on the sequencer lives in this worklet: process()
 * pumps it once per 128-sample quantum BEFORE draining the synth ring (a
 * tick's MIDI lands in the synth in the same quantum), and while the
 * context is SUSPENDED (process() not yet called) the main thread drives
 * it with 'oct_pump' messages at RAF rate — ignored once audioDriven. An
 * octopus init failure posts {type:'error'} but never retires the node:
 * the synth path is independent and keeps running.
 *
 * Multi-instance (Phase A): _obxd_init creates 10 SynthEngine instances
 * in one WASM heap. Every MIDI/param/gain/fxp/etc message carries an
 * `instance_id` (0..9). The render path is unchanged — the C side sums
 * all 10 active engines into the master buffer with soft-clip and exposes
 * it via the same _get_buf_l_ptr / _get_buf_r_ptr that the cached HEAPF32
 * views already point at.
 *
 * Heavy/deferred execution: every mutating port message (params, gains,
 * fxp/PCM loads, bulk restores) is converted to a closure and pushed onto
 * the AwpTaskQueue (from src/awp-task-queue.js, concatenated above us in
 * this same classic script). process() drains it once per 128-sample
 * quantum with a budget of at most ONE heavy task (load_fxp, factory
 * patch, PCM load/clear) so those operations spread across frames
 * instead of blowing the ~2.9ms render deadline. Strict FIFO keeps a
 * set_param enqueued after a load_fxp applying AFTER it. Reply messages
 * (fxp_loaded, param_value, patch_name, the bulk dump/restored acks) are
 * posted from INSIDE the queued tasks so replies stay ordered relative
 * to the work. Only 'midi' (pendingMidi array), 'ping' (30Hz liveness
 * / meter read) and the cheap Octopus control messages (oct_key /
 * oct_rotary / ... — see the oct_* cases in port.onmessage) bypass the
 * queue; the two heavy Octopus FS round-trips (oct_save_state /
 * oct_load_state) go through it like every other load.
 *
 * IMPORTANT: This file is plain JS (not an ES module, not TypeScript) so it
 * can be loaded via AudioWorklet.addModule() which expects a classic script.
 */

// Top-level log — proves the combined file was parsed at addModule() time.
console.log('[obxd-processor] module evaluating');

// Restore-layout constants (OBXD_*) come from src/generated/restore-layout.js,
// concatenated into this same classic script by build.sh BEFORE this file.
// They are generated by tools/gen-param-table.mjs from tools/param-spec.mjs so
// the JS bulk dump/restore layout can never silently drift from the C side
// (main_obxd.cpp INSTANCE_COUNT / RESTORE_* defines). Legacy literals (10
// instances, 108 params, 432 drum stride, sentinels 200+) are gone.
const DEFAULT_INSTANCE_GAIN = 0.4 * 0.7;  // matches prior single-instance default (gainLinear * 0.4)

let wasmModule = null;
let initPromise = null;
let bufLPtr = 0;
let bufRPtr = 0;
let pendingMidi = [];   // queued via port.onmessage, drained in process()

const taskQueue = new AwpTaskQueue();   // from src/awp-task-queue.js (concatenated above us)

// SAB-based MIDI ring buffer (direct from Octopus sequencer, no main thread).
// Since the combined-worklet migration these views are built inside
// ensureOctopus() over the OCTOPUS module's own heap — the shared memory the
// main thread passes as processorOptions.octopusMemory — using the C-side
// ring/head/tail getters. The old processorOptions midiSab +
// midiSynth*Offset handoff is gone. The imported shared memory is not
// expected to grow, so the views are built once.
let midiSabRing = null;      // Uint32Array view over the octopus shared memory
let midiSabHead = null;      // Int32Array view (1 element)
let midiSabTail = null;      // Int32Array view (1 element)
const MIDI_SYNTH_RING_SIZE = 512;
const MIDI_SYNTH_RING_MASK = 511;
let midiRouting = null;      // array[17]: channel → bitmask of instance IDs (0 = unmapped)

// Cached HEAPF32 views into the WASM linear memory. The raw `wasmModule.HEAPF32`
// reference is replaced by emcc whenever WASM memory grows
// (-sALLOW_MEMORY_GROWTH=1), so we cache both the underlying ArrayBuffer
// (to detect the swap) and the typed-array view (to skip per-quantum
// allocation). Allocating two Float32Array views per process() call was a
// significant source of GC pressure and caused periodic audio glitches on
// sustained notes.
let heapF32Ref = null;     // the ArrayBuffer HEAPF32 is currently backed by
let bufLView = null;       // Float32Array view over g_master_l
let bufRView = null;       // Float32Array view over g_master_r

const RENDER_QUANTUM = 128;   // AWP quantum is fixed at 128 frames by spec

// --- Octopus sequencer engine state (combined worklet) ---
let octModule = null;        // Octopus WASM module (shared memory, engine)
let octReady = false;        // engine_init done, pointers valid
let audioDriven = false;     // true after first process() call; oct_pump ignored then
let octInitPromise = null;   // memoized ensureOctopus promise (mirrors initPromise)

// The pristine WebAssembly.instantiate, captured the first time any of our
// loader patches runs (see ensureModule / ensureOctopus). Patched variants
// must ALWAYS bottom out here — never in another patch — so the two
// factories can never substitute each other's WASM bytes.
let realInstantiate = null;

function ensureModule(wasmBytesArg) {
    if (initPromise) return initPromise;
    initPromise = (async () => {
        try {
            console.log('[obxd-processor] locating ObxdModuleFactory...');
            const factory = (typeof ObxdModuleFactory !== 'undefined') ? ObxdModuleFactory : null;
            if (typeof factory !== 'function') {
                throw new Error('ObxdModuleFactory not found after combined-script load (typeof=' + typeof factory + ')');
            }

            // emcc 6.x's WASM loader inside AudioWorkletGlobalScope is
            // unreachable from outside the factory closure — all of its
            // inner vars (`wasmBinary`, `readBinary`, `readAsync`, `fetch`)
            // are declared inside the factory function body, so we can't
            // monkey-patch them by bare name. We CAN monkey-patch
            // `WebAssembly.instantiateStreaming` itself (a real global),
            // which emcc calls with whatever `fetch()` returned. If we make
            // it succeed using our pre-fetched bytes, emcc's loader never
            // tries to call `fetch` for the binary.
            let prefetchedBytes = null;
            if (wasmBytesArg) {
                prefetchedBytes = wasmBytesArg instanceof Uint8Array
                    ? wasmBytesArg
                    : new Uint8Array(wasmBytesArg);
                const originalInstantiateStreaming = WebAssembly.instantiateStreaming;
                WebAssembly.instantiateStreaming = async function (_response, imports) {
                    console.log('[obxd-processor] instantiateStreaming patched -> using pre-fetched bytes');
                    return WebAssembly.instantiate(prefetchedBytes, imports);
                };
                // Also patch plain instantiate() in case emcc falls through
                // to its ArrayBuffer path: when called with imports object
                // (not a Module), swap in our bytes.
                const originalInstantiate = WebAssembly.instantiate;
                realInstantiate = originalInstantiate;   // shared with ensureOctopus (see its comment)
                WebAssembly.instantiate = async function (binaryOrModule, imports) {
                    if (imports && (!binaryOrModule || !(binaryOrModule instanceof WebAssembly.Module))) {
                        return originalInstantiate(prefetchedBytes, imports);
                    }
                    return originalInstantiate(binaryOrModule, imports);
                };
                console.log('[obxd-processor] pre-fetched WASM bytes injected (' + prefetchedBytes.byteLength + '); WebAssembly.instantiate patched');
            } else {
                console.warn('[obxd-processor] no pre-fetched WASM bytes; falling back to emcc default loader');
            }

            console.log('[obxd-processor] invoking factory...');
            const m = await factory({
                locateFile: (p) => '/' + p,
            });
            console.log('[obxd-processor] factory resolved; _exports:', Object.keys(m).filter(k => k.startsWith('_')).join(','));
            wasmModule = m;
            // _obxd_init now creates all 10 SynthEngine instances and
            // applies the matching factory patch to each. No additional
            // per-instance setup is required from the constructor beyond
            // seeding the default gain.
            wasmModule._obxd_init(sampleRate || 44100);
            bufLPtr = wasmModule._get_buf_l_ptr();
            bufRPtr = wasmModule._get_buf_r_ptr();
            // Default each instance to the prior single-instance default
            // gain (gainLinear * 0.4 where gainLinear was 0.7). The C side
            // has no "global gain" any more — every instance manages its
            // own VOLUME param, so we issue one set_gain per instance.
            for (let i = 0; i < OBXD_INSTANCE_COUNT; i++) {
                wasmModule._obxd_set_gain(i, DEFAULT_INSTANCE_GAIN);
            }
            // Seed the cached views now that WASM is up.
            heapF32Ref = wasmModule.HEAPF32.buffer;
            bufLView = new Float32Array(heapF32Ref, bufLPtr, RENDER_QUANTUM);
            bufRView = new Float32Array(heapF32Ref, bufRPtr, RENDER_QUANTUM);
            console.log('[obxd-processor] WASM ready, bufLPtr=' + bufLPtr + ' bufRPtr=' + bufRPtr + ' instances=' + OBXD_INSTANCE_COUNT);
        } catch (e) {
            console.error('[obxd-processor] WASM load failed:', e && e.message, e && e.stack);
            throw e;
        }
    })();
    return initPromise;
}

// ---------------------------------------------------------------------------
// Octopus sequencer engine (combined-worklet migration)
// ---------------------------------------------------------------------------

// Async init for the Octopus engine, mirroring ensureModule above. Key
// differences from the obxd path:
//
//   * bytes AND memory arrive via processorOptions (octopusWasmBinary /
//     octopusMemory) — the octopus glue is built with -sIMPORTED_MEMORY, so
//     the factory config takes `wasmMemory` and the module imports the main
//     thread's shared WebAssembly.Memory. From then on one heap is shared
//     between the main thread (MIR/status rendering) and this worklet.
//   * after engine_init we optionally replay an initial state blob, then
//     build the synth-ring views over the module's OWN heap — the ring the
//     pump writes and process() drains lives in that same shared memory.
//   * failure rethrows to the constructor's .catch, which posts
//     {type:'error'} WITHOUT setting alive=false — the synth path must
//     survive a sequencer-only failure.
//
// Loader patching mirrors ensureModule's trick (patch the WebAssembly
// globals emcc's inner loader calls — its closure vars are unreachable from
// outside the factory), but SCOPED: installed right before the factory call
// and restored in a finally. We also await the obxd initPromise FIRST:
// ensureModule's patches stay installed forever and close over the obxd
// bytes, so if both factories were in flight at once, whichever patch was
// installed when a factory's instantiate fired would win and could hand the
// OTHER module the wrong bytes. Serializing after obxd settles and
// restoring afterwards closes that window; both patched variants bottom out
// at `realInstantiate` (the pristine builtin captured at first patch) so
// they can never chain into each other even if the timing assumptions
// change.
function ensureOctopus(opts) {
    if (octInitPromise) return octInitPromise;
    octInitPromise = (async () => {
        const port = opts && opts.port;
        try {
            // Let the obxd instantiate finish first (see the function
            // comment). A rejected obxd init must not block the sequencer —
            // swallow and continue.
            try { if (initPromise) await initPromise; } catch (e) { /* obxd failed; octopus still boots */ }

            console.log('[obxd-processor] locating OctopusModuleFactory...');
            const factory = (typeof OctopusModuleFactory !== 'undefined') ? OctopusModuleFactory : null;
            if (typeof factory !== 'function') {
                throw new Error('OctopusModuleFactory not found after combined-script load (typeof=' + typeof factory + ')');
            }

            const octBytes = opts.wasmBinary instanceof Uint8Array
                ? opts.wasmBinary
                : new Uint8Array(opts.wasmBinary);

            const prevStreaming = WebAssembly.instantiateStreaming;
            const prevInstantiate = WebAssembly.instantiate;
            if (!realInstantiate) realInstantiate = prevInstantiate;
            WebAssembly.instantiateStreaming = async function (_response, imports) {
                console.log('[obxd-processor] octopus instantiateStreaming patched -> using pre-fetched bytes');
                return realInstantiate(octBytes, imports);
            };
            // Same fall-through guard as ensureModule's plain-instantiate
            // patch: when called with real bytes (wasmBinary was in the
            // factory config), pass them through untouched.
            WebAssembly.instantiate = async function (binaryOrModule, imports) {
                if (imports && (!binaryOrModule || !(binaryOrModule instanceof WebAssembly.Module))) {
                    return realInstantiate(octBytes, imports);
                }
                return realInstantiate(binaryOrModule, imports);
            };
            console.log('[obxd-processor] octopus loader patched (' + octBytes.byteLength + ' pre-fetched bytes, imported shared memory)');

            try {
                const m = await factory({
                    wasmBinary: octBytes,
                    wasmMemory: opts.memory,
                    locateFile: (p) => '/' + p,
                });

                // Sequencer timebase: _octopus_pump converts audio-quantum
                // sample deltas into 48-PPQN ticks, so it needs the exact
                // context sample rate.
                m._octopus_set_sample_rate(sampleRate || 48000);

                // /persistent is the engine's state slot (the octopus glue
                // keeps -sFORCE_FILESYSTEM=1). mkdir throws when the dir
                // already exists — swallow and move on.
                try { m.FS.mkdir('/persistent'); } catch (e) { /* already exists */ }

                m._engine_init();

                // Optional initial state (saved project handed over by the
                // main thread): stage the bytes into the FS, then replay
                // through the engine's normal load path.
                const initialState = opts.initialState;
                if (initialState && initialState.length) {
                    m.FS.writeFile('/persistent/octopus_state.bin', initialState);
                    m._wasm_load_state();
                }

                // Synth-ring views, built over the octopus module's own heap
                // (HEAPU8.buffer IS the shared memory's buffer) from the
                // C-side getters. process() drains this ring right after
                // pumping the engine — same quantum, same memory.
                midiSabRing = new Uint32Array(m.HEAPU8.buffer, m._get_midi_synth_ring_ptr(), MIDI_SYNTH_RING_SIZE);
                midiSabHead = new Int32Array(m.HEAPU8.buffer, m._get_midi_synth_ring_head_ptr(), 1);
                midiSabTail = new Int32Array(m.HEAPU8.buffer, m._get_midi_synth_ring_tail_ptr(), 1);
                console.log('[obxd-processor] octopus synth-ring views connected (ring ptr ' + m._get_midi_synth_ring_ptr() + ')');

                octModule = m;
                octReady = true;

                // Engine is up — tell the main thread. It builds its OWN
                // views (MIR rendering, status reads) over the SAME shared
                // memory it passed as processorOptions.octopusMemory, using
                // these byte offsets; no per-frame posting needed.
                port.postMessage({
                    type: 'oct_ready',
                    mirPtr: m._get_mir_ptr(),
                    processedMirPtr: m._get_processed_mir_ptr(),
                    statusPtr: m._get_status_ptr(),
                });
                console.log('[obxd-processor] octopus engine ready');
            } finally {
                // Restore whatever was installed before us (the obxd-era
                // patches, or the pristine builtins) — see the function
                // comment for why the patch must be scoped.
                WebAssembly.instantiateStreaming = prevStreaming;
                WebAssembly.instantiate = prevInstantiate;
            }
        } catch (e) {
            console.error('[obxd-processor] octopus WASM load failed:', e && e.message, e && e.stack);
            throw e;
        }
    })();
    return octInitPromise;
}

class ObxdProcessor extends AudioWorkletProcessor {
    constructor(options) {
        super(options);
        this.alive = true;

        const reportError = (e) => {
            this.port.postMessage({
                type: 'error',
                message: String(e && e.message || e),
                stack: String(e && e.stack || ''),
            });
        };

        // The main thread pre-fetches the WASM and passes the bytes via
        // processorOptions — this is the only reliable way to get binary
        // into AudioWorkletGlobalScope (no XHR, no fetch-needed).
        const wasmBytesArg = options && options.processorOptions && options.processorOptions.wasmBinary;
        console.log('[obxd-processor] constructor; options.processorOptions =', options && options.processorOptions ? Object.keys(options.processorOptions).join(',') : 'none',
            '; wasmBytesArg type:', typeof wasmBytesArg,
            '; byteLength:', wasmBytesArg ? wasmBytesArg.byteLength : 0);

        // Default routing: channels 1-10 → instances 0-9 (bitmask: bit i = instance i)
        midiRouting = new Array(17).fill(0);
        for (let i = 0; i < OBXD_INSTANCE_COUNT; i++) midiRouting[i + 1] = (1 << i);

        ensureModule(wasmBytesArg).then(() => {
            this.port.postMessage({ type: 'ready' });
        }).catch((e) => {
            reportError(e);
            this.alive = false;
        });

        // Boot the Octopus sequencer engine in this same worklet. The main
        // thread passes the pre-fetched octopus WASM bytes, the shared
        // WebAssembly.Memory the module imports, and an optional initial
        // state blob. ensureOctopus() (which waits for the obxd factory
        // above to settle first — see its comment) builds the synth-ring
        // views over the octopus heap itself; the old processorOptions
        // midiSab/midiSynth*Offset keys are gone. A sequencer-only failure
        // posts {type:'error'} but deliberately does NOT set alive=false.
        const octProcOpts = options && options.processorOptions;
        const octBytesArg = octProcOpts ? octProcOpts.octopusWasmBinary : null;
        const octMemArg = octProcOpts ? octProcOpts.octopusMemory : null;
        const octInitialState = octProcOpts ? octProcOpts.octopusInitialState : null;
        if (octBytesArg && octMemArg) {
            ensureOctopus({
                wasmBinary: octBytesArg,
                memory: octMemArg,
                initialState: octInitialState,
                port: this.port,
            }).catch((e) => {
                reportError(e);   // posts {type:'error',...}; alive stays true
            });
        }

        // Per-instance message routing. Every command carries an
        // instance_id (0..9) so the C side can dispatch to the right
        // SynthEngine. MIDI is queued and drained at the top of process()
        // so we don't interrupt the audio thread with allocator/GC work
        // mid-quantum.
        this.port.onmessage = (ev) => {
            const msg = ev.data;
            if (!msg) return;
            const id = (typeof msg.instance_id === 'number') ? (msg.instance_id | 0) : 0;
            switch (msg.type) {
                case 'midi':
                    // Queued; msg must carry {instance_id, status, d1, d2}.
                    // Drained in process() so we don't dispatch from the
                    // message thread while the audio thread is mid-render.
                    pendingMidi.push(msg);
                    break;
                case 'set_routing':
                    taskQueue.push(() => {
                        if (msg.routing && Array.isArray(msg.routing)) {
                            midiRouting = msg.routing.slice();
                        }
                    });
                    break;
                case 'set_active':
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_active(id, msg.active ? 1 : 0);
                    });
                    break;
                case 'set_polyphony':
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_polyphony(id, msg.voice_count | 0);
                    });
                    break;
                case 'set_mpe':
                    // Per-instance MPE flag (T9). Stored on the C side in
                    // g_mpe_enabled[id]; the engine is channel-aware but the
                    // actual per-channel dispatch arrives in T20. For now
                    // obxd_midi_in still passes channel=0 regardless.
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_mpe(id, msg.enabled ? 1 : 0);
                    });
                    break;
                case 'set_mod_wheel':
                    // Fix 2: reserved CC 1 direct routing. value is 0..1.
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_mod_wheel(id, +msg.value);
                    });
                    break;
                case 'set_sustain':
                    // Fix 2: reserved CC 64 direct routing. enabled is 0/1.
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_sustain(id, msg.enabled ? 1 : 0);
                    });
                    break;
                case 'set_mpe_glide_range':
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_mpe_glide_range(id, msg.semitones | 0);
                    });
                    break;
                case 'set_matrix_row':
                    taskQueue.push(() => {
                        if (wasmModule && typeof msg.row === 'number'
                                && typeof msg.src === 'string' && typeof msg.tgt === 'string'
                                && typeof msg.depth === 'number') {
                            wasmModule._obxd_set_matrix_row(id, msg.row | 0, msg.src, msg.tgt, +msg.depth);
                        }
                    });
                    break;
                case 'clear_matrix_row':
                    taskQueue.push(() => {
                        if (wasmModule && typeof msg.row === 'number') {
                            wasmModule._obxd_clear_matrix_row(id, msg.row | 0);
                        }
                    });
                    break;
                case 'set_param':
                    // idx is a ParamsEnum.h value; value is 0..1. Forwarded
                    // directly to the engine. Useful for runtime patch tweaks.
                    taskQueue.push(() => {
                        if (wasmModule && typeof msg.idx === 'number' && typeof msg.value === 'number') {
                            wasmModule._obxd_set_param(id, msg.idx | 0, +msg.value);
                        }
                    });
                    break;
                case 'gain':
                    // UI sends 0..1; we scale down so the slider's max isn't
                    // deafening (engine's processVolume maps 0..1 -> 0..0.30).
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_gain(id, Math.max(0, Math.min(1, +msg.value)) * 0.4);
                    });
                    break;
                case 'load_fxp': {
                    // Phase 4 — load a VST2 preset file into one instance.
                    // The main thread sends the raw .fxp bytes as a
                    // Uint8Array; we copy them into WASM linear memory
                    // via _malloc + HEAPU8.set (the worklet can't read the
                    // FS — emcc was built with -sFORCE_FILESYSTEM=0), then
                    // hand the pointer to the C loader. Reply with the
                    // parsed patch name (or an error code) so the UI can
                    // update its label. HEAVY: _malloc + XML parse can blow
                    // the render quantum — deferred, one per drain.
                    const bytes = msg.bytes;
                    taskQueue.push(() => {
                        if (!wasmModule || !bytes || !bytes.length) {
                            this.port.postMessage({ type: 'fxp_loaded', instance_id: msg.instance_id, success: false, rc: -1, name: '' });
                            return;
                        }
                        let rc = -1, name = '';
                        try {
                            const ptr = wasmModule._malloc(bytes.length);
                            if (!ptr) throw new Error('_malloc returned 0');
                            wasmModule.HEAPU8.set(bytes, ptr);
                            rc = wasmModule._obxd_load_fxp(id, ptr, bytes.length);
                            wasmModule._free(ptr);
                            name = wasmModule.UTF8ToString(wasmModule._obxd_get_patch_name(id)) || '';
                        } catch (e) {
                            console.error('[obxd-processor] load_fxp threw:', e && e.message);
                            rc = -128;
                        }
                        this.port.postMessage({
                            type: 'fxp_loaded',
                            instance_id: msg.instance_id,
                            success: rc === 0,
                            rc,
                            name,
                        });
                    }, true);
                    break;
                }
                case 'set_factory_patch':
                    // HEAVY: deletes + recreates a SynthEngine (32-voice
                    // array) on the C side.
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_factory_patch(id, msg.patch_id | 0);
                    }, true);
                    break;
                case 'panic':
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_panic(id);
                    });
                    break;
                case 'panic_all':
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_panic_all();
                    });
                    break;
                case 'reset_patch':
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_reset_patch(id);
                    });
                    break;
                case 'get_param':
                    taskQueue.push(() => {
                        if (wasmModule && typeof msg.idx === 'number') {
                            const v = wasmModule._obxd_get_param(id, msg.idx | 0);
                            this.port.postMessage({ type: 'param_value', instance_id: msg.instance_id, idx: msg.idx | 0, value: v });
                        }
                    });
                    break;
                // Bulk param dump/restore for state persistence (save/load).
                // Single round-trip for all instances × OBXD_RESTORE_STRIDE params.
                case 'dump_all_params': {
                    taskQueue.push(() => {
                        const total = OBXD_INSTANCE_COUNT * OBXD_RESTORE_STRIDE;
                        const params = new Array(total);
                        if (wasmModule) {
                            for (let i = 0; i < OBXD_INSTANCE_COUNT; i++) {
                                const base = i * OBXD_RESTORE_STRIDE;
                                for (let p = 0; p < OBXD_LEGACY_PARAM_COUNT; p++)
                                    params[base + p] = wasmModule._obxd_get_param(i, p);
                                for (let n = 0; n < OBXD_NEW_PARAM_COUNT; n++)
                                    params[base + OBXD_LEGACY_PARAM_COUNT + n] = wasmModule._obxd_get_param(i, OBXD_NEW_PARAM_BASE + n);
                            }
                        } else {
                            params.fill(0);
                        }
                        this.port.postMessage({ type: 'all_params_dumped', params });
                    });
                    break;
                }
                // Bulk full-state restore (state persistence) — ENGINE-OWNED
                // ordering. One HEAVY task commits both arrays into C-side
                // staging buffers via _obxd_restore_stage(0, ...); LIGHT tasks
                // then run stages 1..4 in order. The C side owns ALL restore
                // ordering semantics, including the instance-9 drum-structural
                // skip + finalize that this file's old DRUM_STRUCTURAL_SKIP set
                // and app-state's reassertDrumInstanceStructural call used to
                // enforce (see obxd_restore_stage in wasm/obxd/main_obxd.cpp).
                //
                // drumParams == null → synth-only restore: stage 0 marks the
                // drum data absent and stages 3/4 become C-side no-ops (they
                // still run so the C state machine completes and resets).
                // Synth-only restores are used on paths that never had drum
                // state, so no instance-9 structural finalize is wanted there.
                case 'restore_all_state': {
                    if (!wasmModule || !Array.isArray(msg.synthParams)
                            || msg.synthParams.length !== OBXD_INSTANCE_COUNT * OBXD_RESTORE_STRIDE) {
                        // preserve the old restore handlers' behavior shape:
                        // still post the reply
                        this.port.postMessage({ type: 'all_state_restored' });
                        break;
                    }
                    const synthParams = msg.synthParams;
                    const drumParams = Array.isArray(msg.drumParams) ? msg.drumParams : null;
                    let commitFailed = false;
                    // HEAVY: _malloc + two HEAPF32.set copies (up to 4536
                    // floats) + the C-side stage-0 memcpy into the static
                    // staging buffers — deferred, one per drain. The heap
                    // copies are freed right after stage 0 returns; later
                    // stages read only the C-owned staging buffers.
                    taskQueue.push(() => {
                        try {
                            const synthPtr = wasmModule._malloc(synthParams.length * 4);
                            const drumPtr = drumParams ? wasmModule._malloc(drumParams.length * 4) : 0;
                            wasmModule.HEAPF32.set(synthParams, synthPtr >> 2);
                            if (drumPtr) wasmModule.HEAPF32.set(drumParams, drumPtr >> 2);
                            const rc = wasmModule._obxd_restore_stage(
                                0, synthPtr, synthParams.length,
                                drumPtr, drumParams ? drumParams.length : 0);
                            wasmModule._free(synthPtr);
                            if (drumPtr) wasmModule._free(drumPtr);
                            if (rc < 0) {
                                console.error('[obxd-processor] restore stage 0 failed rc=' + rc);
                                commitFailed = true;
                            }
                        } catch (e) {
                            console.error('[obxd-processor] restore_all_state commit threw:', e && e.message);
                            commitFailed = true;
                        }
                    }, true);
                    // LIGHT: stages 1..4 in order (each ~540 bounded setter
                    // calls). FIFO guarantees they run after the commit and
                    // before the reply. Passing 0/0 for the pointers — later
                    // stages read the C-owned staging buffers only.
                    for (let st = 1; st <= 4; st++) {
                        taskQueue.push(() => {
                            if (commitFailed) return;
                            const rc = wasmModule._obxd_restore_stage(st, 0, 0, 0, 0);
                            if (rc < 0) console.error('[obxd-processor] restore stage ' + st + ' failed rc=' + rc);
                        });
                    }
                    taskQueue.push(() => {
                        this.port.postMessage({ type: 'all_state_restored' });
                    });
                    break;
                }
                // Bulk drum layer param dump/restore (state persistence).
                // Dumps OBXD_DRUM_PADS × OBXD_DRUM_LAYERS × OBXD_RESTORE_STRIDE params
                // (legacy + new per instance stride).
                case 'dump_drum_params': {
                    taskQueue.push(() => {
                        const dtotal = OBXD_DRUM_PADS * OBXD_DRUM_LAYERS * OBXD_RESTORE_STRIDE;
                        const dparams = new Array(dtotal);
                        if (wasmModule) {
                            for (let dpad = 0; dpad < OBXD_DRUM_PADS; dpad++) {
                                for (let dlayer = 0; dlayer < OBXD_DRUM_LAYERS; dlayer++) {
                                    const dbase = dpad * OBXD_DRUM_STRIDE + dlayer * OBXD_RESTORE_STRIDE;
                                    for (let dp = 0; dp < OBXD_LEGACY_PARAM_COUNT; dp++) {
                                        // Drum globals are dumped via the synth-params path
                                        // (instance 9) — emitting them here would duplicate
                                        // state that must not be restored per-layer. Write 0
                                        // into skipped slots so the length stays
                                        // pads*layers*stride.
                                        if (wasmModule._obxd_is_global_drum_param(dp)) { dparams[dbase + dp] = 0; continue; }
                                        dparams[dbase + dp] = wasmModule._obxd_get_drum_layer_param(dpad, dlayer, dp);
                                    }
                                    for (let dn = 0; dn < OBXD_NEW_PARAM_COUNT; dn++) {
                                        // NEW-param drum globals (verified:
                                        // UnisonVoices, VoiceReassign,
                                        // VibratoWave, LFO1PW) route live to
                                        // instance 9 — dumping per-layer
                                        // values for them would duplicate
                                        // engine state, exactly like the
                                        // legacy globals above. Write 0 into
                                        // their slots (the C-side restore,
                                        // stage 3, skips them) so the length
                                        // stays pads*layers*stride.
                                        if (wasmModule._obxd_is_global_drum_param(OBXD_NEW_PARAM_BASE + dn)) { dparams[dbase + OBXD_LEGACY_PARAM_COUNT + dn] = 0; continue; }
                                        dparams[dbase + OBXD_LEGACY_PARAM_COUNT + dn] = wasmModule._obxd_get_drum_layer_param(dpad, dlayer, OBXD_NEW_PARAM_BASE + dn);
                                    }
                                }
                            }
                        } else {
                            dparams.fill(0);
                        }
                        this.port.postMessage({ type: 'drum_params_dumped', params: dparams });
                    });
                    break;
                }
                // NOTE: drum params are RESTORED via the combined
                // 'restore_all_state' handler above (engine-owned staging);
                // only the dump side remains separate ('dump_drum_params').
                // OctOBX PCM — per-drum-layer full-param get/set (mirrors get_param / set_param).
                case 'set_drum_layer_param':
                    taskQueue.push(() => {
                        if (wasmModule && typeof msg.idx === 'number' && typeof msg.value === 'number') {
                            wasmModule._obxd_set_drum_layer_param(msg.pad | 0, msg.layer | 0, msg.idx | 0, +msg.value);
                        }
                    });
                    break;
                case 'get_drum_layer_param':
                    taskQueue.push(() => {
                        if (wasmModule && typeof msg.idx === 'number') {
                            const val = wasmModule._obxd_get_drum_layer_param(msg.pad | 0, msg.layer | 0, msg.idx | 0);
                            this.port.postMessage({ type: 'drum_layer_param_value', instance_id: msg.instance_id, pad: msg.pad | 0, layer: msg.layer | 0, idx: msg.idx | 0, value: val });
                        }
                    });
                    break;
                case 'get_patch_name': {
                    taskQueue.push(() => {
                        let name = '';
                        if (wasmModule) {
                            try { name = wasmModule.UTF8ToString(wasmModule._obxd_get_patch_name(id)) || ''; }
                            catch (e) { name = ''; }
                        }
                        this.port.postMessage({ type: 'patch_name', instance_id: msg.instance_id, name });
                    });
                    break;
                }
                case 'ping': {
                    const meters = new Array(OBXD_INSTANCE_COUNT);
                    const voices = new Array(OBXD_INSTANCE_COUNT);
                    if (wasmModule) {
                        for (let i = 0; i < OBXD_INSTANCE_COUNT; i++) {
                            meters[i] = wasmModule._obxd_get_instance_rms(i);
                            voices[i] = wasmModule._obxd_get_voice_activity(i) >>> 0;
                        }
                    } else {
                        for (let i = 0; i < OBXD_INSTANCE_COUNT; i++) { meters[i] = 0.0; voices[i] = 0; }
                    }
                    this.port.postMessage({
                        type: 'pong',
                        alive: this.alive,
                        ready: wasmModule !== null,
                        meters,
                        voiceActivity: voices,
                        bufLPtr,
                        bufRPtr,
                    });
                    break;
                }
                // OctOBX PCM
                case 'load_pcm': {
                    // msg = {instance_id, pad, layer, pcmL: Float32Array, frames}
                    // HEAVY: _malloc + a large HEAPF32.set can blow the
                    // render quantum — deferred, one per drain.
                    const pcmL = msg.pcmL;
                    taskQueue.push(() => {
                        if (!wasmModule || !pcmL || !pcmL.length) return;
                        const size = msg.frames * 4;
                        const ptr = wasmModule._malloc(size);
                        wasmModule.HEAPF32.set(pcmL, ptr >> 2);
                        wasmModule._obxd_load_pcm(id, msg.pad | 0, msg.layer | 0, ptr, msg.frames | 0);
                        // WASM takes ownership of the pointer — do NOT free
                    }, true);
                    break;
                }
                case 'set_pcm_layer':
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_pcm_layer(id, msg.pad | 0, msg.layer | 0,
                            +msg.gain, +msg.cutoff, +msg.res, +msg.mode,
                            +msg.aA, +msg.aD, +msg.aS, +msg.aR, +msg.pan, +msg.pitch);
                    });
                    break;
                case 'set_pcm_note_map':
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_pcm_note_map(id, msg.note | 0, msg.pad | 0);
                    });
                    break;
                case 'set_pcm_layer_count':
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_pcm_layer_count(id, msg.pad | 0, msg.count | 0);
                    });
                    break;
                case 'set_pcm_choke':
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_set_pcm_choke(id, msg.pad | 0, msg.group | 0);
                    });
                    break;
                case 'clear_pcm':
                    // HEAVY: frees the per-pad PCM banks.
                    taskQueue.push(() => {
                        if (wasmModule) wasmModule._obxd_clear_pcm(id);
                    }, true);
                    break;
                // ------------------------------------------------------------------
                // Octopus sequencer engine messages (combined worklet).
                //
                // These are cheap and latency-sensitive, so they run INLINE
                // — NOT through taskQueue — EXCEPT the two heavy FS
                // round-trips further down (oct_save_state / oct_load_state).
                // Every handler null-guards on octModule/octReady so a
                // failed (or not-yet-finished) sequencer init is a silent
                // no-op for the synth path.
                // ------------------------------------------------------------------
                case 'oct_key':
                    // UI key press → firmware interpreter. The SAVE key
                    // latches a one-shot "state saved" flag inside the
                    // engine; when it fires we forward the persisted bytes
                    // to the main thread in the same message turn.
                    if (!octModule || !octReady) return;
                    try {
                        octModule._wasm_key_press(msg.key | 0, msg.press ? 1 : 0);
                        if (octModule._wasm_consume_state_saved()) {
                            const savedBytes = octModule.FS.readFile('/persistent/octopus_state.bin');
                            this.port.postMessage({ type: 'oct_state_saved', bytes: savedBytes });
                        }
                    } catch (e) {
                        console.error('[obxd-processor] oct_key threw:', e && e.message);
                    }
                    break;
                case 'oct_rotary':
                    if (!octModule || !octReady) return;
                    octModule._wasm_rotary(msg.idx | 0, msg.dir | 0);
                    break;
                case 'oct_transport':
                    if (!octModule || !octReady) return;
                    octModule._wasm_transport(msg.running ? 1 : 0);
                    break;
                case 'oct_pause':
                    if (!octModule || !octReady) return;
                    octModule._wasm_pause();
                    break;
                case 'oct_tempo':
                    if (!octModule || !octReady) return;
                    if (typeof msg.bpm === 'number') octModule._wasm_set_tempo(+msg.bpm);
                    break;
                case 'oct_zoom':
                    if (!octModule || !octReady) return;
                    octModule._wasm_set_zoom(msg.level | 0);
                    break;
                case 'oct_midi_in':
                    // Hardware MIDI in: feeds the firmware's byte-at-a-time
                    // running-status interpreters.
                    if (!octModule || !octReady) return;
                    octModule._wasm_midi_input(msg.status | 0, msg.d1 | 0, msg.d2 | 0);
                    break;
                case 'oct_shutdown':
                    if (!octModule || !octReady) return;
                    octModule._wasm_shutdown();
                    break;
                case 'oct_pump':
                    // RAF-rate pump for the SUSPENDED-context case: while
                    // process() is not being called (context suspended, e.g.
                    // before the first user gesture), the main thread posts
                    // elapsed-milliseconds messages and we convert them to
                    // sample deltas at the context rate. Clamped to 1..100ms
                    // so a stalled main thread can't request a huge catch-up
                    // burst. Once process() has run at least once
                    // (audioDriven) audio owns the clock and these are
                    // dropped on the floor.
                    if (!audioDriven && octModule && octReady) {
                        const ms = Math.max(1, Math.min(100, +msg.ms | 0));
                        octModule._octopus_pump(Math.round(ms / 1000 * (sampleRate || 48000)));
                        // process() is the ONLY other drain site for the
                        // deferred task queue — while the context is
                        // suspended nothing runs it, so oct_save_state /
                        // oct_load_state (and the synth-side bulk restores)
                        // would sit queued forever and their main-thread
                        // requesters would time out. Drain with the same
                        // per-call budget process() uses; once audio drives
                        // the pump this branch (and drain) stops firing.
                        taskQueue.drain(1);
                    }
                    break;
                case 'oct_save_state':
                    // HEAVY: full sequencer state flush into MEMFS + the
                    // file read back across the heap — deferred, one per
                    // drain. Always replies; bytes:null on any failure
                    // (including engine-not-ready) so the requester can't
                    // hang waiting for bytes.
                    taskQueue.push(() => {
                        let outBytes = null;
                        try {
                            if (octModule && octReady) {
                                octModule._wasm_save_state();
                                outBytes = octModule.FS.readFile('/persistent/octopus_state.bin');
                            }
                        } catch (e) {
                            console.error('[obxd-processor] oct_save_state threw:', e && e.message);
                            outBytes = null;
                        }
                        this.port.postMessage({ type: 'oct_state_bytes', bytes: outBytes });
                    }, true);
                    break;
                case 'oct_load_state': {
                    // HEAVY: heap copy in + full engine replay — deferred,
                    // one per drain. Always replies with ok (false covers
                    // missing bytes, not-ready, and throws).
                    const inBytes = msg.bytes;
                    taskQueue.push(() => {
                        let ok = false;
                        try {
                            if (octModule && octReady && inBytes && inBytes.length) {
                                octModule.FS.writeFile('/persistent/octopus_state.bin', inBytes);
                                octModule._wasm_load_state();
                                ok = true;
                            }
                        } catch (e) {
                            console.error('[obxd-processor] oct_load_state threw:', e && e.message);
                            ok = false;
                        }
                        this.port.postMessage({ type: 'oct_state_loaded', ok });
                    }, true);
                    break;
                }
                case 'oct_snapshot':
                    // Test hook: full processed-MIR + status readback. The
                    // status block is an int32 array at _get_status_ptr()
                    // ([0]=engine_ready, [1]=run_bit, [2]=tempo,
                    // [3]=zoom_level, [4]=tick_count, [5]=midi_dropped,
                    // [6]=midi_synth_dropped; double at byte offset 32 =
                    // tick_ns). Read straight off the shared heap.
                    if (!octModule || !octReady) return;
                    try {
                        const status = new Int32Array(octModule.HEAPU8.buffer, octModule._get_status_ptr(), 7);
                        const mir = Array.from(new Uint8Array(octModule.HEAPU8.buffer, octModule._get_processed_mir_ptr(), 170));
                        this.port.postMessage({
                            type: 'oct_snapshot',
                            mir,
                            runBit: status[1],
                            tempo: status[2],
                            zoom: status[3],
                            tickCount: status[4] >>> 0,
                        });
                    } catch (e) {
                        console.error('[obxd-processor] oct_snapshot threw:', e && e.message);
                    }
                    break;
                default:
                    break;
            }
        };

        this.port.postMessage({ type: 'constructed' });
    }

    process(_inputs, outputs) {
        // Octopus sequencer pump — FIRST, before the synth-ring drain below,
        // so a tick generated this quantum lands in the synth in this same
        // quantum (the ring the pump writes into is the ring the drain
        // reads). Also latches audioDriven: from now on the engine is
        // clocked by audio and main-thread 'oct_pump' messages are ignored.
        audioDriven = true;
        if (octModule && octReady) octModule._octopus_pump(RENDER_QUANTUM);

        if (!this.alive) return false;   // retire node on fatal init failure
        if (!wasmModule) return true;    // still loading; output silence

        const out = outputs[0];
        if (!out || out.length === 0) return true;

        // Read MIDI events directly from the Octopus SAB ring buffer.
        // This runs BEFORE the pendingMidi drain so the lowest-latency path
        // (lock-free, no main-thread round trip) always wins. System
        // real-time (status >= 0xF0) is skipped — those have no channel.
        if (midiSabRing && midiSabHead && midiSabTail && wasmModule) {
            const tail = Atomics.load(midiSabTail, 0);
            let head = Atomics.load(midiSabHead, 0);
            const hwBatch = [];
            while (head !== tail) {
                const packed = Atomics.load(midiSabRing, head);
                const status = packed & 0xff;
                if (status < 0xf0) {
                    const channel = (packed >> 24) & 0xff;
                    const mask = midiRouting[channel];
                    if (mask) {
                        const d1 = (packed >> 8) & 0xff;
                        const d2 = (packed >> 16) & 0xff;
                        let m = mask, bit = 0;
                        while (m) {
                            if (m & 1) wasmModule._obxd_midi_in(bit, status, d1, d2);
                            m >>>= 1;
                            bit++;
                        }
                    }
                }
                hwBatch.push(packed);
                head = (head + 1) & MIDI_SYNTH_RING_MASK;
            }
            Atomics.store(midiSabHead, 0, head);
            if (hwBatch.length > 0) {
                this.port.postMessage({ type: 'hw_midi', packed: hwBatch });
            }
        }

        // Drain queued MIDI into the engine before rendering this quantum.
        // Timing granularity is the 128-sample AWP quantum (~2.9ms @
        // 44.1kHz) — well below perceptible MIDI jitter. Each message
        // carries its own instance_id so the right SynthEngine receives it.
        if (pendingMidi.length > 0) {
            for (let i = 0; i < pendingMidi.length; i++) {
                const m = pendingMidi[i];
                const id = (typeof m.instance_id === 'number') ? (m.instance_id | 0) : 0;
                wasmModule._obxd_midi_in(id, m.status | 0, m.d1 | 0, m.d2 | 0);
            }
            pendingMidi.length = 0;
        }

        // Run deferred port messages (budgeted: light tasks flow freely, at most
        // `1` heavy task per quantum). Placed before render so param changes
        // applied here take effect in this quantum.
        taskQueue.drain(1);

        // Renders every active engine, sums into g_master_l/r, applies
        // soft-clip — all inside the C side. The worklet doesn't need to
        // know there are 10 instances; it just sees the master buffer.
        wasmModule._obxd_render(RENDER_QUANTUM);

        // Refresh cached views if WASM memory grew (HEAPF32 buffer swapped).
        // This is rare but can happen under ALLOW_MEMORY_GROWTH=1.
        const currentBuf = wasmModule.HEAPF32.buffer;
        if (currentBuf !== heapF32Ref) {
            heapF32Ref = currentBuf;
            bufLView = new Float32Array(currentBuf, bufLPtr, RENDER_QUANTUM);
            bufRView = new Float32Array(currentBuf, bufRPtr, RENDER_QUANTUM);
        }

        if (out[0]) out[0].set(bufLView);
        if (out[1]) out[1].set(bufRView);

        return true;
    }
}

registerProcessor('obxd-processor', ObxdProcessor);
console.log('[obxd-processor] registerProcessor called');
