/**
 * obxf-layout.ts — OB-Xf editor UI layout spec (read-only data module).
 *
 * SOURCE ATTRIBUTION:
 *   Auto-extracted by an opencode "OB-Xf UI layout explorer" task that read the
 *   OB-Xf (Surge Synthesizer Team) source tree and emitted a TypeScript layout
 *   spec. Persisted here verbatim so downstream UI agents can consume the spec
 *   without re-running the explorer.
 *
 * GENERATION DATE: 2026-07-26
 *
 * SOURCE FILES (OB-Xf tree, read-only, GPL-3.0-or-later):
 *   - third_party/OB-Xf/assets/binary/VectorTheme/theme.xml
 *       every widget x/y/w/h/d/fh
 *   - third_party/OB-Xf/src/editor/ObxfEditorLayout.cpp
 *       registry → SynthParam::ID mapping + panel-group definitions
 *   - third_party/OB-Xf/src/parameter/SynthParam.h
 *       ID strings (case-sensitive, streaming) + display Names
 *   - third_party/OB-Xf/src/parameter/ParameterList.h
 *       defaults, ranges, choices, feature flags
 *   - third_party/OB-Xf/src/editor/ObxfEditorMenus.cpp
 *       choice lists for the selector menus
 *   - third_party/OB-Xf/src/ObxfEditor.cpp
 *       editor dimensions, scale logic
 *   - third_party/OB-Xf/src/gui/{Knob,ToggleButton,MultiStateButton,ButtonList,
 *       ImageMenu,Label,Display}.h — widget primitives
 *   - third_party/OB-Xf/src/gui/LookAndFeel.h — color tokens
 *   - third_party/OB-Xf/src/configuration.h
 *       MAX_VOICES=32, MAX_BEND_RANGE=48, MAX_MPE_BEND_RANGE=96,
 *       NUM_XPANDER_MODES=15, NUM_LFOS=2, NUM_MATRIX_ROWS=8,
 *       NUM_PATCHES_PER_GROUP=16
 *
 * WARNING — DO NOT EDIT THIS FILE BY HAND:
 *   The data structures below are VERBATIM explorer output. To regenerate,
 *   re-run the OB-Xf UI layout explorer task against the OB-Xf source tree and
 *   replace this file wholesale.
 *
 * TYPING NOTE (the one non-verbatim adjustment; spec values are unchanged):
 *   The explorer's ControlSpec interface declared `paramBound: boolean` as
 *   REQUIRED, but the 104 parameter-bound control entries omit it (only the
 *   ~69 special widgets set `paramBound: false` explicitly). To make the file
 *   type-check cleanly under `tsc --noEmit` without altering any spec values,
 *   `paramBound` was made OPTIONAL here (`paramBound?: boolean`). When absent,
 *   the control is parameter-bound (true). See the trailing EXPLORER NOTES.
 */

// Auto-extracted from OB-Xf source. All x/y/w/h are pixel coords in the
// 1150×576 VectorTheme. Knobs use d (diameter) for both w and h.
// ID strings are SynthParam::ID::* — CASE-SENSITIVE streaming identifiers.

export type ControlType = "knob" | "toggle" | "triState" | "selector" | "slider" | "button";

export enum Section {
  Master = "master",
  Global = "global",
  MPE = "mpe",
  Oscillators = "oscillators",
  Mixer = "mixer",
  Control = "control",
  Filter = "filter",
  LFO1 = "lfo1",
  LFO2 = "lfo2",
  FilterEnv = "filterEnv",
  AmpEnv = "ampEnv",
  Voice = "voice",
  Programmer = "programmer",
  Other = "other",
}

export interface ControlSpec {
  id: string;            // SynthParam::ID::* string, or widgetName for specials
  widgetName: string;    // raw name from theme.xml
  type: ControlType;
  section: Section;
  label: string;         // SynthParam::Name::* display string
  x: number; y: number;
  w: number; h: number;
  default: number;       // 0..1 normalized (matching Knob::getValue range)
  min: number; max: number;  // 0..1 unless noted
  asset?: string;        // SVG asset basename (without "-layerN.svg")
  choices?: string[];
  triStateMeaning?: { zero: string; half: string; one: string };
  paramBound?: boolean;  // false = special widget (no SynthParam::ID); absent === true (see header note)
  notes?: string;
}

// === Tri-state label shared by all LFO routing buttons ===
const LFO_TRI = { zero: "Off", half: "On", one: "Inverted" };

// === Range constants from configuration.h ===
// MAX_VOICES = 32, MAX_BEND_RANGE = 48, MAX_MPE_BEND_RANGE = 96, NUM_XPANDER_MODES = 15

export const obxfControls: ControlSpec[] = [

  // ───── MASTER (panel 0 of master group) ─────
  { id: "Volume",    widgetName: "volumeKnob",    type: "knob", section: Section.Master,
    label: "Volume",    x:  52, y: 127, w: 40, h: 40, default: 0.5,  min: 0, max: 1, asset: "knob" },
  { id: "Transpose", widgetName: "transposeKnob", type: "knob", section: Section.Master,
    label: "Transpose", x: 120, y: 127, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob",
    notes: "Alt-drag snaps to octaves [-2..2]." },
  { id: "Tune",      widgetName: "tuneKnob",      type: "knob", section: Section.Master,
    label: "Tune",      x: 188, y: 127, w: 40, h: 40, default: 0.5,  min: 0, max: 1, asset: "knob" },

  // ───── MASTER panel 1: MTS-ESP (toggled by mtsSettingsButton) ─────
  // These are SPECIAL widgets (no SynthParam::ID).
  { id: "mtsSettingsButton", widgetName: "mtsSettingsButton", type: "toggle", section: Section.Master,
    label: "MTS-ESP Settings", x: 232, y: 170, w: 11, h: 11, default: 0, min: 0, max: 1,
    asset: "button-tuning", paramBound: false,
    notes: "Panel selector: toggles between master knobs and MTS-ESP widgets." },
  { id: "mtsStatusLabel", widgetName: "mtsStatusLabel", type: "button", section: Section.Master,
    label: "MTS-ESP Scale Name", x: 56, y: 131, w: 109, h: 31, default: 0, min: 0, max: 1,
    paramBound: false, notes: "Read-only Display; text color #FF0000 (FFFF0000 ARGB)." },
  { id: "mtsDynamicButton", widgetName: "mtsDynamicButton", type: "toggle", section: Section.Master,
    label: "Dynamic MTS-ESP", x: 196, y: 129, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button", paramBound: false, notes: "Processor flag processor.dynamicMTSESP." },

  // ───── Section background labels (decorative; toBack, no mouse) ─────
  { id: "masterBGLabel", widgetName: "masterBGLabel", type: "button", section: Section.Master,
    label: "Master BG", x: 31, y: 102, w: 218, h: 84, default: 0, min: 0, max: 1,
    asset: "label-bg-master", paramBound: false,
    notes: "2-frame image strip (218×168). Frame 0 = master knobs, frame 1 = MTS-ESP." },
  { id: "globalBGLabel", widgetName: "globalBGLabel", type: "button", section: Section.Global,
    label: "Global BG", x: 31, y: 201, w: 218, h: 268, default: 0, min: 0, max: 1,
    asset: "label-bg-global", paramBound: false,
    notes: "2-frame strip (218×536). Frame 0 = global, frame 1 = MPE." },

  // ───── GLOBAL (panel 0 of global group) ─────
  { id: "Polyphony",     widgetName: "polyphonyMenu",     type: "selector", section: Section.Global,
    label: "Polyphony",     x:  56, y: 235, w: 31, h: 31, default: 8/32, min: 0, max: 1,
    asset: "menu-poly", choices: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16",
                                  "17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32"],
    notes: "2-column popup. Drives voice LED visibility." },
  { id: "HQMode",        widgetName: "hqModeButton",      type: "toggle", section: Section.Global,
    label: "High Quality Mode", x: 128, y: 233, w: 23, h: 35, default: 0, min: 0, max: 1, asset: "button" },
  { id: "lockHQButton",  widgetName: "lockHQButton",      type: "toggle", section: Section.Global,
    label: "Lock High Quality Mode", x: 154, y: 272, w: 11, h: 11, default: 0, min: 0, max: 1,
    asset: "button-lock", paramBound: false, notes: "Special: locks HQMode across patch loads." },
  { id: "UnisonVoices",  widgetName: "unisonVoicesMenu",  type: "selector", section: Section.Global,
    label: "Unison Voices", x: 192, y: 235, w: 31, h: 31, default: 8/32, min: 0, max: 1,
    asset: "menu-poly", choices: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16",
                                  "17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32"],
    notes: "Dimmed to alpha 0.25 when Unison is off." },
  { id: "Portamento",    widgetName: "portamentoKnob",    type: "knob", section: Section.Global,
    label: "Glide",        x:  52, y: 291, w: 40, h: 40, default: 0,   min: 0, max: 1, asset: "knob" },
  { id: "Unison",        widgetName: "unisonButton",      type: "toggle", section: Section.Global,
    label: "Unison",      x: 128, y: 293, w: 23, h: 35, default: 0, min: 0, max: 1, asset: "button" },
  { id: "UnisonDetune",  widgetName: "unisonDetuneKnob",  type: "knob", section: Section.Global,
    label: "Unison Detune", x: 188, y: 291, w: 40, h: 40, default: 0.25, min: 0, max: 1, asset: "knob" },
  { id: "EnvLegatoMode", widgetName: "envLegatoModeMenu", type: "selector", section: Section.Global,
    label: "Envelope Legato Mode", x:  56, y: 357, w: 90, h: 31, default: 0, min: 0, max: 1,
    asset: "menu-legato",
    choices: ["Both Envelopes", "Filter Envelope Only", "Amplifier Envelope Only", "Always Retrigger"] },
  { id: "NotePriority",  widgetName: "notePriorityMenu",  type: "selector", section: Section.Global,
    label: "Note Priority", x: 161, y: 357, w: 64, h: 31, default: 0, min: 0, max: 1,
    asset: "menu-note-priority", choices: ["Last", "Low", "High"] },
  { id: "VoiceReassign", widgetName: "voiceReassignButton", type: "toggle", section: Section.Global,
    label: "Voice Reassign", x: 232, y: 395, w: 11, h: 11, default: 0, min: 0, max: 1,
    asset: "button-reassign", notes: "v1.1 param (version hint 2)." },

  // ───── GLOBAL footer row: special main menu / MPE / MIDI-learn ─────
  { id: "mainMenu",      widgetName: "mainMenu",      type: "button", section: Section.Global,
    label: "Main Menu",   x:  60, y: 415, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-clear-red", paramBound: false, notes: "ImageMenu (popup)." },
  { id: "mpeButton",     widgetName: "mpeButton",     type: "toggle", section: Section.Global,
    label: "MPE Mode",    x: 128, y: 415, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button", paramBound: false, notes: "Toggles processor MPE enabled." },
  { id: "midiLearnButton", widgetName: "midiLearnButton", type: "toggle", section: Section.Global,
    label: "MIDI Learn",  x: 196, y: 415, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button", paramBound: false, notes: "Enters/exits MIDI-learn overlay mode." },

  // ───── MPE (panel 1 of global group; toggled by mpeSettingsButton; has childGroup) ─────
  { id: "mpeSettingsButton", widgetName: "mpeSettingsButton", type: "toggle", section: Section.MPE,
    label: "MPE Settings", x: 155, y: 455, w: 11, h: 11, default: 0, min: 0, max: 1,
    asset: "button-cogwheel", paramBound: false,
    notes: "Switches globalBGLabel to frame 1 and reveals MPE dimension panel." },
  { id: "mpeLinesLabel", widgetName: "mpeLinesLabel", type: "button", section: Section.MPE,
    label: "MPE Dimension Select Label", x: 39, y: 260, w: 118, h: 114, default: 0, min: 0, max: 1,
    asset: "label-mpe-lines", paramBound: false,
    notes: "4-frame strip showing which dimension (Strike/Lift/Press/Slide) is active." },

  // MPE dimension selector buttons — radioGroupId 2 (mutually exclusive)
  { id: "mpeStrikeSelectButton", widgetName: "mpeStrikeSelectButton", type: "toggle", section: Section.MPE,
    label: "Show MPE Strike Modulations", x:  57, y: 244, w: 18, h: 13, default: 1, min: 0, max: 1,
    asset: "button-slim", paramBound: false, notes: "Radio group 2. Sets mpeLinesLabel frame 0." },
  { id: "mpeLiftSelectButton",   widgetName: "mpeLiftSelectButton",   type: "toggle", section: Section.MPE,
    label: "Show MPE Lift Modulations",   x:  87, y: 244, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim", paramBound: false, notes: "Radio group 2. Sets mpeLinesLabel frame 1." },
  { id: "mpePressSelectButton",  widgetName: "mpePressSelectButton",  type: "toggle", section: Section.MPE,
    label: "Show MPE Press Modulations",  x: 117, y: 244, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim", paramBound: false, notes: "Radio group 2. Sets mpeLinesLabel frame 2." },
  { id: "mpeSlideSelectButton",  widgetName: "mpeSlideSelectButton",  type: "toggle", section: Section.MPE,
    label: "Show MPE Slide Modulations",  x: 147, y: 244, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim", paramBound: false, notes: "Radio group 2. Sets mpeLinesLabel frame 3." },

  // mpeGlideRangeMenu — also under MPE panel
  { id: "mpeGlideRangeMenu", widgetName: "mpeGlideRangeMenu", type: "selector", section: Section.MPE,
    label: "MPE Glide Range", x: 192, y: 235, w: 31, h: 31, default: 0, min: 0, max: 1,
    asset: "menu-mpe-pitch-bend", paramBound: false,
    choices: Array.from({length:97}, (_,i)=>String(i)),  // 0..96 semitones
    notes: "8-column popup. Processor flag (mpePitchBendRange), not a JUCE param." },

  // ───── MPE child group — 4 dimensions, each shows dest1/amt1/dest2/amt2 ─────
  // All four panels SHARE the same x/y coords (only one visible at a time).
  // The 8 amount knobs are bipolar (-1..1) and drive the voice matrix depth.
  // The 8 destination menus have variable choice lists (per MatrixSource).
  // Choice lists are runtime-derived from VoiceMatrix; first choice is always "None".
  // Dest menu asset: strike/lift use menu-mpe-targets-{strike,lift}; press/slide use menu-mpe-targets.
  ...mpeMatrixPanel("Strike", 0),
  ...mpeMatrixPanel("Lift",   1),
  ...mpeMatrixPanel("Press",  2),
  ...mpeMatrixPanel("Slide",  3),

  // ───── OSCILLATORS ─────
  { id: "Osc1Pitch",        widgetName: "osc1PitchKnob",        type: "knob", section: Section.Oscillators,
    label: "Osc 1 Pitch", x: 287, y:  48, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob",
    notes: "Cmd-drag = semitone snap [-24..24]; Alt-drag = musical snap (5ths/4ths/octaves)." },
  { id: "Osc2Detune",       widgetName: "osc2DetuneKnob",       type: "knob", section: Section.Oscillators,
    label: "Osc 2 Detune", x: 354, y:  48, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob",
    notes: "OBXF log scale [0.1..60 cents]." },
  { id: "Osc2Pitch",        widgetName: "osc2PitchKnob",        type: "knob", section: Section.Oscillators,
    label: "Osc 2 Pitch", x: 422, y:  48, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob",
    notes: "Same pitch-snap callbacks as Osc1Pitch." },
  { id: "Osc2Keytrack",     widgetName: "osc2KeytrackButton",   type: "toggle", section: Section.Oscillators,
    label: "Osc 2 Keytrack", x: 463, y: 91, w: 11, h: 11, default: 1, min: 0, max: 1,
    asset: "button-keytrack", notes: "v1.1 param. Default ON." },
  { id: "Osc1SawWave",      widgetName: "osc1SawButton",        type: "toggle", section: Section.Oscillators,
    label: "Osc 1 Saw Wave", x: 277, y: 129, w: 23, h: 35, default: 1, min: 0, max: 1, asset: "button" },
  { id: "Osc1PulseWave",    widgetName: "osc1PulseButton",      type: "toggle", section: Section.Oscillators,
    label: "Osc 1 Pulse Wave", x: 314, y: 129, w: 23, h: 35, default: 0, min: 0, max: 1, asset: "button" },
  { id: "Osc1TriangleLabel", widgetName: "osc1TriangleLabel",  type: "button", section: Section.Oscillators,
    label: "Osc 1 Triangle Icon", x: 299, y: 170, w: 16, h: 10, default: 0, min: 0, max: 1,
    asset: "label-osc-triangle", paramBound: false,
    notes: "2-frame strip. Frame 1 shows when both Saw and Pulse are off." },
  { id: "Osc1PulseLabel",   widgetName: "osc1PulseLabel",       type: "button", section: Section.Oscillators,
    label: "Osc 1 Pulse Icon", x: 319, y: 171, w: 14, h: 8, default: 0, min: 0, max: 1,
    asset: "label-osc-pulse", paramBound: false,
    notes: "Multi-frame strip; frame = round(pwKnob*46) clamped to 50." },
  { id: "Osc2SawWave",      widgetName: "osc2SawButton",        type: "toggle", section: Section.Oscillators,
    label: "Osc 2 Saw Wave", x: 412, y: 129, w: 23, h: 35, default: 1, min: 0, max: 1, asset: "button" },
  { id: "Osc2PulseWave",    widgetName: "osc2PulseButton",      type: "toggle", section: Section.Oscillators,
    label: "Osc 2 Pulse Wave", x: 449, y: 129, w: 23, h: 35, default: 0, min: 0, max: 1, asset: "button" },
  { id: "Osc2TriangleLabel", widgetName: "osc2TriangleLabel",  type: "button", section: Section.Oscillators,
    label: "Osc 2 Triangle Icon", x: 434, y: 170, w: 16, h: 10, default: 0, min: 0, max: 1,
    asset: "label-osc-triangle", paramBound: false },
  { id: "Osc2PulseLabel",   widgetName: "osc2PulseLabel",       type: "button", section: Section.Oscillators,
    label: "Osc 2 Pulse Icon", x: 454, y: 171, w: 14, h: 8, default: 0, min: 0, max: 1,
    asset: "label-osc-pulse", paramBound: false,
    notes: "Frame = min(round(pw1*46)+round(pw2*46), 50)." },
  { id: "OscPW",            widgetName: "oscPWKnob",            type: "knob", section: Section.Oscillators,
    label: "Osc Pulsewidth", x: 354, y: 127, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "Osc2PWOffset",     widgetName: "osc2PWOffsetKnob",     type: "knob", section: Section.Oscillators,
    label: "Osc 2 Pulsewidth Offset", x: 354, y: 218, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "EnvToPitchAmount", widgetName: "envToPitchAmountKnob", type: "knob", section: Section.Oscillators,
    label: "Filter Env to Pitch", x: 287, y: 218, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob",
    notes: "Cmd-drag = semitone snap [0..36]; Alt-drag = musical snap." },
  { id: "EnvToPitchBothOscs", widgetName: "envToPitchBothOscsButton", type: "toggle", section: Section.Oscillators,
    label: "Filter Env to Both Osc Pitch", x: 279, y: 187, w: 18, h: 13, default: 1, min: 0, max: 1,
    asset: "button-slim" },
  { id: "EnvToPitchInvert", widgetName: "envToPitchInvertButton", type: "toggle", section: Section.Oscillators,
    label: "Invert Filter Env to Pitch", x: 316, y: 187, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim" },
  { id: "EnvToPWAmount",    widgetName: "envToPWAmountKnob",    type: "knob", section: Section.Oscillators,
    label: "Filter Env to Pulsewidth", x: 422, y: 218, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "EnvToPWBothOscs",  widgetName: "envToPWBothOscsButton", type: "toggle", section: Section.Oscillators,
    label: "Filter Env to Both Osc Pulsewidth", x: 452, y: 187, w: 18, h: 13, default: 1, min: 0, max: 1,
    asset: "button-slim" },
  { id: "EnvToPWInvert",    widgetName: "envToPWInvertButton",  type: "toggle", section: Section.Oscillators,
    label: "Invert Filter Env to Pulsewidth", x: 415, y: 187, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim" },
  { id: "OscCrossmod",      widgetName: "oscCrossmodKnob",      type: "knob", section: Section.Oscillators,
    label: "Cross Modulation", x: 287, y: 291, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "OscSync",          widgetName: "oscSyncButton",        type: "toggle", section: Section.Oscillators,
    label: "Osc Sync", x: 363, y: 293, w: 23, h: 35, default: 0, min: 0, max: 1, asset: "button" },
  { id: "OscBrightness",    widgetName: "oscBrightnessKnob",    type: "knob", section: Section.Oscillators,
    label: "Osc Brightness", x: 422, y: 291, w: 40, h: 40, default: 1, min: 0, max: 1, asset: "knob" },

  // ───── MIXER ─────
  { id: "Osc1Vol",   widgetName: "osc1VolKnob",  type: "knob", section: Section.Mixer,
    label: "Osc 1 Volume", x: 520, y:  48, w: 40, h: 40, default: 1, min: 0, max: 1, asset: "knob",
    notes: "asCubicDecibelAttenuation." },
  { id: "Osc2Vol",   widgetName: "osc2VolKnob",  type: "knob", section: Section.Mixer,
    label: "Osc 2 Volume", x: 520, y: 127, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob",
    notes: "asCubicDecibelAttenuation. NOTE: registry default 1.0 but ParameterList default 0.0." },
  { id: "RingModVol", widgetName: "ringModVolKnob", type: "knob", section: Section.Mixer,
    label: "Ring Mod Volume", x: 520, y: 218, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "NoiseVol",  widgetName: "noiseVolKnob", type: "knob", section: Section.Mixer,
    label: "Noise Volume", x: 520, y: 291, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "NoiseColor", widgetName: "noiseColorButton", type: "triState", section: Section.Mixer,
    label: "Noise Color", x: 504, y: 333, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim-noise", triStateMeaning: { zero: "White", half: "Pink", one: "Red" } },

  // ───── CONTROL ─────
  { id: "BendDownRange", widgetName: "bendDownRangeMenu", type: "selector", section: Section.Control,
    label: "Pitch Bend Down", x: 291, y: 417, w: 31, h: 31, default: 2/48, min: 0, max: 1,
    asset: "menu-pitch-bend", choices: Array.from({length:49}, (_,i)=>String(i)),  // 0..48
    notes: "4-column popup." },
  { id: "BendUpRange",   widgetName: "bendUpRangeMenu", type: "selector", section: Section.Control,
    label: "Pitch Bend Up", x: 359, y: 417, w: 31, h: 31, default: 2/48, min: 0, max: 1,
    asset: "menu-pitch-bend", choices: Array.from({length:49}, (_,i)=>String(i)) },
  { id: "BendOsc2Only",  widgetName: "bendOsc2OnlyButton", type: "toggle", section: Section.Control,
    label: "Pitch Bend Osc 2 Only", x: 431, y: 415, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button" },
  { id: "lockBendRangeButton", widgetName: "lockBendRangeButton", type: "toggle", section: Section.Control,
    label: "Lock Pitch Bend Range", x: 335, y: 427, w: 11, h: 11, default: 0, min: 0, max: 1,
    asset: "button-lock", paramBound: false,
    notes: "Special: locks Bend{Up,Down}Range across patch loads." },
  { id: "VibratoWave",   widgetName: "vibratoWaveButton", type: "toggle", section: Section.Control,
    label: "Vibrato Wave", x: 491, y: 426, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim-vibrato-wave",
    notes: "Stored as bool but displays as {0:'Sine', 1:'Square'}." },
  { id: "VibratoRate",   widgetName: "vibratoRateKnob", type: "knob", section: Section.Control,
    label: "Vibrato Rate", x: 520, y: 413, w: 40, h: 40, default: 0.3, min: 0, max: 1, asset: "knob" },

  // ───── FILTER ─────
  // Visibility rule (CRITICAL — see Notes §6):
  //   fourPole = Filter4PoleMode; xpander = Filter4PoleXpander
  //   filter2PoleBPBlend / filter2PolePush / filterModeLabel-frame-0  visible when !fourPole
  //   filter4PoleXpander / filterXpanderModeMenu                       visible when fourPole
  //   filterModeKnob                                                    hidden when fourPole && xpander
  { id: "Filter4PoleMode",   widgetName: "filter4PoleModeButton",   type: "toggle", section: Section.Filter,
    label: "Filter 4-Pole Mode", x: 601, y:  20, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim" },
  { id: "FilterCutoff",      widgetName: "filterCutoffKnob",       type: "knob", section: Section.Filter,
    label: "Filter Cutoff", x: 616, y:  48, w: 40, h: 40, default: 1, min: 0, max: 1, asset: "knob" },
  { id: "FilterResonance",   widgetName: "filterResonanceKnob",    type: "knob", section: Section.Filter,
    label: "Filter Resonance", x: 684, y:  48, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "FilterEnvAmount",   widgetName: "filterEnvAmountKnob",    type: "knob", section: Section.Filter,
    label: "Filter Env Amount", x: 752, y:  48, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "FilterKeyTrack",    widgetName: "filterKeyTrackKnob",     type: "knob", section: Section.Filter,
    label: "Filter Keytracking", x: 616, y: 127, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "FilterMode",        widgetName: "filterModeKnob",         type: "knob", section: Section.Filter,
    label: "Filter Mode", x: 684, y: 127, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob",
    notes: "Hidden when Filter4PoleMode && Filter4PoleXpander both on." },
  { id: "Filter2PoleBPBlend", widgetName: "filter2PoleBPBlendButton", type: "toggle", section: Section.Filter,
    label: "Filter 2-Pole BP Blend", x: 749, y: 131, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim", notes: "Hidden when Filter4PoleMode is on." },
  { id: "Filter2PolePush",   widgetName: "filter2PolePushButton",  type: "toggle", section: Section.Filter,
    label: "Filter 2-Pole Push", x: 749, y: 151, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim", notes: "Hidden when Filter4PoleMode is on." },
  { id: "Filter4PoleXpander", widgetName: "filter4PoleXpanderButton", type: "toggle", section: Section.Filter,
    label: "Filter 4-Pole Xpander", x: 760, y: 129, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button", notes: "Visible only when Filter4PoleMode is on." },
  { id: "FilterXpanderMode", widgetName: "filterXpanderModeMenu",  type: "selector", section: Section.Filter,
    label: "Filter Xpander Mode", x: 674, y: 132, w: 62, h: 31, default: 0, min: 0, max: 1,
    asset: "menu-xpander",
    choices: ["LP4","LP3","LP2","LP1","HP3","HP2","HP1","BP4","BP2","N2","PH3",
              "HP2+LP1","HP3+LP1","N2+LP1","PH3+LP1"],
    notes: "Visible only when Filter4PoleMode && Filter4PoleXpander both on." },
  { id: "filterModeLabel", widgetName: "filterModeLabel", type: "button", section: Section.Filter,
    label: "Filter Mode Label", x: 670, y: 116, w: 70, h: 56, default: 0, min: 0, max: 1,
    asset: "label-filter-mode", paramBound: false,
    notes: "4-frame strip. Frame = fourPole ? (xpander?3:2) : (bpBlend?1:0)." },
  { id: "filterOptionsLabel", widgetName: "filterOptionsLabel", type: "button", section: Section.Filter,
    label: "Filter Options Label", x: 747, y: 127, w: 54, h: 54, default: 0, min: 0, max: 1,
    asset: "label-filter-options", paramBound: false,
    notes: "2-frame strip. Frame = fourPole ? 1 : 0." },

  // ───── LFO selector buttons (radio group 1) ─────
  { id: "lfo1SelectButton", widgetName: "lfo1SelectButton", type: "toggle", section: Section.LFO1,
    label: "Select LFO 1", x: 757, y: 213, w: 18, h: 13, default: 1, min: 0, max: 1,
    asset: "button-slim", paramBound: false, notes: "Radio group 1." },
  { id: "lfo2SelectButton", widgetName: "lfo2SelectButton", type: "toggle", section: Section.LFO2,
    label: "Select LFO 2", x: 789, y: 213, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim-alt", paramBound: false, notes: "Radio group 1." },

  // ───── LFO 1 (panel 0 of lfo group; visible when lfo1SelectButton is on) ─────
  { id: "LFO1TempoSync",  widgetName: "lfo1TempoSyncButton",  type: "toggle", section: Section.LFO1,
    label: "LFO 1 Tempo Sync", x: 601, y: 213, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim" },
  { id: "LFO1Rate",       widgetName: "lfo1RateKnob",         type: "knob", section: Section.LFO1,
    label: "LFO 1 Rate", x: 616, y: 233, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob",
    notes: "temposyncable; display switches to synced rate names when LFO1TempoSync is on." },
  { id: "LFO1ModAmount1", widgetName: "lfo1ModAmount1Knob",   type: "knob", section: Section.LFO1,
    label: "LFO 1 Mod 1 Amount", x: 684, y: 233, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "LFO1ModAmount2", widgetName: "lfo1ModAmount2Knob",   type: "knob", section: Section.LFO1,
    label: "LFO 1 Mod 2 Amount", x: 752, y: 233, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "LFO1Wave1",      widgetName: "lfo1Wave1Knob",        type: "knob", section: Section.LFO1,
    label: "LFO 1 Wave 1", x: 616, y: 291, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob",
    notes: "Bipolar display -1..1 (Sine ↔ Triangle). defaultVal in ParameterList is -1 (mapped to 0)." },
  { id: "LFO1Wave2",      widgetName: "lfo1Wave2Knob",        type: "knob", section: Section.LFO1,
    label: "LFO 1 Wave 2", x: 616, y: 353, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob",
    notes: "Bipolar display (Pulse ↔ Saw). Knob registry default 0.5." },
  { id: "LFO1Wave3",      widgetName: "lfo1Wave3Knob",        type: "knob", section: Section.LFO1,
    label: "LFO 1 Wave 3", x: 616, y: 413, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob",
    notes: "Bipolar display (Sample&Hold ↔ Sample&Glide)." },
  { id: "LFO1PW",         widgetName: "lfo1PWSlider",         type: "slider", section: Section.LFO1,
    label: "LFO 1 Pulsewidth", x: 598, y: 348, w: 12, h: 47, default: 0, min: 0, max: 1,
    asset: "slider-v", notes: "VERTICAL slider via Knob svgTranslationMode. fh=9." },
  { id: "lfo1Wave2Label", widgetName: "lfo1Wave2Label",       type: "button", section: Section.LFO1,
    label: "LFO 1 Wave 2 Icons", x: 609, y: 396, w: 54, h: 8, default: 0, min: 0, max: 1,
    asset: "label-lfo-wave2", paramBound: false,
    notes: "25-frame strip; frame = round(LFO1PW * 24)." },
  { id: "LFO1ToOsc1Pitch",    widgetName: "lfo1ToOsc1PitchButton",    type: "triState", section: Section.LFO1,
    label: "LFO 1 to Osc 1 Pitch", x: 692, y: 293, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual", triStateMeaning: LFO_TRI },
  { id: "LFO1ToOsc2Pitch",    widgetName: "lfo1ToOsc2PitchButton",    type: "triState", section: Section.LFO1,
    label: "LFO 1 to Osc 2 Pitch", x: 692, y: 355, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual", triStateMeaning: LFO_TRI },
  { id: "LFO1ToFilterCutoff", widgetName: "lfo1ToFilterCutoffButton", type: "triState", section: Section.LFO1,
    label: "LFO 1 to Filter Cutoff", x: 692, y: 415, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual", triStateMeaning: LFO_TRI },
  { id: "LFO1ToOsc1PW",       widgetName: "lfo1ToOsc1PWButton",       type: "triState", section: Section.LFO1,
    label: "LFO 1 to Osc 1 PW", x: 760, y: 293, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual", triStateMeaning: LFO_TRI },
  { id: "LFO1ToOsc2PW",       widgetName: "lfo1ToOsc2PWButton",       type: "triState", section: Section.LFO1,
    label: "LFO 1 to Osc 2 PW", x: 760, y: 355, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual", triStateMeaning: LFO_TRI },
  { id: "LFO1ToVolume",       widgetName: "lfo1ToVolumeButton",       type: "triState", section: Section.LFO1,
    label: "LFO 1 to Volume", x: 760, y: 415, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual", triStateMeaning: LFO_TRI },

  // ───── LFO 2 (panel 1; shares LFO1 footprint) ─────
  { id: "LFO2TempoSync",  widgetName: "lfo2TempoSyncButton",  type: "toggle", section: Section.LFO2,
    label: "LFO 2 Tempo Sync", x: 601, y: 213, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim-alt" },
  { id: "LFO2Rate",       widgetName: "lfo2RateKnob",         type: "knob", section: Section.LFO2,
    label: "LFO 2 Rate", x: 616, y: 233, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },
  { id: "LFO2ModAmount1", widgetName: "lfo2ModAmount1Knob",   type: "knob", section: Section.LFO2,
    label: "LFO 2 Mod 1 Amount", x: 684, y: 233, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "LFO2ModAmount2", widgetName: "lfo2ModAmount2Knob",   type: "knob", section: Section.LFO2,
    label: "LFO 2 Mod 2 Amount", x: 752, y: 233, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "LFO2Wave1",      widgetName: "lfo2Wave1Knob",        type: "knob", section: Section.LFO2,
    label: "LFO 2 Wave 1", x: 616, y: 291, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "LFO2Wave2",      widgetName: "lfo2Wave2Knob",        type: "knob", section: Section.LFO2,
    label: "LFO 2 Wave 2", x: 616, y: 353, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },
  { id: "LFO2Wave3",      widgetName: "lfo2Wave3Knob",        type: "knob", section: Section.LFO2,
    label: "LFO 2 Wave 3", x: 616, y: 413, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },
  { id: "LFO2PW",         widgetName: "lfo2PWSlider",         type: "slider", section: Section.LFO2,
    label: "LFO 2 Pulsewidth", x: 598, y: 348, w: 12, h: 47, default: 0, min: 0, max: 1,
    asset: "slider-v" },
  { id: "lfo2Wave2Label", widgetName: "lfo2Wave2Label",       type: "button", section: Section.LFO2,
    label: "LFO 2 Wave 2 Icons", x: 609, y: 396, w: 54, h: 8, default: 0, min: 0, max: 1,
    asset: "label-lfo-wave2", paramBound: false },
  { id: "LFO2ToOsc1Pitch",    widgetName: "lfo2ToOsc1PitchButton",    type: "triState", section: Section.LFO2,
    label: "LFO 2 to Osc 1 Pitch", x: 692, y: 293, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual-alt", triStateMeaning: LFO_TRI },
  { id: "LFO2ToOsc2Pitch",    widgetName: "lfo2ToOsc2PitchButton",    type: "triState", section: Section.LFO2,
    label: "LFO 2 to Osc 2 Pitch", x: 692, y: 355, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual-alt", triStateMeaning: LFO_TRI },
  { id: "LFO2ToFilterCutoff", widgetName: "lfo2ToFilterCutoffButton", type: "triState", section: Section.LFO2,
    label: "LFO 2 to Filter Cutoff", x: 692, y: 415, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual-alt", triStateMeaning: LFO_TRI },
  { id: "LFO2ToOsc1PW",       widgetName: "lfo2ToOsc1PWButton",       type: "triState", section: Section.LFO2,
    label: "LFO 2 to Osc 1 PW", x: 760, y: 293, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual-alt", triStateMeaning: LFO_TRI },
  { id: "LFO2ToOsc2PW",       widgetName: "lfo2ToOsc2PWButton",       type: "triState", section: Section.LFO2,
    label: "LFO 2 to Osc 2 PW", x: 760, y: 355, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual-alt", triStateMeaning: LFO_TRI },
  { id: "LFO2ToVolume",       widgetName: "lfo2ToVolumeButton",       type: "triState", section: Section.LFO2,
    label: "LFO 2 to Volume", x: 760, y: 415, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-dual-alt", triStateMeaning: LFO_TRI },

  // ───── FILTER ENVELOPE ─────
  { id: "FilterEnvInvert",     widgetName: "filterEnvInvertButton",     type: "toggle", section: Section.FilterEnv,
    label: "Filter Env Invert", x: 833, y:  20, w: 18, h: 13, default: 0, min: 0, max: 1,
    asset: "button-slim" },
  { id: "FilterEnvAttack",     widgetName: "filterEnvAttackKnob",      type: "knob", section: Section.FilterEnv,
    label: "Filter Env Attack", x:  850, y:  48, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob",
    notes: "Log scale [1ms..60s]." },
  { id: "FilterEnvDecay",      widgetName: "filterEnvDecayKnob",       type: "knob", section: Section.FilterEnv,
    label: "Filter Env Decay", x:  919, y:  48, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "FilterEnvSustain",    widgetName: "filterEnvSustainKnob",     type: "knob", section: Section.FilterEnv,
    label: "Filter Env Sustain", x:  988, y:  48, w: 40, h: 40, default: 1, min: 0, max: 1, asset: "knob" },
  { id: "FilterEnvRelease",    widgetName: "filterEnvReleaseKnob",     type: "knob", section: Section.FilterEnv,
    label: "Filter Env Release", x: 1057, y:  48, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "FilterEnvAttackCurve", widgetName: "filterEnvAttackCurveSlider", type: "slider", section: Section.FilterEnv,
    label: "Filter Env Attack Curve", x:  844, y: 111, w: 47, h: 12, default: 0, min: 0, max: 1,
    asset: "slider-h", notes: "HORIZONTAL slider via Knob svgTranslationMode. fh=9." },
  { id: "VelToFilterEnv",      widgetName: "velToFilterEnvSlider",     type: "slider", section: Section.FilterEnv,
    label: "Velocity to Filter Env", x: 1052, y: 111, w: 47, h: 12, default: 0, min: 0, max: 1,
    asset: "slider-h" },

  // ───── AMPLIFIER ENVELOPE ─────
  { id: "AmpEnvAttack",     widgetName: "ampEnvAttackKnob",      type: "knob", section: Section.AmpEnv,
    label: "Amp Env Attack", x:  850, y: 175, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob",
    notes: "Log scale [4ms..60s]." },
  { id: "AmpEnvDecay",      widgetName: "ampEnvDecayKnob",       type: "knob", section: Section.AmpEnv,
    label: "Amp Env Decay", x: 919, y: 175, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob" },
  { id: "AmpEnvSustain",    widgetName: "ampEnvSustainKnob",     type: "knob", section: Section.AmpEnv,
    label: "Amp Env Sustain", x: 988, y: 175, w: 40, h: 40, default: 1, min: 0, max: 1, asset: "knob" },
  { id: "AmpEnvRelease",    widgetName: "ampEnvReleaseKnob",     type: "knob", section: Section.AmpEnv,
    label: "Amp Env Release", x: 1057, y: 175, w: 40, h: 40, default: 0, min: 0, max: 1, asset: "knob",
    notes: "Log scale [8ms..60s]." },
  { id: "AmpEnvAttackCurve", widgetName: "ampEnvAttackCurveSlider", type: "slider", section: Section.AmpEnv,
    label: "Amp Env Attack Curve", x:  844, y: 238, w: 47, h: 12, default: 0, min: 0, max: 1,
    asset: "slider-h" },
  { id: "VelToAmpEnv",      widgetName: "velToAmpEnvSlider",     type: "slider", section: Section.AmpEnv,
    label: "Velocity to Amp Env", x: 1052, y: 238, w: 47, h: 12, default: 0, min: 0, max: 1,
    asset: "slider-h" },

  // ───── VOICE VARIATION ─────
  { id: "PortamentoSlop", widgetName: "portamentoSlopKnob", type: "knob", section: Section.Voice,
    label: "Glide Slop", x:  850, y: 291, w: 40, h: 40, default: 0.25, min: 0, max: 1, asset: "knob" },
  { id: "FilterSlop",     widgetName: "filterSlopKnob",     type: "knob", section: Section.Voice,
    label: "Filter Slop", x: 919, y: 291, w: 40, h: 40, default: 0.25, min: 0, max: 1, asset: "knob" },
  { id: "EnvelopeSlop",   widgetName: "envelopeSlopKnob",   type: "knob", section: Section.Voice,
    label: "Envelope Slop", x: 988, y: 291, w: 40, h: 40, default: 0.25, min: 0, max: 1, asset: "knob" },
  { id: "LevelSlop",      widgetName: "levelSlopKnob",      type: "knob", section: Section.Voice,
    label: "Level Slop", x: 1057, y: 291, w: 40, h: 40, default: 0.25, min: 0, max: 1, asset: "knob" },
  // Pan knobs are bipolar -1..1 with custom display "37 L / Center / 92 R".
  { id: "PanVoice1", widgetName: "pan1Knob", type: "knob", section: Section.Voice,
    label: "Pan Voice 1", x:  850, y: 353, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },
  { id: "PanVoice2", widgetName: "pan2Knob", type: "knob", section: Section.Voice,
    label: "Pan Voice 2", x:  919, y: 353, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },
  { id: "PanVoice3", widgetName: "pan3Knob", type: "knob", section: Section.Voice,
    label: "Pan Voice 3", x:  988, y: 353, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },
  { id: "PanVoice4", widgetName: "pan4Knob", type: "knob", section: Section.Voice,
    label: "Pan Voice 4", x: 1057, y: 353, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },
  { id: "PanVoice5", widgetName: "pan5Knob", type: "knob", section: Section.Voice,
    label: "Pan Voice 5", x:  850, y: 413, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },
  { id: "PanVoice6", widgetName: "pan6Knob", type: "knob", section: Section.Voice,
    label: "Pan Voice 6", x:  919, y: 413, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },
  { id: "PanVoice7", widgetName: "pan7Knob", type: "knob", section: Section.Voice,
    label: "Pan Voice 7", x:  988, y: 413, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },
  { id: "PanVoice8", widgetName: "pan8Knob", type: "knob", section: Section.Voice,
    label: "Pan Voice 8", x: 1057, y: 413, w: 40, h: 40, default: 0.5, min: 0, max: 1, asset: "knob" },

  // ───── Voice LEDs (1..32, display-only) ─────
  // Polyphony determines how many are visible (1..32). LED alpha = cbrt(voiceStatusValue[i]).
  // LEDs 1-8 use label-led1, 9-16 use label-led2, 17-24 use label-led3, 25-32 use label-led4.
  // Each LED has a paired voice{N}BG component at the same bounds (the dark "off" graphic).
  // Y-offsets: each "row" of 4 voices is at y=354 (voices 1-4,9-12,17-20,25-28) then y=364/374/384/394...
  // Pattern from theme.xml (omitted for brevity — full list in theme.xml lines 246-284):
  //   voice{1,2,3,4}LED     x=895/964/1033/1102, y=354, w=9, h=9, asset=label-led1
  //   voice{5,6,7,8}LED     x=895/964/1033/1102, y=414, w=9, h=9, asset=label-led1
  //   voice{9..16}LED       same x's, y=364/424,                                       asset=label-led2
  //   voice{17..24}LED      same x's, y=374/434,                                       asset=label-led3
  //   voice{25..32}LED      same x's, y=384/444,                                       asset=label-led4
  // Verified against VectorTheme theme.xml lines 246-284 (byte-exact x/y/asset match).

  // ───── PROGRAMMER (footer row, all at y=504/506) ─────
  { id: "patchNumberMenu", widgetName: "patchNumberMenu", type: "button", section: Section.Programmer,
    label: "Patch Number", x:  56, y: 506, w: 43, h: 31, default: 0, min: 0, max: 1,
    asset: "menu-patch", paramBound: false, notes: "DisplayDigits component; opens patch list popup." },
  { id: "patchNameLabel", widgetName: "patchNameLabel", type: "button", section: Section.Programmer,
    label: "Patch Name", x: 103, y: 506, w: 166, h: 31, default: 0, min: 0, max: 1,
    paramBound: false, notes: "Display (editable Label). Font Jersey20 @ 18px. Color #FF0000." },
  { id: "prevPatchButton", widgetName: "prevPatchButton", type: "button", section: Section.Programmer,
    label: "Previous Patch", x: 297, y: 504, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-clear", paramBound: false },
  { id: "nextPatchButton", widgetName: "nextPatchButton", type: "button", section: Section.Programmer,
    label: "Next Patch", x: 327, y: 504, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-clear", paramBound: false },
  { id: "savePatchButton", widgetName: "savePatchButton", type: "button", section: Section.Programmer,
    label: "Save Patch", x: 372, y: 504, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-clear-red", paramBound: false, notes: "Cmd-click = quick save." },
  { id: "undoPatchButton", widgetName: "undoPatchButton", type: "button", section: Section.Programmer,
    label: "Undo", x: 405, y: 504, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-clear", paramBound: false },
  { id: "initPatchButton", widgetName: "initPatchButton", type: "button", section: Section.Programmer,
    label: "Initialize Patch", x: 450, y: 504, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-clear-white", paramBound: false },
  { id: "randomizePatchButton", widgetName: "randomizePatchButton", type: "button", section: Section.Programmer,
    label: "Randomize Patch", x: 483, y: 504, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-clear", paramBound: false, notes: "Right-click opens mutator section menu." },
  { id: "groupSelectButton", widgetName: "groupSelectButton", type: "toggle", section: Section.Programmer,
    label: "Select Patch or Group", x: 530, y: 504, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-alt", paramBound: false },

  // select1..select16 — patch/group selector buttons (always use button-group-patch asset)
  ...Array.from({length:16}, (_,i) => ({
    id: `select${i+1}Button`, widgetName: `select${i+1}Button`, type: "button" as const,
    section: Section.Programmer, label: `Select Group/Patch ${i+1}`,
    x: 578 + i*33, y: 504, w: 23, h: 35, default: 0, min: 0, max: 1,
    asset: "button-group-patch", paramBound: false,
    notes: "triggeredOnMouseDown; clickingTogglesState=false; paired label at same bounds.",
  })),

  // ───── About click area ─────
  { id: "aboutPage", widgetName: "aboutPage", type: "button", section: Section.Other,
    label: "About Page", x: 30, y: 14, w: 220, h: 74, default: 0, min: 0, max: 1,
    paramBound: false, notes: "Invisible click area over the logo; opens about overlay." },
];

// === MPE matrix panel generator (4 dimensions × 2 rows × {dest, amount}) ===
// All four panels share the same screen coordinates — only one is visible at a time
// (selected by mpe{Strike,Lift,Press,Slide}SelectButton radio group).
// The amount knobs are bipolar -1..1 (setRange(-1,1,0.001)) and drive VoiceMatrix row.depth.
// The dest menus are runtime-populated from VoiceMatrix targets (first entry "None").
function mpeMatrixPanel(dim: "Strike"|"Lift"|"Press"|"Slide", frame: number): ControlSpec[] {
  const lc = dim.toLowerCase();
  const destAsset =
    dim === "Strike" ? "menu-mpe-targets-strike" :
    dim === "Lift"   ? "menu-mpe-targets-lift"  :
                       "menu-mpe-targets";
  return [
    { id: `mpe${dim}Destination1Menu`, widgetName: `mpe${dim}Destination1Menu`,
      type: "selector", section: Section.MPE, label: `MPE ${dim} Destination 1`,
      x: 56, y: 297, w: 107, h: 31, default: 0, min: 0, max: 1, asset: destAsset,
      paramBound: false, choices: [], // TODO: populated at runtime from VoiceMatrix
      notes: `MatrixSource::${dim}, slot ${(frame*2)}.` },
    { id: `mpe${dim}Amount1Knob`, widgetName: `mpe${dim}Amount1Knob`,
      type: "knob", section: Section.MPE, label: `MPE ${dim} Amount 1`,
      x: 188, y: 291, w: 40, h: 40, default: 0, min: -1, max: 1, asset: "knob",
      paramBound: false,
      notes: `Bipolar -1..1; custom text "N.N %". Drives voice matrix depth.` },
    { id: `mpe${dim}Destination2Menu`, widgetName: `mpe${dim}Destination2Menu`,
      type: "selector", section: Section.MPE, label: `MPE ${dim} Destination 2`,
      x: 56, y: 357, w: 107, h: 31, default: 0, min: 0, max: 1, asset: destAsset,
      paramBound: false, choices: [], notes: `MatrixSource::${dim}, slot ${(frame*2)+1}.` },
    { id: `mpe${dim}Amount2Knob`, widgetName: `mpe${dim}Amount2Knob`,
      type: "knob", section: Section.MPE, label: `MPE ${dim} Amount 2`,
      x: 188, y: 351, w: 40, h: 40, default: 0, min: -1, max: 1, asset: "knob",
      paramBound: false, notes: "Bipolar -1..1." },
  ];
}

// =============================================================================
// Theme tokens (explorer Section 3)
// All colors extracted from:
//  - src/gui/LookAndFeel.h (LookAndFeel constructor, lines 78-99)
//  - assets/binary/VectorTheme/background.svg (root fill)
//  - assets/binary/VectorTheme/label-bg-{master,global}.svg (root fills)
//  - theme.xml `color` attributes (text inputs only — format is AARRGGBB)
//
// JUCE Colour is RGB; alpha defaults to FF (opaque) when 0xRRGGBB is given.
// =============================================================================

export const obxfTheme = {
  // Editor canvas — set in ObxfEditor::paint as `g.fillAll(Colours::black.brighter(0.1f))`.
  // Colours::black = #000000; brighter(0.1) ≈ mix with white at 10% → ~#1A1A1A.
  // The SVG background.svg rect is #191919 and covers the whole 1150x576.
  background: "#191919",
  backgroundFallback: "#1a1a1a",   // brighter(0.1) of pure black

  // LookAndFeel_V4 base palette (LookAndFeel.h lines 78-99)
  documentWindowBackground: "#303030",  // (48, 48, 48)
  textButton:         "#202020",        // (32, 32, 32)
  textEditorBg:       "#202020",
  textEditorHighlight:"#606060",        // (96, 96, 96)
  listBoxBg:          "#202020",
  scrollBarThumb:     "#d4d4d4",        // (212, 212, 212)
  scrollBarTrack:     "#808080",        // (128, 128, 128)
  sliderThumb:        "#d4d4d4",
  sliderTrack:        "#808080",
  sliderBg:           "rgba(255,255,255,0.078)",  // (255,255,255, 20/255)
  comboBoxBg:         "#202020",
  popupMenuBg:        "#202020",
  popupMenuHighlightBg:"#404040",       // (64, 64, 64)
  alertWindowBg:      "#303030",
  alertWindowOutline: "#606060",
  alertWindowText:    "#ffffff",
  bubbleBg:           "rgba(48,48,48,0.8)",
  bubbleOutline:      "rgba(64,64,64,0.6)",
  tooltipText:        "#ffffff",

  // Custom buttons created via createDocumentWindowButton
  docWindowClose:     "#d44040",        // (212, 64, 64)
  docWindowMinimize:  "#ffd420",        // (255, 212, 32)
  docWindowHover:     "#606060",        // (96, 96, 96)

  // Text input color: from theme.xml `color` attribute, default "FFFF0000" (ARGB → opaque red).
  // LookAndFeel stores it as textInputColour initialized to Colours::red (#ff0000),
  // overridden by the patchNameLabel/mtsStatusLabel/savePatch*Label `color` attrs (all #FF0000).
  textInput:          "#ff0000",

  // Panel/section background art (from SVG root fills). These are full-image assets,
  // not flat colors — list the dominant panel color only as a fallback.
  panel: {
    master:  "#727882",   // label-bg-master.svg root rect (grey-blue)
    global:  "#727882",   // label-bg-global.svg root rect (same)
    other:   "#191919",   // no per-section bg; uses main background.svg
  },

  // Knob colors — OB-Xf's knob is a 2-layer SVG (knob-layer1.svg base, knob-layer2.svg
  // indicator), NOT a procedurally-drawn arc. Use the existing OctOBX SVG knob look
  // (var(--accent) green) as a placeholder if you don't want to ship the OB-Xf knob SVGs.
  knob: {
    base: "#3a3a3a",      // placeholder
    indicator: "#d4d4d4", // placeholder
    accent: "#0c0",       // (matches OctOBX knob fill — OB-Xf itself uses SVG art only)
  },

  // Fonts — embedded as BinaryData resources.
  //  Jersey20.ttf  → patch name display (patchNameLabel, mtsStatusLabel, savePatch* labels)
  //                 patchNameFont set to Jersey20 @ height 18 in ObxfEditor constructor + loadTheme.
  //  Trek.ttf      → midiLearnPopupFont (used by MIDI-learn overlay only)
  //  System default→ everything else (LookAndFeel_V4 defaults).
  font: {
    patchName:  "'Jersey20', sans-serif",   // 18px
    midiLearn:   "'Trek', sans-serif",
    default:     "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
  },

  // Knob geometry constants (from ObxfEditorTheme.h + Knob.h paint()):
  //  defKnobDiameter = 40
  //  Rotary angle range: -135° to +135° (270° sweep) — same as OctOBX knob.
  //    angle = (2 * value01 - 1) * (π * 0.75)
  knobDiameter: 40,
  knobArcStartDeg: -135,
  knobArcSweepDeg: 270,

  // Editor dimensions (ObxfEditor constructor — derived from background.svg)
  width: 1150,
  height: 576,
  // Aspect ratio is locked (ComponentBoundsConstrainer::setFixedAspectRatio).
  aspectRatio: 1150 / 576,
  // Minimum size = initial size * 0.75 (smallest zoom factor)
  minWidth: 1150 * 0.75,
  minHeight:  576 * 0.75,
  scaleFactors: [0.75, 0.85, 1.0, 1.25, 1.5, 1.75, 2.0, 2.5, 3.0, 4.0],
};

// === EXPLORER NOTES ==========================================================
//
// The text below is the explorer's prose documentation (Sections 4, 5, 6 of the
// original output), preserved verbatim as comments for downstream agents. This
// content is NOT executable code. Where the explorer emitted TypeScript in these
// sections (PanelGroup / obxfPanels), it is reproduced commented-out so the
// shapes are visible without polluting the runtime exports.
//
// ---------------------------------------------------------------------------
// SECTION 4: Section groupings (with bounding boxes)
// ---------------------------------------------------------------------------
//
// Panel backgrounds are 2-frame image strips (one frame per visible state).
// Bounding boxes below are the visible rectangle in the canvas; the source SVG
// is twice as tall (frame 0 stacked on frame 1).
//
// (explorer TS, commented out:)
//
// export interface PanelGroup {
//   name: string;
//   bbox: { x: number; y: number; w: number; h: number };
//   backgroundAsset?: string;     // 2-frame image strip; setCurrentFrame() picks sub-image
//   backgroundFrames?: number;    // typically 2 (off / on)
//   controls: string[];           // widgetNames whose center falls in this panel
// }
//
// export const obxfPanels: PanelGroup[] = [
//
//   // ── MASTER (top-left, with MTS-ESP alt-state) ──
//   // masterBGLabel is 2-frame: frame 0 shows master knobs, frame 1 shows MTS-ESP widgets.
//   // The same 84px-tall rectangle hosts BOTH panels (radio-like toggle via mtsSettingsButton).
//   {
//     name: "master",
//     bbox: { x: 31, y: 102, w: 218, h: 84 },
//     backgroundAsset: "label-bg-master",
//     backgroundFrames: 2,
//     controls: ["volumeKnob", "transposeKnob", "tuneKnob",
//                "mtsSettingsButton", "mtsStatusLabel", "mtsDynamicButton"],
//   },
//
//   // ── GLOBAL / MPE (left column below master; 2-frame alt-state) ──
//   // globalBGLabel is 2-frame: frame 0 = global knobs, frame 1 = MPE dimension selectors.
//   // Note: the MPE sub-dimension panels (Strike/Lift/Press/Slide) live INSIDE the same
//   // rectangle and are switched by the radio group 2 buttons.
//   {
//     name: "global",
//     bbox: { x: 31, y: 201, w: 218, h: 268 },
//     backgroundAsset: "label-bg-global",
//     backgroundFrames: 2,
//     controls: [
//       // Global panel (frame 0)
//       "polyphonyMenu", "hqModeButton", "lockHQButton", "unisonVoicesMenu",
//       "portamentoKnob", "unisonButton", "unisonDetuneKnob",
//       "envLegatoModeMenu", "notePriorityMenu", "voiceReassignButton",
//       "mainMenu", "mpeButton", "midiLearnButton",
//       // MPE panel (frame 1) — toggled by mpeSettingsButton
//       "mpeSettingsButton", "mpeLinesLabel",
//       "mpeStrikeSelectButton", "mpeLiftSelectButton",
//       "mpePressSelectButton", "mpeSlideSelectButton",
//       "mpeGlideRangeMenu",
//       // MPE child-group — 4 dimensions, each shows dest1/amt1/dest2/amt2
//       "mpeStrikeDestination1Menu", "mpeStrikeAmount1Knob",
//       "mpeStrikeDestination2Menu", "mpeStrikeAmount2Knob",
//       "mpeLiftDestination1Menu",   "mpeLiftAmount1Knob",
//       "mpeLiftDestination2Menu",   "mpeLiftAmount2Knob",
//       "mpePressDestination1Menu",  "mpePressAmount1Knob",
//       "mpePressDestination2Menu",  "mpePressAmount2Knob",
//       "mpeSlideDestination1Menu",  "mpeSlideAmount1Knob",
//       "mpeSlideDestination2Menu",  "mpeSlideAmount2Knob",
//     ],
//   },
//
//   // ── OSCILLATORS (no background art; drawn directly on canvas) ──
//   {
//     name: "oscillators",
//     bbox: { x: 277, y:  48, w: 209, h: 278 },  // tight box around all osc widgets
//     controls: [
//       "osc1PitchKnob", "osc2DetuneKnob", "osc2PitchKnob", "osc2KeytrackButton",
//       "osc1SawButton", "osc1PulseButton", "osc1TriangleLabel", "osc1PulseLabel",
//       "osc2SawButton", "osc2PulseButton", "osc2TriangleLabel", "osc2PulseLabel",
//       "oscPWKnob", "osc2PWOffsetKnob",
//       "envToPitchAmountKnob", "envToPitchBothOscsButton", "envToPitchInvertButton",
//       "envToPWAmountKnob",    "envToPWBothOscsButton",    "envToPWInvertButton",
//       "oscCrossmodKnob", "oscSyncButton", "oscBrightnessKnob",
//     ],
//   },
//
//   // ── MIXER (single vertical column at x=520) ──
//   {
//     name: "mixer",
//     bbox: { x: 504, y:  48, w: 56, h: 298 },
//     controls: ["osc1VolKnob", "osc2VolKnob", "ringModVolKnob", "noiseVolKnob", "noiseColorButton"],
//   },
//
//   // ── CONTROL (pitch-bend / vibrato, bottom of osc/mixer column) ──
//   {
//     name: "control",
//     bbox: { x: 291, y: 413, w: 269, h: 35 },
//     controls: [
//       "bendDownRangeMenu", "bendUpRangeMenu", "lockBendRangeButton",
//       "bendOsc2OnlyButton", "vibratoWaveButton", "vibratoRateKnob",
//     ],
//   },
//
//   // ── FILTER (top-center; panel contains 2-pole and 4-pole modes that share footprint) ──
//   {
//     name: "filter",
//     bbox: { x: 601, y:  20, w: 182, h: 161 },
//     controls: [
//       "filter4PoleModeButton", "filterCutoffKnob", "filterResonanceKnob", "filterEnvAmountKnob",
//       "filterKeyTrackKnob", "filterModeKnob",
//       "filter2PoleBPBlendButton", "filter2PolePushButton",
//       "filter4PoleXpanderButton", "filterXpanderModeMenu",
//       "filterModeLabel", "filterOptionsLabel",
//     ],
//   },
//
//   // ── LFO (center; LFO1 and LFO2 share the same footprint, radio-selected) ──
//   {
//     name: "lfo",
//     bbox: { x: 598, y: 213, w: 191, h: 235 },
//     controls: [
//       "lfo1SelectButton", "lfo2SelectButton",
//       // LFO 1
//       "lfo1TempoSyncButton", "lfo1RateKnob", "lfo1ModAmount1Knob", "lfo1ModAmount2Knob",
//       "lfo1Wave1Knob", "lfo1Wave2Knob", "lfo1Wave3Knob", "lfo1PWSlider", "lfo1Wave2Label",
//       "lfo1ToOsc1PitchButton", "lfo1ToOsc2PitchButton", "lfo1ToFilterCutoffButton",
//       "lfo1ToOsc1PWButton",    "lfo1ToOsc2PWButton",    "lfo1ToVolumeButton",
//       // LFO 2 (same x/y as LFO 1)
//       "lfo2TempoSyncButton", "lfo2RateKnob", "lfo2ModAmount1Knob", "lfo2ModAmount2Knob",
//       "lfo2Wave1Knob", "lfo2Wave2Knob", "lfo2Wave3Knob", "lfo2PWSlider", "lfo2Wave2Label",
//       "lfo2ToOsc1PitchButton", "lfo2ToOsc2PitchButton", "lfo2ToFilterCutoffButton",
//       "lfo2ToOsc1PWButton",    "lfo2ToOsc2PWButton",    "lfo2ToVolumeButton",
//     ],
//   },
//
//   // ── FILTER ENVELOPE (top-right row of 4 knobs + 2 sliders) ──
//   {
//     name: "filterEnv",
//     bbox: { x: 833, y:  20, w: 266, h: 121 },
//     controls: [
//       "filterEnvInvertButton",
//       "filterEnvAttackKnob", "filterEnvDecayKnob", "filterEnvSustainKnob", "filterEnvReleaseKnob",
//       "filterEnvAttackCurveSlider", "velToFilterEnvSlider",
//     ],
//   },
//
//   // ── AMP ENVELOPE (filterEnv row + 127 px down) ──
//   {
//     name: "ampEnv",
//     bbox: { x: 850, y: 175, w: 249, h: 75 },
//     controls: [
//       "ampEnvAttackKnob", "ampEnvDecayKnob", "ampEnvSustainKnob", "ampEnvReleaseKnob",
//       "ampEnvAttackCurveSlider", "velToAmpEnvSlider",
//     ],
//   },
//
//   // ── VOICE VARIATION (slop row + 2 rows of pans + voice LEDs) ──
//   {
//     name: "voice",
//     bbox: { x: 850, y: 291, w: 247, h: 162 },
//     controls: [
//       "portamentoSlopKnob", "filterSlopKnob", "envelopeSlopKnob", "levelSlopKnob",
//       "pan1Knob", "pan2Knob", "pan3Knob", "pan4Knob",
//       "pan5Knob", "pan6Knob", "pan7Knob", "pan8Knob",
//       // Plus 32 voiceNLED + 32 voiceNBG display-only widgets (omitted from this list — see Notes)
//     ],
//   },
//
//   // ── PROGRAMMER (footer row across the entire width) ──
//   {
//     name: "programmer",
//     bbox: { x: 56, y: 504, w: 1040, h: 33 },
//     controls: [
//       "patchNumberMenu", "patchNameLabel",
//       "prevPatchButton", "nextPatchButton", "savePatchButton", "undoPatchButton",
//       "initPatchButton", "randomizePatchButton", "groupSelectButton",
//       ...Array.from({length:16}, (_,i) => `select${i+1}Button`),
//     ],
//   },
// ];
//
// ---------------------------------------------------------------------------
// SECTION 5: Widget primitives needed
// ---------------------------------------------------------------------------
//
// The current /home/flibb/OctOBX/src/obxd-knob.ts exports TWO primitives:
//  - createObxdKnob(opts) — rotary SVG arc knob, 40×40, sweep -135° to +135°,
//    drag vertical, wheel/keyboard nav, double-click reset. Already matches
//    OB-Xf's Knob rotation geometry exactly (angle = (2·v − 1)·π·0.75).
//  - createObxdToggle(opts) — <button> with obxd-toggle-on class, click toggles,
//    aria-pressed.
//
// OB-Xf uses FIVE C++ widget classes; the table below maps each to what the
// downstream agent must add.
//
//   OB-Xf widget                                  | OctOBX status      | Action required
//   ----------------------------------------------+--------------------+---------------------------
//   Knob (rotary, d attr, default 40×40)         | Already supported  | None. Optionally restyle to look like OB-Xf's 2-layer SVG.
//   Knob in HORIZONTAL slider mode (w>h, slider-h, fh=9) | NOT supported | Add createObxdSliderH(opts) — horizontal track 47×12 with a draggable thumb; bipolar fill from center if range spans 0. Used by: filterEnvAttackCurveSlider, velToFilterEnvSlider, ampEnvAttackCurveSlider, velToAmpEnvSlider.
//   Knob in VERTICAL slider mode (h>w, slider-v, fh=9) | NOT supported | Add createObxdSliderV(opts) — vertical track 12×47 with thumb. Used by: lfo1PWSlider, lfo2PWSlider. (Could be one createObxdSlider with an orientation field.)
//   ToggleButton (button* assets, 2-state)       | Already supported  | None. Note OB-Xf has many visual variants (button, button-slim, button-clear, button-clear-red, button-clear-white, button-alt, button-lock, button-tuning, button-cogwheel, button-keytrack, button-reassign, button-slim-alt, button-slim-vibrato-wave, button-slim-noise) — these are art-only variants of the same widget; downstream agent can either ship the SVGs or use CSS to differentiate.
//   MultiStateButton (3-state; cycles 0→1→2 on click, Cmd-click reverses) | NOT supported | Add createObxdTriState(opts) — clicking cycles 0 → 0.5 → 1 → 0 (normalized to numStates-1 steps). Cmd-click (or right-click in OB-Xf) cycles backwards. Value mapping: stepSize = 1/(numStates-1) = 0.5 for 3 states. Used by: all 13 LFO routing buttons + noiseColorButton.
//   ButtonList (dropdown; left-click opens popup, mouse-wheel advances) | NOT supported | Add createObxdSelector(opts) — image-button that opens a <select>-like popup menu. Asset is a tall multi-frame strip (one frame per choice). Used by: all 7 parameter-bound selectors + 8 MPE matrix menus + mpeGlideRangeMenu (special).
//   ImageMenu (image-only button, click opens popup menu) | NOT supported (only used for mainMenu) | Either reuse createObxdToggle (if you don't need a popup) or add a tiny createObxdImageButton(opts) that wraps a button + onClick callback. Used by: only mainMenu.
//
// Decorative Label widget (image strip with setCurrentFrame(i) API) is NOT
// supported. OB-Xf uses it for:
//  - Section backgrounds (masterBGLabel, globalBGLabel)
//  - State-driven icons (mpeLinesLabel, filterModeLabel, filterOptionsLabel,
//    osc1TriangleLabel, osc1PulseLabel, osc2TriangleLabel, osc2PulseLabel,
//    lfo1Wave2Label, lfo2Wave2Label)
//  - Voice LEDs (voice1LED … voice32LED, with paired voiceNBG)
//
// Recommendation: add createObxdImageStrip(opts) that takes
// { asset, frameCount, currentFrame, width, height } and renders frame N of an
// SVG/PNG sprite. The downstream agent will need this for at least the voice
// LEDs (32 instances) and the filter mode/options labels.
//
// Modal dialogs (AboutScreen, SaveDialog) are full-canvas overlays — outside
// the scope of obxd-knob.ts. The downstream agent can implement them as plain
// HTML <dialog> elements.
//
// ### Slider SVG shape requirements
// Inspecting the OB-Xf SVGs:
//  - slider-h-layer1.svg = 47×12 horizontal track (rounded rect, dark fill, thin outline)
//  - slider-h-layer2.svg = thumb (the moving part)
//  - slider-v-layer1.svg = 12×47 vertical track (same style rotated)
//  - slider-v-layer2.svg = thumb
//
// Both layers are 47×12 (h) or 12×47 (v). The slider paint code in Knob.h
// (HORIZONTAL/VERTICAL branches, lines 509-525) translates layer 2 by
// v01·(width−thumbW) or −v01·(height−thumbH).
//
// Bipolar sliders: when min === −max (the MPE amount knobs and any future
// bipolar slider), JUCE LookAndFeel (LookAndFeel::drawLinearSlider, lines
// 257-289) fills from the zero crossing toward the thumb. This applies to the
// MPE amount knobs only (which use a different code path — they're Knob
// instances with setRange(-1, 1) but the slider visual style isn't engaged
// because they have d not w/h/fh). The OctOBX agent should still implement
// bipolar fill for any horizontal/vertical slider whose range includes zero.
//
// ---------------------------------------------------------------------------
// SECTION 6: Notes & caveats
// ---------------------------------------------------------------------------
//
// ### Default-value discrepancies
//  - Osc2Vol (ring mod oscillator mix): knobRegistry default is 1.0, but
//    ParameterList.h line 158 sets withDefault(0.f). The attachment uses the
//    ParameterList default (engine truth), but the Knob's dblClickReturnValue
//    uses the registry's 1.0. Recommend: use ParameterList's 0.0 as authoritative.
//  - LFO1Wave1 / LFO2Wave1: registry default 0.5, ParameterList
//    customLFOWave(...).withDefault(-1.f) → normalized 0. Same situation as above.
//  - FilterEnvAttackCurve / AmpEnvAttackCurve / VelToFilterEnv / VelToAmpEnv /
//    LFO1PW / LFO2PW: registered as Knob but rendered as linear sliders (because
//    the XML gives w/h/fh, no d). The Knob's svgTranslationMode flips to
//    HORIZONTAL/VERTICAL. Emits value 0..1 — same normalized range as the other
//    knobs.
//
// ### ID/Name asymmetries (case-sensitive streaming IDs)
// Several SynthParam::ID strings differ from what the parameter name implies:
//  - Osc1Vol → ID string is "Osc1Mix" (and Osc2Vol → "Osc2Mix", RingModVol →
//    "RingModMix", NoiseVol → "NoiseMix"). Streaming IDs use "Mix"; display
//    names use "Volume". The downstream agent must use the ID strings for
//    parameter addressing (they're the streaming names).
//  - FilterKeyTrack → ID string is "FilterKeyFollow".
//  - BendUpRange → ID string is "PitchBendUp"; BendDownRange → "PitchBendDown".
//
// The ControlSpec list above uses the canonical ID strings (right-hand side of
// `static const std::string X{"..."}`). NOTE: the obxfControls array as
// persisted uses the human-friendly left-hand labels (e.g. "Osc1Vol") for the
// `id` field — that is what the explorer emitted verbatim. If exact streaming
// IDs are required, apply the asymmetry mapping above (see also
// src/obxf-param-mappings.ts).
//
// ### Filter mode visibility rules (CRITICAL)
// The filter section has mutually-exclusive control sets. Replicate this logic
// exactly (from ObxfEditorTheme.cpp lines 322-343):
//   fourPole = Filter4PoleMode (toggle state)
//   xpander  = Filter4PoleXpander (toggle state)
//
//   filter2PoleBPBlendButton .visible = !fourPole
//   filter2PolePushButton   .visible = !fourPole
//   filter4PoleXpanderButton.visible =  fourPole
//   filterModeKnob          .visible = !(fourPole && xpander)
//   filterXpanderModeMenu   .visible =  fourPole && xpander
//
//   filterModeLabel.currentFrame     = fourPole ? (xpander ? 3 : 2) : (bpBlend ? 1 : 0)
//   filterOptionsLabel.currentFrame  = fourPole ? 1 : 0
// Re-evaluate on every change to Filter4PoleMode or Filter4PoleXpander.
//
// ### LFO panel radio group
//  - lfo1SelectButton / lfo2SelectButton are in JUCE radio group 1 (mutually
//    exclusive).
//  - They alternate panelGroups["lfo"] between panel 0 (LFO1 widgets) and
//    panel 1 (LFO2 widgets).
//  - LFO1 and LFO2 widgets occupy the same screen coordinates — only one set
//    is visible at a time.
//  - The active panel index is stored in processor.selectedLFOIndex.
//
// ### MTS-ESP panel toggle
//  - mtsSettingsButton toggles panelGroups["master"] between panel 0 (master
//    knobs) and panel 1 (MTS-ESP widgets).
//  - Also flips masterBGLabel.currentFrame between 0 and 1.
//  - State stored in processor.selectedMTSESPPanel.
//
// ### MPE panel toggle + child radio group
//  - mpeSettingsButton toggles panelGroups["global"] between panel 0 (global)
//    and panel 1 (MPE).
//  - Also flips globalBGLabel.currentFrame between 0 and 1.
//  - When the MPE panel is visible, a child PanelGroup cycles between 4
//    sub-panels (Strike/Lift/Press/Slide) via radio group 2.
//  - Each sub-panel shows 4 widgets (dest1/amt1/dest2/amt2) at the same screen
//    coordinates.
//  - The 8 MPE amount knobs are bipolar (setRange(-1, 1, 0.001)) and have
//    custom text/value converters ("N.N %"). They drive the VoiceMatrix, not a
//    SynthParam.
//  - The 8 MPE destination menus have runtime-populated choice lists (first
//    entry always "None", followed by matrixCommonTargets() + per-source
//    extras). Choice lists are NOT in theme.xml or ParameterList — they come
//    from VoiceMatrix.h. The downstream agent will need to either hardcode a
//    reasonable target list or extract it separately.
//  - mpeLinesLabel is a 4-frame strip; currentFrame tracks the active dimension.
//
// ### Voice LEDs (anomaly)
//  - 32 LED widgets (voice1LED … voice32LED) are defined in theme.xml, each
//    with a paired voiceNBG background.
//  - Only 1..N LEDs are visible, where N = polyphonyMenu.value (1..32).
//  - LED alpha = cbrt(voiceStatusValue[i]) (cubed-root envelope follower).
//  - All 32 LEDs use 4 distinct assets cycled by row: label-led1, label-led2,
//    label-led3, label-led4. The asset is chosen by which / MAX_PANNINGS
//    (i.e. voice/8 integer-divided).
//  - LED x-positions repeat every 4 voices (895, 964, 1033, 1102); y increases
//    by 10px per "ledger row" of 4.
//
// ### Programmer selector buttons
//  - select1Button … select16Button (16 widgets, x steps of 33 starting at 578).
//  - Each has a paired selectNLabel at the same bounds (drawn underneath; uses
//    button-group-patch asset).
//  - The buttons themselves have no asset in theme.xml — the C++ code hardcodes
//    "button-group-patch" regardless of pic attribute.
//  - setTriggeredOnMouseDown(true) + setClickingTogglesState(false) — they
//    behave as momentary triggers, not toggles.
//
// ### UnisonVoicesMenu dimming
//  - When Unison toggle is OFF, unisonVoicesMenu.setAlpha(0.25) (dimmed but
//    still interactive). Re-evaluated in idle().
//
// ### Tri-state button behavior
//  - 3 states: 0 (Off) → 0.5 (On) → 1 (Inverted) → 0.
//  - Left-click: advance forward. Cmd-click: advance backward.
//  - Right-click: opens parameter context menu (host menu).
//  - Value mapping: stepSize = 1.0 / (numStates - 1).
//  - All 13 tri-states in OB-Xf use numStates=3; visual asset variants are
//    button-dual, button-dual-alt, button-slim-noise.
//
// ### Tempo-syncable parameters
//  - LFO1Rate / LFO2Rate have a tempostsyncable(true) flag in their
//    ParamMetaData.
//  - When the corresponding LFO{1,2}TempoSync toggle is on, the displayed
//    value switches from Hz to a synced rate name (e.g. "1/16", "1/8.", etc.)
//    — driven by ObxfParameterFloat::stringFromValue checking
//    tempoSyncToggle->getValue() > 0.5f.
//
// ### Knob drag modifiers (per-parameter)
//  - transposeKnob: Alt-drag snaps to whole octaves ([-2..2]).
//  - osc1PitchKnob / osc2PitchKnob: Cmd-drag snaps to semitones ([-24..24]);
//    Alt-drag snaps to musical intervals {-24,-19,-17,-12,-7,-5,0,5,7,12,17,19,24}.
//  - envToPitchAmountKnob: Cmd-drag snaps to semitones [0..36]; Alt-drag snaps
//    to {0,5,7,12,17,19,24,29,31,36}.
//  - These are per-knob lambdas set in knobRegistry() (lines 107-117, 124-129,
//    142-153). The OctOBX knob's existing shift-drag for fine control can stay;
//    add Cmd/Alt handlers per-control if you want parity.
//
// ### Pitch-bend lock & HQ lock
//  - lockBendRangeButton (special): when toggled on, captures current
//    BendUpRange / BendDownRange into processor.lockedPBUpRange /
//    lockedPBDownRange. While locked, those two selectors don't track patch
//    loads.
//  - lockHQButton (special): same idea for HQMode.
//  - Neither has a SynthParam::ID — they're processor flags.
//
// ### Modal dialogs
//  - SaveDialog (save-patch overlay): widgets named savePatchDialog,
//    savePatchNameLabel, savePatchAuthorLabel, savePatchProjectLabel,
//    savePatchCategoryMenu, savePatchLicenseLabel, savePatchOKButton,
//    savePatchCancelButton. Their theme.xml entries use LOCAL coordinates
//    (relative to the dialog, not the editor). The dialog background is
//    label-bg-save-patch.svg (246×328).
//  - AboutScreen: full-canvas overlay, no theme.xml entries — it's a
//    self-contained component.
//
// ### mpeSlideBipolarButton (anomaly — likely a bug or future feature)
//  - Referenced in panelGroupDefinitions() line 412 as belonging to the MPE
//    panel widget list.
//  - NOT present in theme.xml and not handled in createSpecialWidgets.
//  - Result: PanelGroup::resolve() finds no matching component, so the entry is
//    silently skipped. The button does not exist in the running UI. Treat as
//    TODO / future feature.
//
// ### OctOBX integration caveats
//  - The OB-Xf IDs use PascalCase streaming names (FilterCutoff, Osc1Mix,
//    etc.). OctOBX's synth uses integer indices into
//    ParamsEnum.h. These are incompatible — the downstream agent must add a
//    mapping layer or change the OctOBX bridge to accept string IDs.
//  - OctOBX's synth engine is OB-Xf. Parameter semantics
//    differ from OB-Xf (e.g. OB-Xf adds Osc2Keytrack, VoiceReassign,
//    Filter2PolePush, Filter4PoleXpander, FilterXpanderMode, all the MPE
//    matrix, LFO1PW, LFO2PW, EnvLegatoMode, NotePriority,
//    BendUpRange/BendDownRange, FilterEnvAttackCurve, VelToFilterEnv,
//    AmpEnvAttackCurve, VelToAmpEnv, PortamentoSlop, FilterSlop, EnvelopeSlop,
//    LevelSlop, PanVoice1..8, NoiseColor). The downstream agent should confirm
//    which params the OctOBX WASM engine actually exposes before wiring
//    all 104 controls.
//  - OctOBX's existing createObxdKnob uses CSS variables (--accent, --panel,
//    --border). The OB-Xf theme uses fixed RGB. Either redefine those CSS vars
//    to match obxfTheme or pass colors explicitly.
//
// === END EXPLORER NOTES ======================================================
