/**
 * obxf-param-mappings.ts — OB-Xd → OB-Xf parameter mapping spec (generated).
 *
 * AUTO-GENERATED by tools/gen-param-table.mjs — DO NOT EDIT THIS FILE BY
 * HAND. Source of truth: tools/param-spec.mjs (see tools/PARAM_SPEC.md).
 *
 * Regenerate with:    node tools/gen-param-table.mjs
 * Freshness check:    node tools/gen-param-table.mjs --check   (CI gate)
 *
 * WARNING — HAND EDITS ARE OVERWRITTEN:
 *   Every exported value below is emitted verbatim from the spec. Change
 *   the spec (tools/param-spec.mjs), not this file. The machine-readable
 *   dump of the same data lives in src/generated/param-table.json.
 *
 * SHAPE NOTES vs the pre-generation hand-maintained file:
 *   - paramMappings now has exactly 80 rows (legacy indices 0..79 once
 *     each). BENDRANGE (6) is ONE row; its split second half is carried
 *     by the secondaryNewId/secondaryMethod fields ("PitchBendDown" /
 *     "processBendDownRange"). The old file duplicated the row (81 rows).
 *   - Rows gained generated fields: transformKind (null on removed rows),
 *     specialInline, drumClass, drumRestoreSkip, and the BENDRANGE pair.
 *   - canonicalNewParamOrder = the 28 OB-Xf-only streaming names by
 *     canonical ordinal (SynthParam.h declaration order). This differs
 *     from the legacy runtime sentinel order frozen in
 *     tools/new-param-order-v1.json.
 *   - paramTransforms provides PURE forward (legacy→engine) and invert
 *     (engine→legacy) functions per streaming name so tests can golden
 *     the transform math without touching the C side. LFO1Rate models
 *     only the free-running path; LFO1TempoSync is value-1:1 — both are
 *     specialInline in C (mirror-state dependent) and carry invert null.
 */

export const PARAM_COUNT = 80;
export const NEW_PARAM_BASE = 200;
export const NEW_PARAM_COUNT = 28;
export const BENDRANGE_LEGACY_INDEX = 6;

export type DrumClass = "none" | "global" | "smoother" | "voice";
export type TransformKind =
    | "IDENTITY" | "MUL" | "SPLIT_BENDRANGE" | "VOICE_COUNT" | "OCTAVE_TRANSPOSE"
    | "LOGSC_INVLOGSC" | "BOOL_BLEND" | "BOOL_TRISTATE" | "NOTEPRIORITY"
    | "PAN" | "LFO1_RATE" | "LFO1_SYNC";

export type ParamMapping = {
    legacyIndex: number;                 // old ParamsEnum.h integer, 0..79
    legacyName: string;                  // old ParamsEnum.h identifier, e.g. "CUTOFF"
    legacyMethod: string;                // old SynthEngine method, e.g. "processCutoff"
    newId: string;                       // OB-Xf SynthParam::ID streaming string ("" = removed)
    newMethod: string | null;            // new SynthEngine method; null if removed/no-op
    secondaryNewId?: string;             // set only on BENDRANGE: "PitchBendDown"
    secondaryMethod?: string;            // set only on BENDRANGE: "processBendDownRange"
    transformKind: TransformKind | null; // closed-vocabulary kind; null on removed rows
    specialInline: boolean;              // true for LFOFREQ(17)/LFO_SYNC(72) — C handles inline
    drumClass: DrumClass;                // PCM drum routing (instance 9)
    drumRestoreSkip: boolean;            // worklet DRUM_STRUCTURAL_SKIP (orthogonal axis)
    newNotes?: string;                   // caveats (rescale math, renames, ...)
};

/**
 * The closed transform vocabulary (mirrors TRANSFORM_KINDS in
 * tools/param-spec.mjs). Keys are the kinds; values are one-line docs of
 * the legacy 0..1 → native 0..1 math. Invert semantics per kind are
 * documented in tools/PARAM_SPEC.md §Invert semantics.
 */
export const transformKinds: Readonly<Record<TransformKind, string>> = {
    IDENTITY: "value passes through unchanged (any internal logsc/linsc happens inside the engine)",
    MUL: "native = legacy * factor (invert: * reciprocal)",
    SPLIT_BENDRANGE: "semitones = v > threshold ? semitonesHigh : semitonesLow; native = semitones / maxBendRange, written to BOTH halves",
    VOICE_COUNT: "old voices = clamp(round(v*7)+1, 1..8); native = (voices-1+0.5)/MAX_VOICES",
    OCTAVE_TRANSPOSE: "transpose = clamp(round(v*4)+1, 0..4); native = transpose * 0.25",
    LOGSC_INVLOGSC: "xdLogsc(v, xd) [/ preDivisor], then unmap through xf (invLogsc / invLinsc / baked-identity per curve)",
    BOOL_BLEND: "LFO wave bool → continuous blend: native = v >= 0.5 ? 0 : 0.5",
    BOOL_TRISTATE: "LFO destination bool → tri-state {Off,On,Inv}: native = v >= 0.5 ? 0.5 : 0",
    NOTEPRIORITY: "bool → tri-state, STRICT >: native = v > 0.5 ? 0 : 0.5",
    PAN: "value identity; the engine method takes an extra voice index — processPan(v, idx)",
    LFO1_RATE: "specialInline (C-side, sync-aware bucket map); the pure forward here models the FREE path only",
    LFO1_SYNC: "specialInline (C-side re-dispatch of LFOFREQ); the value itself is 1:1",
};

/**
 * The 28 OB-Xf-only streaming names ordered by canonical ordinal — the
 * declaration order of streaming IDs in SynthParam.h filtered to params
 * with no legacy ancestor. UI sentinel index = NEW_PARAM_BASE + position.
 * NOTE: intentionally differs from the runtime sentinel order frozen in
 * tools/new-param-order-v1.json (see tools/PARAM_SPEC.md).
 */
export const canonicalNewParamOrder: readonly string[] = [
    "UnisonVoices",
    "VoiceReassign",
    "Osc2Keytrack",
    "EnvToPitchInvert",
    "EnvToPWInvert",
    "RingModMix",
    "NoiseColor",
    "VibratoWave",
    "Filter4PoleXpander",
    "FilterXpanderMode",
    "LFO1PW",
    "LFO1ToVolume",
    "LFO2TempoSync",
    "LFO2Wave1",
    "LFO2Wave2",
    "LFO2Wave3",
    "LFO2PW",
    "LFO2Rate",
    "LFO2ModAmount1",
    "LFO2ModAmount2",
    "LFO2ToOsc1Pitch",
    "LFO2ToOsc2Pitch",
    "LFO2ToFilterCutoff",
    "LFO2ToOsc1PW",
    "LFO2ToOsc2PW",
    "LFO2ToVolume",
    "FilterEnvAttackCurve",
    "AmpEnvAttackCurve",
];

export const paramMappings: ParamMapping[] = [

    // ---- index 0..11: master / global / velocity ----
    { legacyIndex: 0 , legacyName: "UNDEFINED"         , legacyMethod: ""                              , newId: ""                  , newMethod: null                       , transformKind: null              , specialInline: false, drumClass: "none"    , drumRestoreSkip: false, newNotes: "Sentinel / no-op. C is_global_drum_param() also lists it (harmless either way)." },
    { legacyIndex: 1 , legacyName: "MIDILEARN"         , legacyMethod: "(UI-only)"                     , newId: ""                  , newMethod: null                       , transformKind: null              , specialInline: false, drumClass: "none"    , drumRestoreSkip: false, newNotes: "REMOVED: UI-only, no engine action, no OB-Xf equivalent. C is_global_drum_param() also lists it (no-op either way)." },
    { legacyIndex: 2 , legacyName: "VOLUME"            , legacyMethod: "processVolume"                 , newId: "Volume"            , newMethod: "processVolume"            , transformKind: "IDENTITY"        , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "1:1; both engines linsc(v,0,0.30) internally. Sets synth-global volume." },
    { legacyIndex: 3 , legacyName: "VOICE_COUNT"       , legacyMethod: "setVoiceCount"                 , newId: "Polyphony"         , newMethod: "processPolyphony"         , transformKind: "VOICE_COUNT"     , specialInline: false, drumClass: "global"  , drumRestoreSkip: true , newNotes: "RESCALE: old 1..8 voices → new polyphony midpoint (voices-1+0.5)/32. Invert (representative): voices=clamp(round(n*32),1,8) → legacy=(voices-1)/7. drumRestoreSkip: initDrumMode owns drum polyphony." },
    { legacyIndex: 4 , legacyName: "TUNE"              , legacyMethod: "processTune"                   , newId: "Tune"              , newMethod: "processTune"              , transformKind: "IDENTITY"        , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "1:1; both engines v*2-1 internally." },
    { legacyIndex: 5 , legacyName: "OCTAVE"            , legacyMethod: "processOctave"                 , newId: "Transpose"         , newMethod: "processTranspose"         , transformKind: "OCTAVE_TRANSPOSE", specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "SEMANTIC SHIFT: old (round(v*4)-2)*12 st; new round((v*2-1)*24) st. Importer: transpose=clamp(round(v*4)+1,0..4)*0.25. Invert (representative): transpose=round(n*4) → legacy=clamp((transpose-1)/4,0,1)." },
    { legacyIndex: 6 , legacyName: "BENDRANGE"         , legacyMethod: "procPitchWheelAmount"          , newId: "PitchBendUp"       , newMethod: "processBendUpRange"       , secondaryNewId: "PitchBendDown", secondaryMethod: "processBendDownRange", transformKind: "SPLIT_BENDRANGE" , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "SPLIT — ONE spec row covering BOTH halves: n=(v>0.5?12:2)/48 written to processBendUpRange AND processBendDownRange (transform.secondaryNewId=PitchBendDown, secondaryMethod=processBendDownRange) with the SAME value. Legacy rows total 80, not 81. Invert (representative): range=round(n*48) → legacy = range>7 ? 1 : 0." },
    { legacyIndex: 7 , legacyName: "BENDOSC2"          , legacyMethod: "procPitchWheelOsc2Only"        , newId: "BendOsc2Only"      , newMethod: "processBendOsc2Only"      , transformKind: "IDENTITY"        , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold inside both engines." },
    { legacyIndex: 8 , legacyName: "LEGATOMODE"        , legacyMethod: "processLegatoMode"             , newId: "EnvLegatoMode"     , newMethod: "processEnvLegatoMode"     , transformKind: "IDENTITY"        , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "Importer copies 1:1 (quantization happens in the engine). Same 4 modes (Both/Filter/Amp/Retrigger); bucket boundaries differ at v=0.5." },
    { legacyIndex: 9 , legacyName: "BENDLFORATE"       , legacyMethod: "procModWheelFrequency"         , newId: "VibratoRate"       , newMethod: "processVibratoLFORate"    , transformKind: "LOGSC_INVLOGSC"  , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "RESCALE+RENAME: hzXd=logsc(v,3,10); native=invLinsc(hzXd,2,12). xf curve is LIN, not log. Invert (exact): hz=linsc(n,2,12) → legacy=invLogsc(hz,3,10,19)." },
    { legacyIndex: 10, legacyName: "VFLTENV"           , legacyMethod: "procFltVelocityAmount"         , newId: "VelToFilterEnv"    , newMethod: "processVelToFilterEnv"    , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1." },
    { legacyIndex: 11, legacyName: "VAMPENV"           , legacyMethod: "procAmpVelocityAmount"         , newId: "VelToAmpEnv"       , newMethod: "processVelToAmpEnv"       , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1." },

    // ---- index 12..22: allocation / unison / LFO freq+wave ----
    { legacyIndex: 12, legacyName: "ASPLAYEDALLOCATION", legacyMethod: "procAsPlayedAlloc"             , newId: "NotePriority"      , newMethod: "processNotePriority"      , transformKind: "NOTEPRIORITY"    , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "BOOL→TRI: native = v>0.5 ? 0 : 0.5 (STRICT >). High state (1.0) has no ancestor. Invert (representative): legacy = n>0.25 ? 0 : 1." },
    { legacyIndex: 13, legacyName: "PORTAMENTO"        , legacyMethod: "processPortamento"             , newId: "Portamento"        , newMethod: "processPortamento"        , transformKind: "IDENTITY"        , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "1:1; both engines logsc(1-v,0.14,250,150) internally." },
    { legacyIndex: 14, legacyName: "UNISON"            , legacyMethod: "processUnison"                 , newId: "Unison"            , newMethod: "processUnison"            , transformKind: "IDENTITY"        , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold." },
    { legacyIndex: 15, legacyName: "UDET"              , legacyMethod: "processDetune"                 , newId: "UnisonDetune"      , newMethod: "processUnisonDetune"      , transformKind: "LOGSC_INVLOGSC"  , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "RESCALE: dXd=logsc(v,0.001,0.90); native=invLogsc(dXd,0.001,1.0). Invert (exact): d=logsc(n,0.001,1.0) → legacy=invLogsc(d,0.001,0.90)." },
    { legacyIndex: 16, legacyName: "OSC2_DET"          , legacyMethod: "processOsc2Det"                , newId: "Osc2Detune"        , newMethod: "processOsc2Detune"        , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines logsc(v,0.001,0.6) internally." },
    { legacyIndex: 17, legacyName: "LFOFREQ"           , legacyMethod: "processLfoFrequency"           , newId: "LFO1Rate"          , newMethod: "processLFO1Rate"          , transformKind: "LFO1_RATE"       , specialInline: true , drumClass: "global"  , drumRestoreSkip: false, newNotes: "SPECIAL INLINE: free path logsc(v,0,50,120)→invLogsc(·,0,250,3775) (~75x range shift); synced path (LFO_SYNC mirror>0.5) 9→21 bucket table. Reads instance mirror → stays inline in C before AND after the refactor. Sets synth.globalLFO (shared LFO1) → drumClass global." },
    { legacyIndex: 18, legacyName: "LFOSINWAVE"        , legacyMethod: "processLfoSine"                , newId: "LFO1Wave1"         , newMethod: "processLFO1Wave1"         , transformKind: "BOOL_BLEND"      , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "BOOL→BLEND: native = v>=0.5 ? 0 : 0.5 (Sine/Triangle). Shared globalLFO → drumClass global. Invert (representative): legacy = n<0.25 ? 1 : 0." },
    { legacyIndex: 19, legacyName: "LFOSQUAREWAVE"     , legacyMethod: "processLfoSquare"              , newId: "LFO1Wave2"         , newMethod: "processLFO1Wave2"         , transformKind: "BOOL_BLEND"      , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "BOOL→BLEND, same transform (Pulse/Saw). Invert (representative): legacy = n<0.25 ? 1 : 0." },
    { legacyIndex: 20, legacyName: "LFOSHWAVE"         , legacyMethod: "processLfoSH"                  , newId: "LFO1Wave3"         , newMethod: "processLFO1Wave3"         , transformKind: "BOOL_BLEND"      , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "BOOL→BLEND, same transform (S&H/S&G). Invert (representative): legacy = n<0.25 ? 1 : 0." },
    { legacyIndex: 21, legacyName: "LFO1AMT"           , legacyMethod: "processLfoAmt1"                , newId: "LFO1ModAmount1"    , newMethod: "processLFO1ModAmount1"    , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines logsc(logsc(v,0,1,60),0,60,10) internally." },
    { legacyIndex: 22, legacyName: "LFO2AMT"           , legacyMethod: "processLfoAmt2"                , newId: "LFO1ModAmount2"    , newMethod: "processLFO1ModAmount2"    , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "AMBIGUOUS NAME: old LFO2AMT is LFO1 second mod amount, NOT LFO2. 1:1; both engines linsc(v,0,0.7)." },

    // ---- index 23..27: LFO1 routing (bool → tri-state) ----
    { legacyIndex: 23, legacyName: "LFOOSC1"           , legacyMethod: "processLfoOsc1"                , newId: "LFO1ToOsc1Pitch"   , newMethod: "processLFO1ToOsc1Pitch"   , transformKind: "BOOL_TRISTATE"   , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "BOOL→TRI {Off,On,Inv}=0/0.5/1: native = v>=0.5 ? 0.5 : 0. Inv state has no ancestor. Invert (representative): legacy = n>=0.25 ? 1 : 0." },
    { legacyIndex: 24, legacyName: "LFOOSC2"           , legacyMethod: "processLfoOsc2"                , newId: "LFO1ToOsc2Pitch"   , newMethod: "processLFO1ToOsc2Pitch"   , transformKind: "BOOL_TRISTATE"   , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "BOOL→TRI, same transform. Invert (representative): legacy = n>=0.25 ? 1 : 0." },
    { legacyIndex: 25, legacyName: "LFOFILTER"         , legacyMethod: "processLfoFilter"              , newId: "LFO1ToFilterCutoff", newMethod: "processLFO1ToFilterCutoff", transformKind: "BOOL_TRISTATE"   , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "BOOL→TRI, same transform. Invert (representative): legacy = n>=0.25 ? 1 : 0." },
    { legacyIndex: 26, legacyName: "LFOPW1"            , legacyMethod: "processLfoPw1"                 , newId: "LFO1ToOsc1PW"      , newMethod: "processLFO1ToOsc1PW"      , transformKind: "BOOL_TRISTATE"   , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "BOOL→TRI, same transform. Invert (representative): legacy = n>=0.25 ? 1 : 0." },
    { legacyIndex: 27, legacyName: "LFOPW2"            , legacyMethod: "processLfoPw2"                 , newId: "LFO1ToOsc2PW"      , newMethod: "processLFO1ToOsc2PW"      , transformKind: "BOOL_TRISTATE"   , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "BOOL→TRI, same transform. NOT LFO2 — LFO1→Osc2PW. Invert (representative): legacy = n>=0.25 ? 1 : 0." },

    // ---- index 28..39: oscillators ----
    { legacyIndex: 28, legacyName: "OSC2HS"            , legacyMethod: "processOsc2HardSync"           , newId: "OscSync"           , newMethod: "processOscSync"           , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold." },
    { legacyIndex: 29, legacyName: "XMOD"              , legacyMethod: "processOsc2Xmod"               , newId: "OscCrossmod"       , newMethod: "processCrossmod"          , transformKind: "MUL"             , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "RESCALE: old v*24 st, new v*48 st → native = v*0.5. Invert (exact): legacy = n*2." },
    { legacyIndex: 30, legacyName: "OSC1P"             , legacyMethod: "processOsc1Pitch"              , newId: "Osc1Pitch"         , newMethod: "processOsc1Pitch"         , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines v*48 st. Importer additionally has an OCTAVE-compensation branch at .fxp import time (runtime dispatch is 1:1)." },
    { legacyIndex: 31, legacyName: "OSC2P"             , legacyMethod: "processOsc2Pitch"              , newId: "Osc2Pitch"         , newMethod: "processOsc2Pitch"         , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines v*48 st. Same importer-side OCTAVE-compensation note as OSC1P." },
    { legacyIndex: 32, legacyName: "OSCQuantize"       , legacyMethod: "processPitchQuantization"      , newId: ""                  , newMethod: null                       , transformKind: null              , specialInline: false, drumClass: "none"    , drumRestoreSkip: false, newNotes: "REMOVED: no runtime param in OB-Xf. Importer only READS it to round osc pitches at import time." },
    { legacyIndex: 33, legacyName: "OSC1Saw"           , legacyMethod: "processOsc1Saw"                , newId: "Osc1SawWave"       , newMethod: "processOsc1Saw"           , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold." },
    { legacyIndex: 34, legacyName: "OSC1Pul"           , legacyMethod: "processOsc1Pulse"              , newId: "Osc1PulseWave"     , newMethod: "processOsc1Pulse"         , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold." },
    { legacyIndex: 35, legacyName: "OSC2Saw"           , legacyMethod: "processOsc2Saw"                , newId: "Osc2SawWave"       , newMethod: "processOsc2Saw"           , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold." },
    { legacyIndex: 36, legacyName: "OSC2Pul"           , legacyMethod: "processOsc2Pulse"              , newId: "Osc2PulseWave"     , newMethod: "processOsc2Pulse"         , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold." },
    { legacyIndex: 37, legacyName: "PW"                , legacyMethod: "processPulseWidth"             , newId: "OscPW"             , newMethod: "processOscPW"             , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines linsc(v,0,0.95) internally." },
    { legacyIndex: 38, legacyName: "BRIGHTNESS"        , legacyMethod: "processBrightness"             , newId: "OscBrightness"     , newMethod: "processOscBrightness"     , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines linsc(v,7000,26000) internally." },
    { legacyIndex: 39, legacyName: "ENVPITCH"          , legacyMethod: "processEnvelopeToPitch"        , newId: "EnvToPitchAmount"  , newMethod: "processEnvToPitchAmount"  , transformKind: "MUL"             , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "RESCALE: old v*36 st, new v*40 st → native = v*(36/40) = v*0.9. Invert (exact): legacy = n*(40/36)." },

    // ---- index 40..50: mixer + filter ----
    { legacyIndex: 40, legacyName: "OSC1MIX"           , legacyMethod: "processOsc1Mix"                , newId: "Osc1Mix"           , newMethod: "processOsc1Volume"        , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: true , newNotes: "1:1. THREE names differ: ID string Osc1Mix, C++ ID constant Osc1Vol, method processOsc1Volume. drumRestoreSkip: initDrumMode silences oscillators for PCM voices." },
    { legacyIndex: 41, legacyName: "OSC2MIX"           , legacyMethod: "processOsc2Mix"                , newId: "Osc2Mix"           , newMethod: "processOsc2Volume"        , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: true , newNotes: "1:1. Same three-name split as OSC1MIX (Osc2Mix / Osc2Vol / processOsc2Volume). drumRestoreSkip: initDrumMode silences oscillators." },
    { legacyIndex: 42, legacyName: "NOISEMIX"          , legacyMethod: "processNoiseMix"               , newId: "NoiseMix"          , newMethod: "processNoiseVolume"       , transformKind: "LOGSC_INVLOGSC"  , specialInline: false, drumClass: "voice"   , drumRestoreSkip: true , newNotes: "LOGSC BAKE: old engine applied logsc(v,0,1,35) INTERNALLY; OB-Xf takes the pre-scaled value → native = logsc(v,0,1,35), xf curve identity (no unmap). Invert (exact): legacy = invLogsc(n,0,1,35). ID NoiseMix (C++ constant NoiseVol), method processNoiseVolume. drumRestoreSkip: noise floor owned by drum init." },
    { legacyIndex: 43, legacyName: "FLT_KF"            , legacyMethod: "processFilterKeyFollow"        , newId: "FilterKeyFollow"   , newMethod: "processFilterKeyTrack"    , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1. Names differ: ID FilterKeyFollow (C++ constant FilterKeyTrack), method processFilterKeyTrack." },
    { legacyIndex: 44, legacyName: "CUTOFF"            , legacyMethod: "processCutoff"                 , newId: "FilterCutoff"      , newMethod: "processFilterCutoff"      , transformKind: "IDENTITY"        , specialInline: false, drumClass: "smoother", drumRestoreSkip: false, newNotes: "1:1; both engines linsc(v,0,120) into the cutoff smoother. drumClass smoother: processX writes the synth-GLOBAL cutoffSmoother — drum layers apply it directly per triggered voice (v->par.filter.cutoff)." },
    { legacyIndex: 45, legacyName: "RESONANCE"         , legacyMethod: "processResonance"              , newId: "FilterResonance"   , newMethod: "processFilterResonance"   , transformKind: "IDENTITY"        , specialInline: false, drumClass: "smoother", drumRestoreSkip: false, newNotes: "1:1; both engines 0.991-logsc(1-v,0,0.991,40). drumClass smoother: resSmoother is synth-global; drum layers set v->filter.setResonance directly." },
    { legacyIndex: 46, legacyName: "MULTIMODE"         , legacyMethod: "processMultimode"              , newId: "FilterMode"        , newMethod: "processFilterMode"        , transformKind: "IDENTITY"        , specialInline: false, drumClass: "smoother", drumRestoreSkip: false, newNotes: "1:1 (old per-voice, new smoother — same range). drumClass smoother: filterModeSmoother is synth-global; drum layers set v->filter.setMultimode directly." },
    { legacyIndex: 47, legacyName: "FILTER_WARM"       , legacyMethod: "processOversampling"           , newId: "HQMode"            , newMethod: "processHQMode"            , transformKind: "IDENTITY"        , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "RENAME+BEHAVIOR: old SetOversample, new SetHQMode AND the engine calls allSoundOff() on toggle — drumClass global so per-voice application cannot cut drum voices mid-trigger." },
    { legacyIndex: 48, legacyName: "BANDPASS"          , legacyMethod: "processBandpassSw"             , newId: "Filter2PoleBPBlend", newMethod: "processFilter2PoleBPBlend", transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold." },
    { legacyIndex: 49, legacyName: "FOURPOLE"          , legacyMethod: "processFourPole"               , newId: "Filter4PoleMode"   , newMethod: "processFilter4PoleMode"   , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold." },
    { legacyIndex: 50, legacyName: "ENVELOPE_AMT"      , legacyMethod: "processFilterEnvelopeAmt"      , newId: "FilterEnvAmount"   , newMethod: "processFilterEnvAmount"   , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines linsc(v,0,140) internally." },

    // ---- index 51..58: envelopes (loudness=Amp, filter=Filter) ----
    { legacyIndex: 51, legacyName: "LATK"              , legacyMethod: "processLoudnessEnvelopeAttack" , newId: "AmpEnvAttack"      , newMethod: "processAmpEnvAttack"      , transformKind: "LOGSC_INVLOGSC"  , specialInline: false, drumClass: "smoother", drumRestoreSkip: true , newNotes: "RESCALE: msXd=logsc(v,4,60000,900); native=invLogsc(msXd/3,4,60000,900) — attack /3 only (decay/release are NOT divided). Invert (exact): msXd=logsc(n,4,60000,900)*3 → legacy=invLogsc(msXd,4,60000,900). drumClass smoother AND drumRestoreSkip — the two flags are orthogonal (direct per-voice setAttack on drum layers; amp attack owned by drum init)." },
    { legacyIndex: 52, legacyName: "LDEC"              , legacyMethod: "processLoudnessEnvelopeDecay"  , newId: "AmpEnvDecay"       , newMethod: "processAmpEnvDecay"       , transformKind: "IDENTITY"        , specialInline: false, drumClass: "smoother", drumRestoreSkip: false, newNotes: "1:1; both engines logsc(v,4,60000,900). Importer does NOT /3 decay. drumClass smoother: direct per-voice setDecay on drum layers." },
    { legacyIndex: 53, legacyName: "LSUS"              , legacyMethod: "processLoudnessEnvelopeSustain", newId: "AmpEnvSustain"     , newMethod: "processAmpEnvSustain"     , transformKind: "IDENTITY"        , specialInline: false, drumClass: "smoother", drumRestoreSkip: false, newNotes: "1:1. drumClass smoother: direct per-voice setSustain on drum layers." },
    { legacyIndex: 54, legacyName: "LREL"              , legacyMethod: "processLoudnessEnvelopeRelease", newId: "AmpEnvRelease"     , newMethod: "processAmpEnvRelease"     , transformKind: "IDENTITY"        , specialInline: false, drumClass: "smoother", drumRestoreSkip: true , newNotes: "1:1; both engines logsc(v,8,60000,900) (NOTE lo=8, unlike LATK/LDEC lo=4). drumClass smoother AND drumRestoreSkip (orthogonal): direct per-voice setRelease on drum layers; release owned by drum init." },
    { legacyIndex: 55, legacyName: "FATK"              , legacyMethod: "processFilterEnvelopeAttack"   , newId: "FilterEnvAttack"   , newMethod: "processFilterEnvAttack"   , transformKind: "LOGSC_INVLOGSC"  , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "RESCALE: msXd=logsc(v,1,60000,900); native=invLogsc(msXd/3,1,60000,900) — filter attack /3 (lo=1, not 4). Invert (exact): msXd=logsc(n,1,60000,900)*3 → legacy=invLogsc(msXd,1,60000,900)." },
    { legacyIndex: 56, legacyName: "FDEC"              , legacyMethod: "processFilterEnvelopeDecay"    , newId: "FilterEnvDecay"    , newMethod: "processFilterEnvDecay"    , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines logsc(v,1,60000,900)." },
    { legacyIndex: 57, legacyName: "FSUS"              , legacyMethod: "processFilterEnvelopeSustain"  , newId: "FilterEnvSustain"  , newMethod: "processFilterEnvSustain"  , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1." },
    { legacyIndex: 58, legacyName: "FREL"              , legacyMethod: "processFilterEnvelopeRelease"  , newId: "FilterEnvRelease"  , newMethod: "processFilterEnvRelease"  , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines logsc(v,1,60000,900)." },

    // ---- index 59..69: slop + pan ----
    { legacyIndex: 59, legacyName: "ENVDER"            , legacyMethod: "processEnvelopeDetune"         , newId: "EnvelopeSlop"      , newMethod: "processEnvelopeSlop"      , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; old setEnvDer(linsc(v,0,1)) internally, new setEnvTimingOffset(v)." },
    { legacyIndex: 60, legacyName: "FILTERDER"         , legacyMethod: "processFilterDetune"           , newId: "FilterSlop"        , newMethod: "processFilterSlop"        , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines linsc(v,0,18) internally." },
    { legacyIndex: 61, legacyName: "PORTADER"          , legacyMethod: "processPortamentoDetune"       , newId: "PortamentoSlop"    , newMethod: "processPortamentoSlop"    , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines linsc(v,0,0.75) internally." },
    { legacyIndex: 62, legacyName: "PAN1"              , legacyMethod: "processPan"                    , newId: "PanVoice1"         , newMethod: "processPan"               , transformKind: "PAN"             , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "Value identity; call processPan(v, 1) — method takes an EXTRA voiceIndex argument. processPan writes synth.pannings (no ForEachVoice) → drumClass global; PCM voice panning comes from Voice::pcmPan." },
    { legacyIndex: 63, legacyName: "PAN2"              , legacyMethod: "processPan"                    , newId: "PanVoice2"         , newMethod: "processPan"               , transformKind: "PAN"             , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "processPan(v, 2). See PAN1." },
    { legacyIndex: 64, legacyName: "PAN3"              , legacyMethod: "processPan"                    , newId: "PanVoice3"         , newMethod: "processPan"               , transformKind: "PAN"             , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "processPan(v, 3). See PAN1." },
    { legacyIndex: 65, legacyName: "PAN4"              , legacyMethod: "processPan"                    , newId: "PanVoice4"         , newMethod: "processPan"               , transformKind: "PAN"             , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "processPan(v, 4). See PAN1." },
    { legacyIndex: 66, legacyName: "PAN5"              , legacyMethod: "processPan"                    , newId: "PanVoice5"         , newMethod: "processPan"               , transformKind: "PAN"             , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "processPan(v, 5). Old OB-Xd MAX_VOICES=8 so PAN5..8 were rarely used." },
    { legacyIndex: 67, legacyName: "PAN6"              , legacyMethod: "processPan"                    , newId: "PanVoice6"         , newMethod: "processPan"               , transformKind: "PAN"             , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "processPan(v, 6). See PAN5." },
    { legacyIndex: 68, legacyName: "PAN7"              , legacyMethod: "processPan"                    , newId: "PanVoice7"         , newMethod: "processPan"               , transformKind: "PAN"             , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "processPan(v, 7). See PAN5." },
    { legacyIndex: 69, legacyName: "PAN8"              , legacyMethod: "processPan"                    , newId: "PanVoice8"         , newMethod: "processPan"               , transformKind: "PAN"             , specialInline: false, drumClass: "global"  , drumRestoreSkip: false, newNotes: "processPan(v, 8). See PAN5." },

    // ---- index 70..79: UI toggles + extended params ----
    { legacyIndex: 70, legacyName: "UNLEARN"           , legacyMethod: "(UI-only)"                     , newId: ""                  , newMethod: null                       , transformKind: null              , specialInline: false, drumClass: "none"    , drumRestoreSkip: false, newNotes: "REMOVED: UI-only, no engine action, no OB-Xf equivalent." },
    { legacyIndex: 71, legacyName: "ECONOMY_MODE"      , legacyMethod: "procEconomyMode"               , newId: ""                  , newMethod: null                       , transformKind: null              , specialInline: false, drumClass: "none"    , drumRestoreSkip: false, newNotes: "REMOVED: OB-Xf has no economy mode (HQMode is the successor but maps from FILTER_WARM)." },
    { legacyIndex: 72, legacyName: "LFO_SYNC"          , legacyMethod: "procLfoSync"                   , newId: "LFO1TempoSync"     , newMethod: "processLFO1Sync"          , transformKind: "LFO1_SYNC"       , specialInline: true , drumClass: "global"  , drumRestoreSkip: false, newNotes: "SPECIAL INLINE: processLFO1Sync(v) (method name has no \"Tempo\"), then re-dispatch LFOFREQ from the mirror so a sequentially-loaded .fxp gets the right rate path. Shared globalLFO → drumClass global. Importer warns old sync behavior was unreliable." },
    { legacyIndex: 73, legacyName: "PW_ENV"            , legacyMethod: "processPwEnv"                  , newId: "EnvToPWAmount"     , newMethod: "processEnvToPWAmount"     , transformKind: "MUL"             , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "RESCALE: old linsc(v,0,0.85), new linsc(v,0,1.055555555) → native = v*(0.85/1.0555555555). Invert (exact): legacy = n*(1.0555555555/0.85)." },
    { legacyIndex: 74, legacyName: "PW_ENV_BOTH"       , legacyMethod: "processPwEnvBoth"              , newId: "EnvToPWBothOscs"   , newMethod: "processEnvToPWBothOscs"   , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold." },
    { legacyIndex: 75, legacyName: "ENV_PITCH_BOTH"    , legacyMethod: "processPitchModBoth"           , newId: "EnvToPitchBothOscs", newMethod: "processPitchBothOscs"     , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5. METHOD MISMATCH: method is processPitchBothOscs (no \"EnvTo\" prefix) — NOT processEnvToPitchBothOscs." },
    { legacyIndex: 76, legacyName: "FENV_INVERT"       , legacyMethod: "processInvertFenv"             , newId: "FilterEnvInvert"   , newMethod: "processFilterEnvInvert"   , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold." },
    { legacyIndex: 77, legacyName: "PW_OSC2_OFS"       , legacyMethod: "processPwOfs"                  , newId: "Osc2PWOffset"      , newMethod: "processOsc2PWOffset"      , transformKind: "MUL"             , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "RESCALE: old linsc(v,0,0.75), new linsc(v,0,0.95) → native = v*(0.75/0.95). Invert (exact): legacy = n*(0.95/0.75)." },
    { legacyIndex: 78, legacyName: "LEVEL_DIF"         , legacyMethod: "processLoudnessDetune"         , newId: "LevelSlop"         , newMethod: "processLevelSlop"         , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; both engines linsc(v,0,0.67) internally." },
    { legacyIndex: 79, legacyName: "SELF_OSC_PUSH"     , legacyMethod: "processSelfOscPush"            , newId: "Filter2PolePush"   , newMethod: "processFilter2PolePush"   , transformKind: "IDENTITY"        , specialInline: false, drumClass: "voice"   , drumRestoreSkip: false, newNotes: "1:1; >=0.5 threshold. RENAMED: old selfOscPush, new setFilter2PolePush." },
];

// =========================================================================
// PURE transform functions (generated). forward maps legacy 0..1 → native
// engine 0..1 (the applyLegacy math); invert maps native 0..1 → legacy 0..1
// (used to write the legacy param mirror when loading native OB-Xf .fxp
// named attributes). Implemented from the spec descriptors so tests can
// golden the math without touching the C side. Callers clamp inputs to
// [0,1] exactly as the C dispatcher does; these functions add no clamps
// beyond those the spec math itself specifies.
// =========================================================================

const clamp = (v: number, lo: number, hi: number): number => Math.min(hi, Math.max(lo, v));

// OB-Xd logsc/linsc + inverses — verbatim from ObxdImporter.cpp / main_obxd.cpp.
const xdLogsc = (p: number, lo: number, hi: number, rolloff: number): number =>
    ((Math.exp(p * Math.log(rolloff + 1)) - 1) / rolloff) * (hi - lo) + lo;
const xdLinsc = (p: number, lo: number, hi: number): number => lo + p * (hi - lo);
const xdInvLinsc = (y: number, lo: number, hi: number): number =>
    hi === lo ? 0 : clamp((y - lo) / (hi - lo), 0, 1);
const xdInvLogsc = (y: number, lo: number, hi: number, rolloff: number): number => {
    if (hi === lo) return 0;
    const t = (rolloff * (y - lo)) / (hi - lo) + 1;
    if (t <= 0) return 0;
    return clamp(Math.log(t) / Math.log(rolloff + 1), 0, 1);
};

export type ParamTransformFns = {
    readonly legacyIndex: number;
    /** legacy 0..1 → native engine 0..1 (the applyLegacy math) */
    readonly forward: (legacyValue: number) => number;
    /** native engine 0..1 → legacy 0..1 (mirror write); null where the spec says null */
    readonly invert: ((nativeValue: number) => number) | null;
};

/**
 * Name-keyed transforms for every legacy-mapped streaming name (including
 * both BENDRANGE halves). 76 entries in total. NEW-param
 * names (no legacy space) are intentionally absent.
 */
export const paramTransforms: Readonly<Record<string, ParamTransformFns>> = {
    "Volume": { legacyIndex: 2, forward: (v) => v, invert: (v) => v },

    "Polyphony": { legacyIndex: 3, forward: (v) => ((clamp(Math.round(v * 7) + 1, 1, 8) - 1) + 0.5) / 32, invert: (v) => (clamp(Math.round(v * 32), 1, 8) - 1) / 7 },

    "Tune": { legacyIndex: 4, forward: (v) => v, invert: (v) => v },

    "Transpose": { legacyIndex: 5, forward: (v) => clamp(Math.round(v * 4) + 1, 0, 4) * 0.25, invert: (v) => clamp((Math.round(v * 4) - 1) / 4, 0, 1) },

    "PitchBendUp": { legacyIndex: 6, forward: (v) => (v > 0.5 ? 12 : 2) / 48, invert: (v) => Math.round(v * 48) > 7 ? 1 : 0 },
    "PitchBendDown": { legacyIndex: 6, forward: (v) => (v > 0.5 ? 12 : 2) / 48, invert: (v) => Math.round(v * 48) > 7 ? 1 : 0 }, // split half — same forward/invert as the primary

    "BendOsc2Only": { legacyIndex: 7, forward: (v) => v, invert: (v) => v },

    "EnvLegatoMode": { legacyIndex: 8, forward: (v) => v, invert: (v) => v },

    "VibratoRate": { legacyIndex: 9, forward: (v) => xdInvLinsc(xdLogsc(v, 3, 10, 19), 2, 12), invert: (v) => xdInvLogsc(xdLinsc(v, 2, 12), 3, 10, 19) },

    "VelToFilterEnv": { legacyIndex: 10, forward: (v) => v, invert: (v) => v },

    "VelToAmpEnv": { legacyIndex: 11, forward: (v) => v, invert: (v) => v },

    "NotePriority": { legacyIndex: 12, forward: (v) => v > 0.5 ? 0 : 0.5, invert: (v) => v > 0.25 ? 0 : 1 },

    "Portamento": { legacyIndex: 13, forward: (v) => v, invert: (v) => v },

    "Unison": { legacyIndex: 14, forward: (v) => v, invert: (v) => v },

    "UnisonDetune": { legacyIndex: 15, forward: (v) => xdInvLogsc(xdLogsc(v, 0.001, 0.9, 19), 0.001, 1, 19), invert: (v) => xdInvLogsc(xdLogsc(v, 0.001, 1, 19), 0.001, 0.9, 19) },

    "Osc2Detune": { legacyIndex: 16, forward: (v) => v, invert: (v) => v },

    "LFO1Rate": { legacyIndex: 17, forward: (v) => xdInvLogsc(xdLogsc(v, 0, 50, 120), 0, 250, 3775), invert: null }, // specialInline: invert null; see transformKinds.LFO1_RATE

    "LFO1Wave1": { legacyIndex: 18, forward: (v) => v >= 0.5 ? 0 : 0.5, invert: (v) => v < 0.25 ? 1 : 0 },

    "LFO1Wave2": { legacyIndex: 19, forward: (v) => v >= 0.5 ? 0 : 0.5, invert: (v) => v < 0.25 ? 1 : 0 },

    "LFO1Wave3": { legacyIndex: 20, forward: (v) => v >= 0.5 ? 0 : 0.5, invert: (v) => v < 0.25 ? 1 : 0 },

    "LFO1ModAmount1": { legacyIndex: 21, forward: (v) => v, invert: (v) => v },

    "LFO1ModAmount2": { legacyIndex: 22, forward: (v) => v, invert: (v) => v },

    "LFO1ToOsc1Pitch": { legacyIndex: 23, forward: (v) => v >= 0.5 ? 0.5 : 0, invert: (v) => v >= 0.25 ? 1 : 0 },

    "LFO1ToOsc2Pitch": { legacyIndex: 24, forward: (v) => v >= 0.5 ? 0.5 : 0, invert: (v) => v >= 0.25 ? 1 : 0 },

    "LFO1ToFilterCutoff": { legacyIndex: 25, forward: (v) => v >= 0.5 ? 0.5 : 0, invert: (v) => v >= 0.25 ? 1 : 0 },

    "LFO1ToOsc1PW": { legacyIndex: 26, forward: (v) => v >= 0.5 ? 0.5 : 0, invert: (v) => v >= 0.25 ? 1 : 0 },

    "LFO1ToOsc2PW": { legacyIndex: 27, forward: (v) => v >= 0.5 ? 0.5 : 0, invert: (v) => v >= 0.25 ? 1 : 0 },

    "OscSync": { legacyIndex: 28, forward: (v) => v, invert: (v) => v },

    "OscCrossmod": { legacyIndex: 29, forward: (v) => v * 0.5, invert: (v) => v * 2 },

    "Osc1Pitch": { legacyIndex: 30, forward: (v) => v, invert: (v) => v },

    "Osc2Pitch": { legacyIndex: 31, forward: (v) => v, invert: (v) => v },

    "Osc1SawWave": { legacyIndex: 33, forward: (v) => v, invert: (v) => v },

    "Osc1PulseWave": { legacyIndex: 34, forward: (v) => v, invert: (v) => v },

    "Osc2SawWave": { legacyIndex: 35, forward: (v) => v, invert: (v) => v },

    "Osc2PulseWave": { legacyIndex: 36, forward: (v) => v, invert: (v) => v },

    "OscPW": { legacyIndex: 37, forward: (v) => v, invert: (v) => v },

    "OscBrightness": { legacyIndex: 38, forward: (v) => v, invert: (v) => v },

    "EnvToPitchAmount": { legacyIndex: 39, forward: (v) => v * 0.9, invert: (v) => v * 1.1111111111111112 },

    "Osc1Mix": { legacyIndex: 40, forward: (v) => v, invert: (v) => v },

    "Osc2Mix": { legacyIndex: 41, forward: (v) => v, invert: (v) => v },

    "NoiseMix": { legacyIndex: 42, forward: (v) => xdLogsc(v, 0, 1, 35), invert: (v) => xdInvLogsc(v, 0, 1, 35) },

    "FilterKeyFollow": { legacyIndex: 43, forward: (v) => v, invert: (v) => v },

    "FilterCutoff": { legacyIndex: 44, forward: (v) => v, invert: (v) => v },

    "FilterResonance": { legacyIndex: 45, forward: (v) => v, invert: (v) => v },

    "FilterMode": { legacyIndex: 46, forward: (v) => v, invert: (v) => v },

    "HQMode": { legacyIndex: 47, forward: (v) => v, invert: (v) => v },

    "Filter2PoleBPBlend": { legacyIndex: 48, forward: (v) => v, invert: (v) => v },

    "Filter4PoleMode": { legacyIndex: 49, forward: (v) => v, invert: (v) => v },

    "FilterEnvAmount": { legacyIndex: 50, forward: (v) => v, invert: (v) => v },

    "AmpEnvAttack": { legacyIndex: 51, forward: (v) => xdInvLogsc((xdLogsc(v, 4, 60000, 900) / 3), 4, 60000, 900), invert: (v) => xdInvLogsc((xdLogsc(v, 4, 60000, 900) * 3), 4, 60000, 900) },

    "AmpEnvDecay": { legacyIndex: 52, forward: (v) => v, invert: (v) => v },

    "AmpEnvSustain": { legacyIndex: 53, forward: (v) => v, invert: (v) => v },

    "AmpEnvRelease": { legacyIndex: 54, forward: (v) => v, invert: (v) => v },

    "FilterEnvAttack": { legacyIndex: 55, forward: (v) => xdInvLogsc((xdLogsc(v, 1, 60000, 900) / 3), 1, 60000, 900), invert: (v) => xdInvLogsc((xdLogsc(v, 1, 60000, 900) * 3), 1, 60000, 900) },

    "FilterEnvDecay": { legacyIndex: 56, forward: (v) => v, invert: (v) => v },

    "FilterEnvSustain": { legacyIndex: 57, forward: (v) => v, invert: (v) => v },

    "FilterEnvRelease": { legacyIndex: 58, forward: (v) => v, invert: (v) => v },

    "EnvelopeSlop": { legacyIndex: 59, forward: (v) => v, invert: (v) => v },

    "FilterSlop": { legacyIndex: 60, forward: (v) => v, invert: (v) => v },

    "PortamentoSlop": { legacyIndex: 61, forward: (v) => v, invert: (v) => v },

    "PanVoice1": { legacyIndex: 62, forward: (v) => v, invert: (v) => v },

    "PanVoice2": { legacyIndex: 63, forward: (v) => v, invert: (v) => v },

    "PanVoice3": { legacyIndex: 64, forward: (v) => v, invert: (v) => v },

    "PanVoice4": { legacyIndex: 65, forward: (v) => v, invert: (v) => v },

    "PanVoice5": { legacyIndex: 66, forward: (v) => v, invert: (v) => v },

    "PanVoice6": { legacyIndex: 67, forward: (v) => v, invert: (v) => v },

    "PanVoice7": { legacyIndex: 68, forward: (v) => v, invert: (v) => v },

    "PanVoice8": { legacyIndex: 69, forward: (v) => v, invert: (v) => v },

    "LFO1TempoSync": { legacyIndex: 72, forward: (v) => v, invert: null }, // specialInline: invert null; see transformKinds.LFO1_SYNC

    "EnvToPWAmount": { legacyIndex: 73, forward: (v) => v * 0.8052631579371191, invert: (v) => v * 1.2418300652941177 },

    "EnvToPWBothOscs": { legacyIndex: 74, forward: (v) => v, invert: (v) => v },

    "EnvToPitchBothOscs": { legacyIndex: 75, forward: (v) => v, invert: (v) => v },

    "FilterEnvInvert": { legacyIndex: 76, forward: (v) => v, invert: (v) => v },

    "Osc2PWOffset": { legacyIndex: 77, forward: (v) => v * 0.7894736842105263, invert: (v) => v * 1.2666666666666666 },

    "LevelSlop": { legacyIndex: 78, forward: (v) => v, invert: (v) => v },

    "Filter2PolePush": { legacyIndex: 79, forward: (v) => v, invert: (v) => v },
};
